package com.j5erp.entity;

import java.math.BigDecimal;

public class AdvanceDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.ADID
     *
     * @mbggenerated
     */
    private String adid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.ADLINE
     *
     * @mbggenerated
     */
    private Long adline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.ADMONEY
     *
     * @mbggenerated
     */
    private BigDecimal admoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.ADSINGLE
     *
     * @mbggenerated
     */
    private String adsingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.ADSOURCE
     *
     * @mbggenerated
     */
    private Long adsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.ADSUMMARY
     *
     * @mbggenerated
     */
    private String adsummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.TESTA
     *
     * @mbggenerated
     */
    private String testa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADVANCE_DETAIL.TESTB
     *
     * @mbggenerated
     */
    private String testb;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCE_DETAIL
     *
     * @mbggenerated
     */
    public AdvanceDetail(String adid, Long adline, BigDecimal admoney, String adsingle, Long adsource, String adsummary, String testa, String testb) {
        this.adid = adid;
        this.adline = adline;
        this.admoney = admoney;
        this.adsingle = adsingle;
        this.adsource = adsource;
        this.adsummary = adsummary;
        this.testa = testa;
        this.testb = testb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADVANCE_DETAIL
     *
     * @mbggenerated
     */
    public AdvanceDetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.ADID
     *
     * @return the value of ADVANCE_DETAIL.ADID
     *
     * @mbggenerated
     */
    public String getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.ADID
     *
     * @param adid the value for ADVANCE_DETAIL.ADID
     *
     * @mbggenerated
     */
    public void setAdid(String adid) {
        this.adid = adid == null ? null : adid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.ADLINE
     *
     * @return the value of ADVANCE_DETAIL.ADLINE
     *
     * @mbggenerated
     */
    public Long getAdline() {
        return adline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.ADLINE
     *
     * @param adline the value for ADVANCE_DETAIL.ADLINE
     *
     * @mbggenerated
     */
    public void setAdline(Long adline) {
        this.adline = adline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.ADMONEY
     *
     * @return the value of ADVANCE_DETAIL.ADMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getAdmoney() {
        return admoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.ADMONEY
     *
     * @param admoney the value for ADVANCE_DETAIL.ADMONEY
     *
     * @mbggenerated
     */
    public void setAdmoney(BigDecimal admoney) {
        this.admoney = admoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.ADSINGLE
     *
     * @return the value of ADVANCE_DETAIL.ADSINGLE
     *
     * @mbggenerated
     */
    public String getAdsingle() {
        return adsingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.ADSINGLE
     *
     * @param adsingle the value for ADVANCE_DETAIL.ADSINGLE
     *
     * @mbggenerated
     */
    public void setAdsingle(String adsingle) {
        this.adsingle = adsingle == null ? null : adsingle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.ADSOURCE
     *
     * @return the value of ADVANCE_DETAIL.ADSOURCE
     *
     * @mbggenerated
     */
    public Long getAdsource() {
        return adsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.ADSOURCE
     *
     * @param adsource the value for ADVANCE_DETAIL.ADSOURCE
     *
     * @mbggenerated
     */
    public void setAdsource(Long adsource) {
        this.adsource = adsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.ADSUMMARY
     *
     * @return the value of ADVANCE_DETAIL.ADSUMMARY
     *
     * @mbggenerated
     */
    public String getAdsummary() {
        return adsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.ADSUMMARY
     *
     * @param adsummary the value for ADVANCE_DETAIL.ADSUMMARY
     *
     * @mbggenerated
     */
    public void setAdsummary(String adsummary) {
        this.adsummary = adsummary == null ? null : adsummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.TESTA
     *
     * @return the value of ADVANCE_DETAIL.TESTA
     *
     * @mbggenerated
     */
    public String getTesta() {
        return testa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.TESTA
     *
     * @param testa the value for ADVANCE_DETAIL.TESTA
     *
     * @mbggenerated
     */
    public void setTesta(String testa) {
        this.testa = testa == null ? null : testa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADVANCE_DETAIL.TESTB
     *
     * @return the value of ADVANCE_DETAIL.TESTB
     *
     * @mbggenerated
     */
    public String getTestb() {
        return testb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADVANCE_DETAIL.TESTB
     *
     * @param testb the value for ADVANCE_DETAIL.TESTB
     *
     * @mbggenerated
     */
    public void setTestb(String testb) {
        this.testb = testb == null ? null : testb.trim();
    }
}