package com.j5erp.entity;

import java.math.BigDecimal;

public class BalanceAdvancedetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_ADVANCEDETAIL.BAID
     *
     * @mbggenerated
     */
    private String baid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_ADVANCEDETAIL.BALINE
     *
     * @mbggenerated
     */
    private Long baline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_ADVANCEDETAIL.ADID
     *
     * @mbggenerated
     */
    private String adid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_ADVANCEDETAIL.ADLINE
     *
     * @mbggenerated
     */
    private String adline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_ADVANCEDETAIL.BAMONEY
     *
     * @mbggenerated
     */
    private BigDecimal bamoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_ADVANCEDETAIL.TEST1
     *
     * @mbggenerated
     */
    private String test1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_ADVANCEDETAIL.TEST2
     *
     * @mbggenerated
     */
    private String test2;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_ADVANCEDETAIL
     *
     * @mbggenerated
     */
    public BalanceAdvancedetail(String baid, Long baline, String adid, String adline, BigDecimal bamoney, String test1, String test2) {
        this.baid = baid;
        this.baline = baline;
        this.adid = adid;
        this.adline = adline;
        this.bamoney = bamoney;
        this.test1 = test1;
        this.test2 = test2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_ADVANCEDETAIL
     *
     * @mbggenerated
     */
    public BalanceAdvancedetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_ADVANCEDETAIL.BAID
     *
     * @return the value of BALANCE_ADVANCEDETAIL.BAID
     *
     * @mbggenerated
     */
    public String getBaid() {
        return baid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_ADVANCEDETAIL.BAID
     *
     * @param baid the value for BALANCE_ADVANCEDETAIL.BAID
     *
     * @mbggenerated
     */
    public void setBaid(String baid) {
        this.baid = baid == null ? null : baid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_ADVANCEDETAIL.BALINE
     *
     * @return the value of BALANCE_ADVANCEDETAIL.BALINE
     *
     * @mbggenerated
     */
    public Long getBaline() {
        return baline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_ADVANCEDETAIL.BALINE
     *
     * @param baline the value for BALANCE_ADVANCEDETAIL.BALINE
     *
     * @mbggenerated
     */
    public void setBaline(Long baline) {
        this.baline = baline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_ADVANCEDETAIL.ADID
     *
     * @return the value of BALANCE_ADVANCEDETAIL.ADID
     *
     * @mbggenerated
     */
    public String getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_ADVANCEDETAIL.ADID
     *
     * @param adid the value for BALANCE_ADVANCEDETAIL.ADID
     *
     * @mbggenerated
     */
    public void setAdid(String adid) {
        this.adid = adid == null ? null : adid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_ADVANCEDETAIL.ADLINE
     *
     * @return the value of BALANCE_ADVANCEDETAIL.ADLINE
     *
     * @mbggenerated
     */
    public String getAdline() {
        return adline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_ADVANCEDETAIL.ADLINE
     *
     * @param adline the value for BALANCE_ADVANCEDETAIL.ADLINE
     *
     * @mbggenerated
     */
    public void setAdline(String adline) {
        this.adline = adline == null ? null : adline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_ADVANCEDETAIL.BAMONEY
     *
     * @return the value of BALANCE_ADVANCEDETAIL.BAMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getBamoney() {
        return bamoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_ADVANCEDETAIL.BAMONEY
     *
     * @param bamoney the value for BALANCE_ADVANCEDETAIL.BAMONEY
     *
     * @mbggenerated
     */
    public void setBamoney(BigDecimal bamoney) {
        this.bamoney = bamoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_ADVANCEDETAIL.TEST1
     *
     * @return the value of BALANCE_ADVANCEDETAIL.TEST1
     *
     * @mbggenerated
     */
    public String getTest1() {
        return test1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_ADVANCEDETAIL.TEST1
     *
     * @param test1 the value for BALANCE_ADVANCEDETAIL.TEST1
     *
     * @mbggenerated
     */
    public void setTest1(String test1) {
        this.test1 = test1 == null ? null : test1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_ADVANCEDETAIL.TEST2
     *
     * @return the value of BALANCE_ADVANCEDETAIL.TEST2
     *
     * @mbggenerated
     */
    public String getTest2() {
        return test2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_ADVANCEDETAIL.TEST2
     *
     * @param test2 the value for BALANCE_ADVANCEDETAIL.TEST2
     *
     * @mbggenerated
     */
    public void setTest2(String test2) {
        this.test2 = test2 == null ? null : test2.trim();
    }
}