package com.j5erp.entity;

import java.math.BigDecimal;

public class BalanceDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.BDID
     *
     * @mbggenerated
     */
    private String bdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.BDLINE
     *
     * @mbggenerated
     */
    private Long bdline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.BDSINGLE
     *
     * @mbggenerated
     */
    private String bdsingle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.BDSOURCE
     *
     * @mbggenerated
     */
    private String bdsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.BDPRIMARYMONEY
     *
     * @mbggenerated
     */
    private BigDecimal bdprimarymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.BDDISCOUNTSMONEY
     *
     * @mbggenerated
     */
    private BigDecimal bddiscountsmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.BDCHARGEMONEY
     *
     * @mbggenerated
     */
    private BigDecimal bdchargemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.TESTA
     *
     * @mbggenerated
     */
    private String testa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BALANCE_DETAIL.TESTB
     *
     * @mbggenerated
     */
    private String testb;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_DETAIL
     *
     * @mbggenerated
     */
    public BalanceDetail(String bdid, Long bdline, String bdsingle, String bdsource, BigDecimal bdprimarymoney, BigDecimal bddiscountsmoney, BigDecimal bdchargemoney, String testa, String testb) {
        this.bdid = bdid;
        this.bdline = bdline;
        this.bdsingle = bdsingle;
        this.bdsource = bdsource;
        this.bdprimarymoney = bdprimarymoney;
        this.bddiscountsmoney = bddiscountsmoney;
        this.bdchargemoney = bdchargemoney;
        this.testa = testa;
        this.testb = testb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_DETAIL
     *
     * @mbggenerated
     */
    public BalanceDetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.BDID
     *
     * @return the value of BALANCE_DETAIL.BDID
     *
     * @mbggenerated
     */
    public String getBdid() {
        return bdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.BDID
     *
     * @param bdid the value for BALANCE_DETAIL.BDID
     *
     * @mbggenerated
     */
    public void setBdid(String bdid) {
        this.bdid = bdid == null ? null : bdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.BDLINE
     *
     * @return the value of BALANCE_DETAIL.BDLINE
     *
     * @mbggenerated
     */
    public Long getBdline() {
        return bdline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.BDLINE
     *
     * @param bdline the value for BALANCE_DETAIL.BDLINE
     *
     * @mbggenerated
     */
    public void setBdline(Long bdline) {
        this.bdline = bdline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.BDSINGLE
     *
     * @return the value of BALANCE_DETAIL.BDSINGLE
     *
     * @mbggenerated
     */
    public String getBdsingle() {
        return bdsingle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.BDSINGLE
     *
     * @param bdsingle the value for BALANCE_DETAIL.BDSINGLE
     *
     * @mbggenerated
     */
    public void setBdsingle(String bdsingle) {
        this.bdsingle = bdsingle == null ? null : bdsingle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.BDSOURCE
     *
     * @return the value of BALANCE_DETAIL.BDSOURCE
     *
     * @mbggenerated
     */
    public String getBdsource() {
        return bdsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.BDSOURCE
     *
     * @param bdsource the value for BALANCE_DETAIL.BDSOURCE
     *
     * @mbggenerated
     */
    public void setBdsource(String bdsource) {
        this.bdsource = bdsource == null ? null : bdsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.BDPRIMARYMONEY
     *
     * @return the value of BALANCE_DETAIL.BDPRIMARYMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getBdprimarymoney() {
        return bdprimarymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.BDPRIMARYMONEY
     *
     * @param bdprimarymoney the value for BALANCE_DETAIL.BDPRIMARYMONEY
     *
     * @mbggenerated
     */
    public void setBdprimarymoney(BigDecimal bdprimarymoney) {
        this.bdprimarymoney = bdprimarymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.BDDISCOUNTSMONEY
     *
     * @return the value of BALANCE_DETAIL.BDDISCOUNTSMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getBddiscountsmoney() {
        return bddiscountsmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.BDDISCOUNTSMONEY
     *
     * @param bddiscountsmoney the value for BALANCE_DETAIL.BDDISCOUNTSMONEY
     *
     * @mbggenerated
     */
    public void setBddiscountsmoney(BigDecimal bddiscountsmoney) {
        this.bddiscountsmoney = bddiscountsmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.BDCHARGEMONEY
     *
     * @return the value of BALANCE_DETAIL.BDCHARGEMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getBdchargemoney() {
        return bdchargemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.BDCHARGEMONEY
     *
     * @param bdchargemoney the value for BALANCE_DETAIL.BDCHARGEMONEY
     *
     * @mbggenerated
     */
    public void setBdchargemoney(BigDecimal bdchargemoney) {
        this.bdchargemoney = bdchargemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.TESTA
     *
     * @return the value of BALANCE_DETAIL.TESTA
     *
     * @mbggenerated
     */
    public String getTesta() {
        return testa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.TESTA
     *
     * @param testa the value for BALANCE_DETAIL.TESTA
     *
     * @mbggenerated
     */
    public void setTesta(String testa) {
        this.testa = testa == null ? null : testa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BALANCE_DETAIL.TESTB
     *
     * @return the value of BALANCE_DETAIL.TESTB
     *
     * @mbggenerated
     */
    public String getTestb() {
        return testb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BALANCE_DETAIL.TESTB
     *
     * @param testb the value for BALANCE_DETAIL.TESTB
     *
     * @mbggenerated
     */
    public void setTestb(String testb) {
        this.testb = testb == null ? null : testb.trim();
    }
}