package com.j5erp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Buyerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.LINE
     *
     * @mbggenerated
     */
    private Integer line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.FID
     *
     * @mbggenerated
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.WID
     *
     * @mbggenerated
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.FROMID
     *
     * @mbggenerated
     */
    private String fromid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.FROMTYPE
     *
     * @mbggenerated
     */
    private String fromtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.PRICE
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.NUM
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.NOTNUM
     *
     * @mbggenerated
     */
    private Integer notnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.MONEY
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.TARIFF
     *
     * @mbggenerated
     */
    private BigDecimal tariff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.TARIFFMONEY
     *
     * @mbggenerated
     */
    private BigDecimal tariffmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.MONEYTARIFF
     *
     * @mbggenerated
     */
    private BigDecimal moneytariff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.GIFT
     *
     * @mbggenerated
     */
    private Integer gift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.COLUMNSTATE
     *
     * @mbggenerated
     */
    private Integer columnstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.COLUMN1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.COLUMN2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BUYERSON.COLUMN3
     *
     * @mbggenerated
     */
    private String column3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUYERSON
     *
     * @mbggenerated
     */
    public Buyerson(String id, Integer line, String fid, String wid, String fromid, String fromtype, Integer price, Integer num, Date time, Integer notnum, BigDecimal money, BigDecimal tariff, BigDecimal tariffmoney, BigDecimal moneytariff, Integer gift, String remark, Integer columnstate, String column1, String column2, String column3) {
        this.id = id;
        this.line = line;
        this.fid = fid;
        this.wid = wid;
        this.fromid = fromid;
        this.fromtype = fromtype;
        this.price = price;
        this.num = num;
        this.time = time;
        this.notnum = notnum;
        this.money = money;
        this.tariff = tariff;
        this.tariffmoney = tariffmoney;
        this.moneytariff = moneytariff;
        this.gift = gift;
        this.remark = remark;
        this.columnstate = columnstate;
        this.column1 = column1;
        this.column2 = column2;
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUYERSON
     *
     * @mbggenerated
     */
    public Buyerson() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.ID
     *
     * @return the value of BUYERSON.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.ID
     *
     * @param id the value for BUYERSON.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.LINE
     *
     * @return the value of BUYERSON.LINE
     *
     * @mbggenerated
     */
    public Integer getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.LINE
     *
     * @param line the value for BUYERSON.LINE
     *
     * @mbggenerated
     */
    public void setLine(Integer line) {
        this.line = line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.FID
     *
     * @return the value of BUYERSON.FID
     *
     * @mbggenerated
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.FID
     *
     * @param fid the value for BUYERSON.FID
     *
     * @mbggenerated
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.WID
     *
     * @return the value of BUYERSON.WID
     *
     * @mbggenerated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.WID
     *
     * @param wid the value for BUYERSON.WID
     *
     * @mbggenerated
     */
    public void setWid(String wid) {
        this.wid = wid == null ? null : wid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.FROMID
     *
     * @return the value of BUYERSON.FROMID
     *
     * @mbggenerated
     */
    public String getFromid() {
        return fromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.FROMID
     *
     * @param fromid the value for BUYERSON.FROMID
     *
     * @mbggenerated
     */
    public void setFromid(String fromid) {
        this.fromid = fromid == null ? null : fromid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.FROMTYPE
     *
     * @return the value of BUYERSON.FROMTYPE
     *
     * @mbggenerated
     */
    public String getFromtype() {
        return fromtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.FROMTYPE
     *
     * @param fromtype the value for BUYERSON.FROMTYPE
     *
     * @mbggenerated
     */
    public void setFromtype(String fromtype) {
        this.fromtype = fromtype == null ? null : fromtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.PRICE
     *
     * @return the value of BUYERSON.PRICE
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.PRICE
     *
     * @param price the value for BUYERSON.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.NUM
     *
     * @return the value of BUYERSON.NUM
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.NUM
     *
     * @param num the value for BUYERSON.NUM
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.TIME
     *
     * @return the value of BUYERSON.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.TIME
     *
     * @param time the value for BUYERSON.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.NOTNUM
     *
     * @return the value of BUYERSON.NOTNUM
     *
     * @mbggenerated
     */
    public Integer getNotnum() {
        return notnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.NOTNUM
     *
     * @param notnum the value for BUYERSON.NOTNUM
     *
     * @mbggenerated
     */
    public void setNotnum(Integer notnum) {
        this.notnum = notnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.MONEY
     *
     * @return the value of BUYERSON.MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.MONEY
     *
     * @param money the value for BUYERSON.MONEY
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.TARIFF
     *
     * @return the value of BUYERSON.TARIFF
     *
     * @mbggenerated
     */
    public BigDecimal getTariff() {
        return tariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.TARIFF
     *
     * @param tariff the value for BUYERSON.TARIFF
     *
     * @mbggenerated
     */
    public void setTariff(BigDecimal tariff) {
        this.tariff = tariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.TARIFFMONEY
     *
     * @return the value of BUYERSON.TARIFFMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getTariffmoney() {
        return tariffmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.TARIFFMONEY
     *
     * @param tariffmoney the value for BUYERSON.TARIFFMONEY
     *
     * @mbggenerated
     */
    public void setTariffmoney(BigDecimal tariffmoney) {
        this.tariffmoney = tariffmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.MONEYTARIFF
     *
     * @return the value of BUYERSON.MONEYTARIFF
     *
     * @mbggenerated
     */
    public BigDecimal getMoneytariff() {
        return moneytariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.MONEYTARIFF
     *
     * @param moneytariff the value for BUYERSON.MONEYTARIFF
     *
     * @mbggenerated
     */
    public void setMoneytariff(BigDecimal moneytariff) {
        this.moneytariff = moneytariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.GIFT
     *
     * @return the value of BUYERSON.GIFT
     *
     * @mbggenerated
     */
    public Integer getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.GIFT
     *
     * @param gift the value for BUYERSON.GIFT
     *
     * @mbggenerated
     */
    public void setGift(Integer gift) {
        this.gift = gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.REMARK
     *
     * @return the value of BUYERSON.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.REMARK
     *
     * @param remark the value for BUYERSON.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.COLUMNSTATE
     *
     * @return the value of BUYERSON.COLUMNSTATE
     *
     * @mbggenerated
     */
    public Integer getColumnstate() {
        return columnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.COLUMNSTATE
     *
     * @param columnstate the value for BUYERSON.COLUMNSTATE
     *
     * @mbggenerated
     */
    public void setColumnstate(Integer columnstate) {
        this.columnstate = columnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.COLUMN1
     *
     * @return the value of BUYERSON.COLUMN1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.COLUMN1
     *
     * @param column1 the value for BUYERSON.COLUMN1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.COLUMN2
     *
     * @return the value of BUYERSON.COLUMN2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.COLUMN2
     *
     * @param column2 the value for BUYERSON.COLUMN2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BUYERSON.COLUMN3
     *
     * @return the value of BUYERSON.COLUMN3
     *
     * @mbggenerated
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BUYERSON.COLUMN3
     *
     * @param column3 the value for BUYERSON.COLUMN3
     *
     * @mbggenerated
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }
}