package com.j5erp.entity;

import java.util.Date;

public class Check1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDNUMBERS
     *
     * @mbggenerated
     */
    private String pdnumbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDWAREHOUSE
     *
     * @mbggenerated
     */
    private String pdwarehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDDATE
     *
     * @mbggenerated
     */
    private Date pddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDPERSONNEL
     *
     * @mbggenerated
     */
    private String pdpersonnel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDZDPERSONNEL
     *
     * @mbggenerated
     */
    private String pdzdpersonnel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDDEPARTMENT
     *
     * @mbggenerated
     */
    private String pddepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDRECHECKNUMBER
     *
     * @mbggenerated
     */
    private String pdrechecknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDCOLUMN1
     *
     * @mbggenerated
     */
    private String pdcolumn1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDCOLUMN2
     *
     * @mbggenerated
     */
    private String pdcolumn2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDREMARK
     *
     * @mbggenerated
     */
    private String pdremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHECK1.PDEXAMINESTATUS
     *
     * @mbggenerated
     */
    private Short pdexaminestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK1
     *
     * @mbggenerated
     */
    public Check1(String pdnumbers, String pdwarehouse, Date pddate, String pdpersonnel, String pdzdpersonnel, String pddepartment, String pdrechecknumber, String pdcolumn1, String pdcolumn2, String pdremark, Short pdexaminestatus) {
        this.pdnumbers = pdnumbers;
        this.pdwarehouse = pdwarehouse;
        this.pddate = pddate;
        this.pdpersonnel = pdpersonnel;
        this.pdzdpersonnel = pdzdpersonnel;
        this.pddepartment = pddepartment;
        this.pdrechecknumber = pdrechecknumber;
        this.pdcolumn1 = pdcolumn1;
        this.pdcolumn2 = pdcolumn2;
        this.pdremark = pdremark;
        this.pdexaminestatus = pdexaminestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECK1
     *
     * @mbggenerated
     */
    public Check1() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDNUMBERS
     *
     * @return the value of CHECK1.PDNUMBERS
     *
     * @mbggenerated
     */
    public String getPdnumbers() {
        return pdnumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDNUMBERS
     *
     * @param pdnumbers the value for CHECK1.PDNUMBERS
     *
     * @mbggenerated
     */
    public void setPdnumbers(String pdnumbers) {
        this.pdnumbers = pdnumbers == null ? null : pdnumbers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDWAREHOUSE
     *
     * @return the value of CHECK1.PDWAREHOUSE
     *
     * @mbggenerated
     */
    public String getPdwarehouse() {
        return pdwarehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDWAREHOUSE
     *
     * @param pdwarehouse the value for CHECK1.PDWAREHOUSE
     *
     * @mbggenerated
     */
    public void setPdwarehouse(String pdwarehouse) {
        this.pdwarehouse = pdwarehouse == null ? null : pdwarehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDDATE
     *
     * @return the value of CHECK1.PDDATE
     *
     * @mbggenerated
     */
    public Date getPddate() {
        return pddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDDATE
     *
     * @param pddate the value for CHECK1.PDDATE
     *
     * @mbggenerated
     */
    public void setPddate(Date pddate) {
        this.pddate = pddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDPERSONNEL
     *
     * @return the value of CHECK1.PDPERSONNEL
     *
     * @mbggenerated
     */
    public String getPdpersonnel() {
        return pdpersonnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDPERSONNEL
     *
     * @param pdpersonnel the value for CHECK1.PDPERSONNEL
     *
     * @mbggenerated
     */
    public void setPdpersonnel(String pdpersonnel) {
        this.pdpersonnel = pdpersonnel == null ? null : pdpersonnel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDZDPERSONNEL
     *
     * @return the value of CHECK1.PDZDPERSONNEL
     *
     * @mbggenerated
     */
    public String getPdzdpersonnel() {
        return pdzdpersonnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDZDPERSONNEL
     *
     * @param pdzdpersonnel the value for CHECK1.PDZDPERSONNEL
     *
     * @mbggenerated
     */
    public void setPdzdpersonnel(String pdzdpersonnel) {
        this.pdzdpersonnel = pdzdpersonnel == null ? null : pdzdpersonnel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDDEPARTMENT
     *
     * @return the value of CHECK1.PDDEPARTMENT
     *
     * @mbggenerated
     */
    public String getPddepartment() {
        return pddepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDDEPARTMENT
     *
     * @param pddepartment the value for CHECK1.PDDEPARTMENT
     *
     * @mbggenerated
     */
    public void setPddepartment(String pddepartment) {
        this.pddepartment = pddepartment == null ? null : pddepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDRECHECKNUMBER
     *
     * @return the value of CHECK1.PDRECHECKNUMBER
     *
     * @mbggenerated
     */
    public String getPdrechecknumber() {
        return pdrechecknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDRECHECKNUMBER
     *
     * @param pdrechecknumber the value for CHECK1.PDRECHECKNUMBER
     *
     * @mbggenerated
     */
    public void setPdrechecknumber(String pdrechecknumber) {
        this.pdrechecknumber = pdrechecknumber == null ? null : pdrechecknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDCOLUMN1
     *
     * @return the value of CHECK1.PDCOLUMN1
     *
     * @mbggenerated
     */
    public String getPdcolumn1() {
        return pdcolumn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDCOLUMN1
     *
     * @param pdcolumn1 the value for CHECK1.PDCOLUMN1
     *
     * @mbggenerated
     */
    public void setPdcolumn1(String pdcolumn1) {
        this.pdcolumn1 = pdcolumn1 == null ? null : pdcolumn1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDCOLUMN2
     *
     * @return the value of CHECK1.PDCOLUMN2
     *
     * @mbggenerated
     */
    public String getPdcolumn2() {
        return pdcolumn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDCOLUMN2
     *
     * @param pdcolumn2 the value for CHECK1.PDCOLUMN2
     *
     * @mbggenerated
     */
    public void setPdcolumn2(String pdcolumn2) {
        this.pdcolumn2 = pdcolumn2 == null ? null : pdcolumn2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDREMARK
     *
     * @return the value of CHECK1.PDREMARK
     *
     * @mbggenerated
     */
    public String getPdremark() {
        return pdremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDREMARK
     *
     * @param pdremark the value for CHECK1.PDREMARK
     *
     * @mbggenerated
     */
    public void setPdremark(String pdremark) {
        this.pdremark = pdremark == null ? null : pdremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHECK1.PDEXAMINESTATUS
     *
     * @return the value of CHECK1.PDEXAMINESTATUS
     *
     * @mbggenerated
     */
    public Short getPdexaminestatus() {
        return pdexaminestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHECK1.PDEXAMINESTATUS
     *
     * @param pdexaminestatus the value for CHECK1.PDEXAMINESTATUS
     *
     * @mbggenerated
     */
    public void setPdexaminestatus(Short pdexaminestatus) {
        this.pdexaminestatus = pdexaminestatus;
    }
}