package com.j5erp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERID
     *
     * @mbggenerated
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERRECEIVABLEBELONGING
     *
     * @mbggenerated
     */
    private String customerreceivablebelonging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERNAME
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERCLASSID
     *
     * @mbggenerated
     */
    private String customerclassid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERSIMPLENAME
     *
     * @mbggenerated
     */
    private String customersimplename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERADDRESSID
     *
     * @mbggenerated
     */
    private String customeraddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERCURRENCY
     *
     * @mbggenerated
     */
    private String customercurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERFUNCTIONARY
     *
     * @mbggenerated
     */
    private String customerfunctionary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.PERSONNELID
     *
     * @mbggenerated
     */
    private String personnelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERCONTACT
     *
     * @mbggenerated
     */
    private String customercontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERPHONE
     *
     * @mbggenerated
     */
    private String customerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERAMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal customeramount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERTRADE
     *
     * @mbggenerated
     */
    private String customertrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERSMAIL
     *
     * @mbggenerated
     */
    private String customersmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERBANKACCOUNT
     *
     * @mbggenerated
     */
    private String customerbankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERBANKNAME
     *
     * @mbggenerated
     */
    private String customerbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERPORTRAITURE
     *
     * @mbggenerated
     */
    private String customerportraiture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERSELLLEVEL
     *
     * @mbggenerated
     */
    private Short customerselllevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERTAX
     *
     * @mbggenerated
     */
    private Short customertax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERCREATEDATE
     *
     * @mbggenerated
     */
    private Date customercreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERRECEIVABLELIMIT
     *
     * @mbggenerated
     */
    private BigDecimal customerreceivablelimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERSURPLUSLIMIT
     *
     * @mbggenerated
     */
    private BigDecimal customersurpluslimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERADVANCESRECEIVED
     *
     * @mbggenerated
     */
    private BigDecimal customeradvancesreceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERACCOUNTDUE
     *
     * @mbggenerated
     */
    private BigDecimal customeraccountdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLIENT.CUSTOMERREMARK
     *
     * @mbggenerated
     */
    private String customerremark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT
     *
     * @mbggenerated
     */
    public Client(String customerid, String customerreceivablebelonging, String customername, String customerclassid, String customersimplename, String customeraddressid, String customercurrency, String customerfunctionary, String personnelid, String customercontact, String customerphone, BigDecimal customeramount, String customertrade, String customersmail, String customerbankaccount, String customerbankname, String customerportraiture, Short customerselllevel, Short customertax, Date customercreatedate, BigDecimal customerreceivablelimit, BigDecimal customersurpluslimit, BigDecimal customeradvancesreceived, BigDecimal customeraccountdue, String customerremark) {
        this.customerid = customerid;
        this.customerreceivablebelonging = customerreceivablebelonging;
        this.customername = customername;
        this.customerclassid = customerclassid;
        this.customersimplename = customersimplename;
        this.customeraddressid = customeraddressid;
        this.customercurrency = customercurrency;
        this.customerfunctionary = customerfunctionary;
        this.personnelid = personnelid;
        this.customercontact = customercontact;
        this.customerphone = customerphone;
        this.customeramount = customeramount;
        this.customertrade = customertrade;
        this.customersmail = customersmail;
        this.customerbankaccount = customerbankaccount;
        this.customerbankname = customerbankname;
        this.customerportraiture = customerportraiture;
        this.customerselllevel = customerselllevel;
        this.customertax = customertax;
        this.customercreatedate = customercreatedate;
        this.customerreceivablelimit = customerreceivablelimit;
        this.customersurpluslimit = customersurpluslimit;
        this.customeradvancesreceived = customeradvancesreceived;
        this.customeraccountdue = customeraccountdue;
        this.customerremark = customerremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CLIENT
     *
     * @mbggenerated
     */
    public Client() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERID
     *
     * @return the value of CLIENT.CUSTOMERID
     *
     * @mbggenerated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERID
     *
     * @param customerid the value for CLIENT.CUSTOMERID
     *
     * @mbggenerated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERRECEIVABLEBELONGING
     *
     * @return the value of CLIENT.CUSTOMERRECEIVABLEBELONGING
     *
     * @mbggenerated
     */
    public String getCustomerreceivablebelonging() {
        return customerreceivablebelonging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERRECEIVABLEBELONGING
     *
     * @param customerreceivablebelonging the value for CLIENT.CUSTOMERRECEIVABLEBELONGING
     *
     * @mbggenerated
     */
    public void setCustomerreceivablebelonging(String customerreceivablebelonging) {
        this.customerreceivablebelonging = customerreceivablebelonging == null ? null : customerreceivablebelonging.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERNAME
     *
     * @return the value of CLIENT.CUSTOMERNAME
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERNAME
     *
     * @param customername the value for CLIENT.CUSTOMERNAME
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERCLASSID
     *
     * @return the value of CLIENT.CUSTOMERCLASSID
     *
     * @mbggenerated
     */
    public String getCustomerclassid() {
        return customerclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERCLASSID
     *
     * @param customerclassid the value for CLIENT.CUSTOMERCLASSID
     *
     * @mbggenerated
     */
    public void setCustomerclassid(String customerclassid) {
        this.customerclassid = customerclassid == null ? null : customerclassid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERSIMPLENAME
     *
     * @return the value of CLIENT.CUSTOMERSIMPLENAME
     *
     * @mbggenerated
     */
    public String getCustomersimplename() {
        return customersimplename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERSIMPLENAME
     *
     * @param customersimplename the value for CLIENT.CUSTOMERSIMPLENAME
     *
     * @mbggenerated
     */
    public void setCustomersimplename(String customersimplename) {
        this.customersimplename = customersimplename == null ? null : customersimplename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERADDRESSID
     *
     * @return the value of CLIENT.CUSTOMERADDRESSID
     *
     * @mbggenerated
     */
    public String getCustomeraddressid() {
        return customeraddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERADDRESSID
     *
     * @param customeraddressid the value for CLIENT.CUSTOMERADDRESSID
     *
     * @mbggenerated
     */
    public void setCustomeraddressid(String customeraddressid) {
        this.customeraddressid = customeraddressid == null ? null : customeraddressid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERCURRENCY
     *
     * @return the value of CLIENT.CUSTOMERCURRENCY
     *
     * @mbggenerated
     */
    public String getCustomercurrency() {
        return customercurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERCURRENCY
     *
     * @param customercurrency the value for CLIENT.CUSTOMERCURRENCY
     *
     * @mbggenerated
     */
    public void setCustomercurrency(String customercurrency) {
        this.customercurrency = customercurrency == null ? null : customercurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERFUNCTIONARY
     *
     * @return the value of CLIENT.CUSTOMERFUNCTIONARY
     *
     * @mbggenerated
     */
    public String getCustomerfunctionary() {
        return customerfunctionary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERFUNCTIONARY
     *
     * @param customerfunctionary the value for CLIENT.CUSTOMERFUNCTIONARY
     *
     * @mbggenerated
     */
    public void setCustomerfunctionary(String customerfunctionary) {
        this.customerfunctionary = customerfunctionary == null ? null : customerfunctionary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.PERSONNELID
     *
     * @return the value of CLIENT.PERSONNELID
     *
     * @mbggenerated
     */
    public String getPersonnelid() {
        return personnelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.PERSONNELID
     *
     * @param personnelid the value for CLIENT.PERSONNELID
     *
     * @mbggenerated
     */
    public void setPersonnelid(String personnelid) {
        this.personnelid = personnelid == null ? null : personnelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERCONTACT
     *
     * @return the value of CLIENT.CUSTOMERCONTACT
     *
     * @mbggenerated
     */
    public String getCustomercontact() {
        return customercontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERCONTACT
     *
     * @param customercontact the value for CLIENT.CUSTOMERCONTACT
     *
     * @mbggenerated
     */
    public void setCustomercontact(String customercontact) {
        this.customercontact = customercontact == null ? null : customercontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERPHONE
     *
     * @return the value of CLIENT.CUSTOMERPHONE
     *
     * @mbggenerated
     */
    public String getCustomerphone() {
        return customerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERPHONE
     *
     * @param customerphone the value for CLIENT.CUSTOMERPHONE
     *
     * @mbggenerated
     */
    public void setCustomerphone(String customerphone) {
        this.customerphone = customerphone == null ? null : customerphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERAMOUNT
     *
     * @return the value of CLIENT.CUSTOMERAMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getCustomeramount() {
        return customeramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERAMOUNT
     *
     * @param customeramount the value for CLIENT.CUSTOMERAMOUNT
     *
     * @mbggenerated
     */
    public void setCustomeramount(BigDecimal customeramount) {
        this.customeramount = customeramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERTRADE
     *
     * @return the value of CLIENT.CUSTOMERTRADE
     *
     * @mbggenerated
     */
    public String getCustomertrade() {
        return customertrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERTRADE
     *
     * @param customertrade the value for CLIENT.CUSTOMERTRADE
     *
     * @mbggenerated
     */
    public void setCustomertrade(String customertrade) {
        this.customertrade = customertrade == null ? null : customertrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERSMAIL
     *
     * @return the value of CLIENT.CUSTOMERSMAIL
     *
     * @mbggenerated
     */
    public String getCustomersmail() {
        return customersmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERSMAIL
     *
     * @param customersmail the value for CLIENT.CUSTOMERSMAIL
     *
     * @mbggenerated
     */
    public void setCustomersmail(String customersmail) {
        this.customersmail = customersmail == null ? null : customersmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERBANKACCOUNT
     *
     * @return the value of CLIENT.CUSTOMERBANKACCOUNT
     *
     * @mbggenerated
     */
    public String getCustomerbankaccount() {
        return customerbankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERBANKACCOUNT
     *
     * @param customerbankaccount the value for CLIENT.CUSTOMERBANKACCOUNT
     *
     * @mbggenerated
     */
    public void setCustomerbankaccount(String customerbankaccount) {
        this.customerbankaccount = customerbankaccount == null ? null : customerbankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERBANKNAME
     *
     * @return the value of CLIENT.CUSTOMERBANKNAME
     *
     * @mbggenerated
     */
    public String getCustomerbankname() {
        return customerbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERBANKNAME
     *
     * @param customerbankname the value for CLIENT.CUSTOMERBANKNAME
     *
     * @mbggenerated
     */
    public void setCustomerbankname(String customerbankname) {
        this.customerbankname = customerbankname == null ? null : customerbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERPORTRAITURE
     *
     * @return the value of CLIENT.CUSTOMERPORTRAITURE
     *
     * @mbggenerated
     */
    public String getCustomerportraiture() {
        return customerportraiture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERPORTRAITURE
     *
     * @param customerportraiture the value for CLIENT.CUSTOMERPORTRAITURE
     *
     * @mbggenerated
     */
    public void setCustomerportraiture(String customerportraiture) {
        this.customerportraiture = customerportraiture == null ? null : customerportraiture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERSELLLEVEL
     *
     * @return the value of CLIENT.CUSTOMERSELLLEVEL
     *
     * @mbggenerated
     */
    public Short getCustomerselllevel() {
        return customerselllevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERSELLLEVEL
     *
     * @param customerselllevel the value for CLIENT.CUSTOMERSELLLEVEL
     *
     * @mbggenerated
     */
    public void setCustomerselllevel(Short customerselllevel) {
        this.customerselllevel = customerselllevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERTAX
     *
     * @return the value of CLIENT.CUSTOMERTAX
     *
     * @mbggenerated
     */
    public Short getCustomertax() {
        return customertax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERTAX
     *
     * @param customertax the value for CLIENT.CUSTOMERTAX
     *
     * @mbggenerated
     */
    public void setCustomertax(Short customertax) {
        this.customertax = customertax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERCREATEDATE
     *
     * @return the value of CLIENT.CUSTOMERCREATEDATE
     *
     * @mbggenerated
     */
    public Date getCustomercreatedate() {
        return customercreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERCREATEDATE
     *
     * @param customercreatedate the value for CLIENT.CUSTOMERCREATEDATE
     *
     * @mbggenerated
     */
    public void setCustomercreatedate(Date customercreatedate) {
        this.customercreatedate = customercreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERRECEIVABLELIMIT
     *
     * @return the value of CLIENT.CUSTOMERRECEIVABLELIMIT
     *
     * @mbggenerated
     */
    public BigDecimal getCustomerreceivablelimit() {
        return customerreceivablelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERRECEIVABLELIMIT
     *
     * @param customerreceivablelimit the value for CLIENT.CUSTOMERRECEIVABLELIMIT
     *
     * @mbggenerated
     */
    public void setCustomerreceivablelimit(BigDecimal customerreceivablelimit) {
        this.customerreceivablelimit = customerreceivablelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERSURPLUSLIMIT
     *
     * @return the value of CLIENT.CUSTOMERSURPLUSLIMIT
     *
     * @mbggenerated
     */
    public BigDecimal getCustomersurpluslimit() {
        return customersurpluslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERSURPLUSLIMIT
     *
     * @param customersurpluslimit the value for CLIENT.CUSTOMERSURPLUSLIMIT
     *
     * @mbggenerated
     */
    public void setCustomersurpluslimit(BigDecimal customersurpluslimit) {
        this.customersurpluslimit = customersurpluslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERADVANCESRECEIVED
     *
     * @return the value of CLIENT.CUSTOMERADVANCESRECEIVED
     *
     * @mbggenerated
     */
    public BigDecimal getCustomeradvancesreceived() {
        return customeradvancesreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERADVANCESRECEIVED
     *
     * @param customeradvancesreceived the value for CLIENT.CUSTOMERADVANCESRECEIVED
     *
     * @mbggenerated
     */
    public void setCustomeradvancesreceived(BigDecimal customeradvancesreceived) {
        this.customeradvancesreceived = customeradvancesreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERACCOUNTDUE
     *
     * @return the value of CLIENT.CUSTOMERACCOUNTDUE
     *
     * @mbggenerated
     */
    public BigDecimal getCustomeraccountdue() {
        return customeraccountdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERACCOUNTDUE
     *
     * @param customeraccountdue the value for CLIENT.CUSTOMERACCOUNTDUE
     *
     * @mbggenerated
     */
    public void setCustomeraccountdue(BigDecimal customeraccountdue) {
        this.customeraccountdue = customeraccountdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLIENT.CUSTOMERREMARK
     *
     * @return the value of CLIENT.CUSTOMERREMARK
     *
     * @mbggenerated
     */
    public String getCustomerremark() {
        return customerremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLIENT.CUSTOMERREMARK
     *
     * @param customerremark the value for CLIENT.CUSTOMERREMARK
     *
     * @mbggenerated
     */
    public void setCustomerremark(String customerremark) {
        this.customerremark = customerremark == null ? null : customerremark.trim();
    }
}