package com.j5erp.entity;


public class Cointype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COINTYPE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COINTYPE.CNAME
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COINTYPE.PAITIES
     *
     * @mbggenerated
     */
    private Double paities;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COINTYPE
     *
     * @mbggenerated
     */
    public Cointype(String id, String cname, Double paities) {
        this.id = id;
        this.cname = cname;
        this.paities = paities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COINTYPE
     *
     * @mbggenerated
     */
    public Cointype() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COINTYPE.ID
     *
     * @return the value of COINTYPE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COINTYPE.ID
     *
     * @param id the value for COINTYPE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COINTYPE.CNAME
     *
     * @return the value of COINTYPE.CNAME
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COINTYPE.CNAME
     *
     * @param cname the value for COINTYPE.CNAME
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COINTYPE.PAITIES
     *
     * @return the value of COINTYPE.PAITIES
     *
     * @mbggenerated
     */
    public Double getPaities() {
        return paities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COINTYPE.PAITIES
     *
     * @param paities the value for COINTYPE.PAITIES
     *
     * @mbggenerated
     */
    public void setPaities(Double paities) {
        this.paities = paities;
    }
}