package com.j5erp.entity;

import java.math.BigDecimal;

public class Costdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.CID
     *
     * @mbggenerated
     */
    private BigDecimal cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.PID
     *
     * @mbggenerated
     */
    private BigDecimal pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.CLOUD
     *
     * @mbggenerated
     */
    private BigDecimal cloud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.COSTNAME
     *
     * @mbggenerated
     */
    private String costname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.CURRENCY
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.EXCHANGERARATE
     *
     * @mbggenerated
     */
    private BigDecimal exchangerarate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.MONEY
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.STANDARDCOIN
     *
     * @mbggenerated
     */
    private BigDecimal standardcoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.CHECKSTATUS
     *
     * @mbggenerated
     */
    private BigDecimal checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.DEMO1
     *
     * @mbggenerated
     */
    private BigDecimal demo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.DEMO2
     *
     * @mbggenerated
     */
    private String demo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COSTDETAIL.DEMO3
     *
     * @mbggenerated
     */
    private BigDecimal demo3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COSTDETAIL
     *
     * @mbggenerated
     */
    public Costdetail(BigDecimal cid, BigDecimal pid, BigDecimal cloud, String costname, String currency, BigDecimal exchangerarate, BigDecimal money, BigDecimal standardcoin, BigDecimal checkstatus, BigDecimal demo1, String demo2, BigDecimal demo3) {
        this.cid = cid;
        this.pid = pid;
        this.cloud = cloud;
        this.costname = costname;
        this.currency = currency;
        this.exchangerarate = exchangerarate;
        this.money = money;
        this.standardcoin = standardcoin;
        this.checkstatus = checkstatus;
        this.demo1 = demo1;
        this.demo2 = demo2;
        this.demo3 = demo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COSTDETAIL
     *
     * @mbggenerated
     */
    public Costdetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.CID
     *
     * @return the value of COSTDETAIL.CID
     *
     * @mbggenerated
     */
    public BigDecimal getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.CID
     *
     * @param cid the value for COSTDETAIL.CID
     *
     * @mbggenerated
     */
    public void setCid(BigDecimal cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.PID
     *
     * @return the value of COSTDETAIL.PID
     *
     * @mbggenerated
     */
    public BigDecimal getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.PID
     *
     * @param pid the value for COSTDETAIL.PID
     *
     * @mbggenerated
     */
    public void setPid(BigDecimal pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.CLOUD
     *
     * @return the value of COSTDETAIL.CLOUD
     *
     * @mbggenerated
     */
    public BigDecimal getCloud() {
        return cloud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.CLOUD
     *
     * @param cloud the value for COSTDETAIL.CLOUD
     *
     * @mbggenerated
     */
    public void setCloud(BigDecimal cloud) {
        this.cloud = cloud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.COSTNAME
     *
     * @return the value of COSTDETAIL.COSTNAME
     *
     * @mbggenerated
     */
    public String getCostname() {
        return costname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.COSTNAME
     *
     * @param costname the value for COSTDETAIL.COSTNAME
     *
     * @mbggenerated
     */
    public void setCostname(String costname) {
        this.costname = costname == null ? null : costname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.CURRENCY
     *
     * @return the value of COSTDETAIL.CURRENCY
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.CURRENCY
     *
     * @param currency the value for COSTDETAIL.CURRENCY
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.EXCHANGERARATE
     *
     * @return the value of COSTDETAIL.EXCHANGERARATE
     *
     * @mbggenerated
     */
    public BigDecimal getExchangerarate() {
        return exchangerarate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.EXCHANGERARATE
     *
     * @param exchangerarate the value for COSTDETAIL.EXCHANGERARATE
     *
     * @mbggenerated
     */
    public void setExchangerarate(BigDecimal exchangerarate) {
        this.exchangerarate = exchangerarate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.MONEY
     *
     * @return the value of COSTDETAIL.MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.MONEY
     *
     * @param money the value for COSTDETAIL.MONEY
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.STANDARDCOIN
     *
     * @return the value of COSTDETAIL.STANDARDCOIN
     *
     * @mbggenerated
     */
    public BigDecimal getStandardcoin() {
        return standardcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.STANDARDCOIN
     *
     * @param standardcoin the value for COSTDETAIL.STANDARDCOIN
     *
     * @mbggenerated
     */
    public void setStandardcoin(BigDecimal standardcoin) {
        this.standardcoin = standardcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.CHECKSTATUS
     *
     * @return the value of COSTDETAIL.CHECKSTATUS
     *
     * @mbggenerated
     */
    public BigDecimal getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.CHECKSTATUS
     *
     * @param checkstatus the value for COSTDETAIL.CHECKSTATUS
     *
     * @mbggenerated
     */
    public void setCheckstatus(BigDecimal checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.DEMO1
     *
     * @return the value of COSTDETAIL.DEMO1
     *
     * @mbggenerated
     */
    public BigDecimal getDemo1() {
        return demo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.DEMO1
     *
     * @param demo1 the value for COSTDETAIL.DEMO1
     *
     * @mbggenerated
     */
    public void setDemo1(BigDecimal demo1) {
        this.demo1 = demo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.DEMO2
     *
     * @return the value of COSTDETAIL.DEMO2
     *
     * @mbggenerated
     */
    public String getDemo2() {
        return demo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.DEMO2
     *
     * @param demo2 the value for COSTDETAIL.DEMO2
     *
     * @mbggenerated
     */
    public void setDemo2(String demo2) {
        this.demo2 = demo2 == null ? null : demo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COSTDETAIL.DEMO3
     *
     * @return the value of COSTDETAIL.DEMO3
     *
     * @mbggenerated
     */
    public BigDecimal getDemo3() {
        return demo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COSTDETAIL.DEMO3
     *
     * @param demo3 the value for COSTDETAIL.DEMO3
     *
     * @mbggenerated
     */
    public void setDemo3(BigDecimal demo3) {
        this.demo3 = demo3;
    }
}