package com.j5erp.entity;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPARTMENTID
     *
     * @mbggenerated
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEPARTMENTCN_NAME
     *
     * @mbggenerated
     */
    private String departmentcnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.STANDBY_1
     *
     * @mbggenerated
     */
    private String standby1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.STANDBY_2
     *
     * @mbggenerated
     */
    private String standby2;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated
     */
    public Department(String departmentid, String departmentcnName, String standby1, String standby2) {
        this.departmentid = departmentid;
        this.departmentcnName = departmentcnName;
        this.standby1 = standby1;
        this.standby2 = standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated
     */
    public Department() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPARTMENTID
     *
     * @return the value of DEPARTMENT.DEPARTMENTID
     *
     * @mbggenerated
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPARTMENTID
     *
     * @param departmentid the value for DEPARTMENT.DEPARTMENTID
     *
     * @mbggenerated
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEPARTMENTCN_NAME
     *
     * @return the value of DEPARTMENT.DEPARTMENTCN_NAME
     *
     * @mbggenerated
     */
    public String getDepartmentcnName() {
        return departmentcnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEPARTMENTCN_NAME
     *
     * @param departmentcnName the value for DEPARTMENT.DEPARTMENTCN_NAME
     *
     * @mbggenerated
     */
    public void setDepartmentcnName(String departmentcnName) {
        this.departmentcnName = departmentcnName == null ? null : departmentcnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.STANDBY_1
     *
     * @return the value of DEPARTMENT.STANDBY_1
     *
     * @mbggenerated
     */
    public String getStandby1() {
        return standby1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.STANDBY_1
     *
     * @param standby1 the value for DEPARTMENT.STANDBY_1
     *
     * @mbggenerated
     */
    public void setStandby1(String standby1) {
        this.standby1 = standby1 == null ? null : standby1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.STANDBY_2
     *
     * @return the value of DEPARTMENT.STANDBY_2
     *
     * @mbggenerated
     */
    public String getStandby2() {
        return standby2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.STANDBY_2
     *
     * @param standby2 the value for DEPARTMENT.STANDBY_2
     *
     * @mbggenerated
     */
    public void setStandby2(String standby2) {
        this.standby2 = standby2 == null ? null : standby2.trim();
    }
}