package com.j5erp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Enquiry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.SUPPLIERNAME
     *
     * @mbggenerated
     */
    private String suppliername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.MONEYTYPE
     *
     * @mbggenerated
     */
    private Integer moneytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.TAXSTATE
     *
     * @mbggenerated
     */
    private Integer taxstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.RATE
     *
     * @mbggenerated
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.DELIVER
     *
     * @mbggenerated
     */
    private String deliver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.TOUCHING
     *
     * @mbggenerated
     */
    private String touching;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.SECTION
     *
     * @mbggenerated
     */
    private String section;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.CHECKPEOPLE
     *
     * @mbggenerated
     */
    private String checkpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.CHECKSTATE
     *
     * @mbggenerated
     */
    private Integer checkstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.COLUMNSTATE
     *
     * @mbggenerated
     */
    private Integer columnstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.COLUMN1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.COLUMN2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRY.COLUMN3
     *
     * @mbggenerated
     */
    private String column3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRY
     *
     * @mbggenerated
     */
    public Enquiry(String id, Date time, String suppliername, Integer moneytype, Integer taxstate, BigDecimal rate, String deliver, String touching, String section, String checkpeople, String remark, Integer checkstate, Integer columnstate, String column1, String column2, String column3) {
        this.id = id;
        this.time = time;
        this.suppliername = suppliername;
        this.moneytype = moneytype;
        this.taxstate = taxstate;
        this.rate = rate;
        this.deliver = deliver;
        this.touching = touching;
        this.section = section;
        this.checkpeople = checkpeople;
        this.remark = remark;
        this.checkstate = checkstate;
        this.columnstate = columnstate;
        this.column1 = column1;
        this.column2 = column2;
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRY
     *
     * @mbggenerated
     */
    public Enquiry() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.ID
     *
     * @return the value of ENQUIRY.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.ID
     *
     * @param id the value for ENQUIRY.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.TIME
     *
     * @return the value of ENQUIRY.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.TIME
     *
     * @param time the value for ENQUIRY.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.SUPPLIERNAME
     *
     * @return the value of ENQUIRY.SUPPLIERNAME
     *
     * @mbggenerated
     */
    public String getSuppliername() {
        return suppliername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.SUPPLIERNAME
     *
     * @param suppliername the value for ENQUIRY.SUPPLIERNAME
     *
     * @mbggenerated
     */
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername == null ? null : suppliername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.MONEYTYPE
     *
     * @return the value of ENQUIRY.MONEYTYPE
     *
     * @mbggenerated
     */
    public Integer getMoneytype() {
        return moneytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.MONEYTYPE
     *
     * @param moneytype the value for ENQUIRY.MONEYTYPE
     *
     * @mbggenerated
     */
    public void setMoneytype(Integer moneytype) {
        this.moneytype = moneytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.TAXSTATE
     *
     * @return the value of ENQUIRY.TAXSTATE
     *
     * @mbggenerated
     */
    public Integer getTaxstate() {
        return taxstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.TAXSTATE
     *
     * @param taxstate the value for ENQUIRY.TAXSTATE
     *
     * @mbggenerated
     */
    public void setTaxstate(Integer taxstate) {
        this.taxstate = taxstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.RATE
     *
     * @return the value of ENQUIRY.RATE
     *
     * @mbggenerated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.RATE
     *
     * @param rate the value for ENQUIRY.RATE
     *
     * @mbggenerated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.DELIVER
     *
     * @return the value of ENQUIRY.DELIVER
     *
     * @mbggenerated
     */
    public String getDeliver() {
        return deliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.DELIVER
     *
     * @param deliver the value for ENQUIRY.DELIVER
     *
     * @mbggenerated
     */
    public void setDeliver(String deliver) {
        this.deliver = deliver == null ? null : deliver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.TOUCHING
     *
     * @return the value of ENQUIRY.TOUCHING
     *
     * @mbggenerated
     */
    public String getTouching() {
        return touching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.TOUCHING
     *
     * @param touching the value for ENQUIRY.TOUCHING
     *
     * @mbggenerated
     */
    public void setTouching(String touching) {
        this.touching = touching == null ? null : touching.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.SECTION
     *
     * @return the value of ENQUIRY.SECTION
     *
     * @mbggenerated
     */
    public String getSection() {
        return section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.SECTION
     *
     * @param section the value for ENQUIRY.SECTION
     *
     * @mbggenerated
     */
    public void setSection(String section) {
        this.section = section == null ? null : section.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.CHECKPEOPLE
     *
     * @return the value of ENQUIRY.CHECKPEOPLE
     *
     * @mbggenerated
     */
    public String getCheckpeople() {
        return checkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.CHECKPEOPLE
     *
     * @param checkpeople the value for ENQUIRY.CHECKPEOPLE
     *
     * @mbggenerated
     */
    public void setCheckpeople(String checkpeople) {
        this.checkpeople = checkpeople == null ? null : checkpeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.REMARK
     *
     * @return the value of ENQUIRY.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.REMARK
     *
     * @param remark the value for ENQUIRY.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.CHECKSTATE
     *
     * @return the value of ENQUIRY.CHECKSTATE
     *
     * @mbggenerated
     */
    public Integer getCheckstate() {
        return checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.CHECKSTATE
     *
     * @param checkstate the value for ENQUIRY.CHECKSTATE
     *
     * @mbggenerated
     */
    public void setCheckstate(Integer checkstate) {
        this.checkstate = checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.COLUMNSTATE
     *
     * @return the value of ENQUIRY.COLUMNSTATE
     *
     * @mbggenerated
     */
    public Integer getColumnstate() {
        return columnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.COLUMNSTATE
     *
     * @param columnstate the value for ENQUIRY.COLUMNSTATE
     *
     * @mbggenerated
     */
    public void setColumnstate(Integer columnstate) {
        this.columnstate = columnstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.COLUMN1
     *
     * @return the value of ENQUIRY.COLUMN1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.COLUMN1
     *
     * @param column1 the value for ENQUIRY.COLUMN1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.COLUMN2
     *
     * @return the value of ENQUIRY.COLUMN2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.COLUMN2
     *
     * @param column2 the value for ENQUIRY.COLUMN2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRY.COLUMN3
     *
     * @return the value of ENQUIRY.COLUMN3
     *
     * @mbggenerated
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRY.COLUMN3
     *
     * @param column3 the value for ENQUIRY.COLUMN3
     *
     * @mbggenerated
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }
}