package com.j5erp.entity;

import java.math.BigDecimal;

public class Enquirysons {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.LINE
     *
     * @mbggenerated
     */
    private String line;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.FID
     *
     * @mbggenerated
     */
    private String fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.WID
     *
     * @mbggenerated
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.FROMID
     *
     * @mbggenerated
     */
    private String fromid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.FROMTYPE
     *
     * @mbggenerated
     */
    private String fromtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.PRICE
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.NUM
     *
     * @mbggenerated
     */
    private Short num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.MONEY
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.TARIFF
     *
     * @mbggenerated
     */
    private BigDecimal tariff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.TARIFFMONEY
     *
     * @mbggenerated
     */
    private BigDecimal tariffmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.MONEYTARIFF
     *
     * @mbggenerated
     */
    private BigDecimal moneytariff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.GIFT
     *
     * @mbggenerated
     */
    private Short gift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.COLUMN1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.COLUMN2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ENQUIRYSONS.COLUMN3
     *
     * @mbggenerated
     */
    private String column3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRYSONS
     *
     * @mbggenerated
     */
    public Enquirysons(String id, String line, String fid, String wid, String fromid, String fromtype, BigDecimal price, Short num, BigDecimal money, BigDecimal tariff, BigDecimal tariffmoney, BigDecimal moneytariff, Short gift, String remark, String column1, String column2, String column3) {
        this.id = id;
        this.line = line;
        this.fid = fid;
        this.wid = wid;
        this.fromid = fromid;
        this.fromtype = fromtype;
        this.price = price;
        this.num = num;
        this.money = money;
        this.tariff = tariff;
        this.tariffmoney = tariffmoney;
        this.moneytariff = moneytariff;
        this.gift = gift;
        this.remark = remark;
        this.column1 = column1;
        this.column2 = column2;
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRYSONS
     *
     * @mbggenerated
     */
    public Enquirysons() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.ID
     *
     * @return the value of ENQUIRYSONS.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.ID
     *
     * @param id the value for ENQUIRYSONS.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.LINE
     *
     * @return the value of ENQUIRYSONS.LINE
     *
     * @mbggenerated
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.LINE
     *
     * @param line the value for ENQUIRYSONS.LINE
     *
     * @mbggenerated
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.FID
     *
     * @return the value of ENQUIRYSONS.FID
     *
     * @mbggenerated
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.FID
     *
     * @param fid the value for ENQUIRYSONS.FID
     *
     * @mbggenerated
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.WID
     *
     * @return the value of ENQUIRYSONS.WID
     *
     * @mbggenerated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.WID
     *
     * @param wid the value for ENQUIRYSONS.WID
     *
     * @mbggenerated
     */
    public void setWid(String wid) {
        this.wid = wid == null ? null : wid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.FROMID
     *
     * @return the value of ENQUIRYSONS.FROMID
     *
     * @mbggenerated
     */
    public String getFromid() {
        return fromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.FROMID
     *
     * @param fromid the value for ENQUIRYSONS.FROMID
     *
     * @mbggenerated
     */
    public void setFromid(String fromid) {
        this.fromid = fromid == null ? null : fromid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.FROMTYPE
     *
     * @return the value of ENQUIRYSONS.FROMTYPE
     *
     * @mbggenerated
     */
    public String getFromtype() {
        return fromtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.FROMTYPE
     *
     * @param fromtype the value for ENQUIRYSONS.FROMTYPE
     *
     * @mbggenerated
     */
    public void setFromtype(String fromtype) {
        this.fromtype = fromtype == null ? null : fromtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.PRICE
     *
     * @return the value of ENQUIRYSONS.PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.PRICE
     *
     * @param price the value for ENQUIRYSONS.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.NUM
     *
     * @return the value of ENQUIRYSONS.NUM
     *
     * @mbggenerated
     */
    public Short getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.NUM
     *
     * @param num the value for ENQUIRYSONS.NUM
     *
     * @mbggenerated
     */
    public void setNum(Short num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.MONEY
     *
     * @return the value of ENQUIRYSONS.MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.MONEY
     *
     * @param money the value for ENQUIRYSONS.MONEY
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.TARIFF
     *
     * @return the value of ENQUIRYSONS.TARIFF
     *
     * @mbggenerated
     */
    public BigDecimal getTariff() {
        return tariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.TARIFF
     *
     * @param tariff the value for ENQUIRYSONS.TARIFF
     *
     * @mbggenerated
     */
    public void setTariff(BigDecimal tariff) {
        this.tariff = tariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.TARIFFMONEY
     *
     * @return the value of ENQUIRYSONS.TARIFFMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getTariffmoney() {
        return tariffmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.TARIFFMONEY
     *
     * @param tariffmoney the value for ENQUIRYSONS.TARIFFMONEY
     *
     * @mbggenerated
     */
    public void setTariffmoney(BigDecimal tariffmoney) {
        this.tariffmoney = tariffmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.MONEYTARIFF
     *
     * @return the value of ENQUIRYSONS.MONEYTARIFF
     *
     * @mbggenerated
     */
    public BigDecimal getMoneytariff() {
        return moneytariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.MONEYTARIFF
     *
     * @param moneytariff the value for ENQUIRYSONS.MONEYTARIFF
     *
     * @mbggenerated
     */
    public void setMoneytariff(BigDecimal moneytariff) {
        this.moneytariff = moneytariff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.GIFT
     *
     * @return the value of ENQUIRYSONS.GIFT
     *
     * @mbggenerated
     */
    public Short getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.GIFT
     *
     * @param gift the value for ENQUIRYSONS.GIFT
     *
     * @mbggenerated
     */
    public void setGift(Short gift) {
        this.gift = gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.REMARK
     *
     * @return the value of ENQUIRYSONS.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.REMARK
     *
     * @param remark the value for ENQUIRYSONS.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.COLUMN1
     *
     * @return the value of ENQUIRYSONS.COLUMN1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.COLUMN1
     *
     * @param column1 the value for ENQUIRYSONS.COLUMN1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.COLUMN2
     *
     * @return the value of ENQUIRYSONS.COLUMN2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.COLUMN2
     *
     * @param column2 the value for ENQUIRYSONS.COLUMN2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ENQUIRYSONS.COLUMN3
     *
     * @return the value of ENQUIRYSONS.COLUMN3
     *
     * @mbggenerated
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ENQUIRYSONS.COLUMN3
     *
     * @param column3 the value for ENQUIRYSONS.COLUMN3
     *
     * @mbggenerated
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }
}