package com.j5erp.entity;

import java.math.BigDecimal;

public class Estimatemoneybilldetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTIMATEMONEYBILLDETAIL.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTIMATEMONEYBILLDETAIL.LINENO
     *
     * @mbggenerated
     */
    private Long lineno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTIMATEMONEYBILLDETAIL.BILLTYPEID
     *
     * @mbggenerated
     */
    private Short billtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTIMATEMONEYBILLDETAIL.BILLNO
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTIMATEMONEYBILLDETAIL.ESTIMATEMONEY
     *
     * @mbggenerated
     */
    private BigDecimal estimatemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESTIMATEMONEYBILLDETAIL.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESTIMATEMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    public Estimatemoneybilldetail(String id, Long lineno, Short billtypeid, String billno, BigDecimal estimatemoney, String remark) {
        this.id = id;
        this.lineno = lineno;
        this.billtypeid = billtypeid;
        this.billno = billno;
        this.estimatemoney = estimatemoney;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESTIMATEMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    public Estimatemoneybilldetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTIMATEMONEYBILLDETAIL.ID
     *
     * @return the value of ESTIMATEMONEYBILLDETAIL.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTIMATEMONEYBILLDETAIL.ID
     *
     * @param id the value for ESTIMATEMONEYBILLDETAIL.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTIMATEMONEYBILLDETAIL.LINENO
     *
     * @return the value of ESTIMATEMONEYBILLDETAIL.LINENO
     *
     * @mbggenerated
     */
    public Long getLineno() {
        return lineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTIMATEMONEYBILLDETAIL.LINENO
     *
     * @param lineno the value for ESTIMATEMONEYBILLDETAIL.LINENO
     *
     * @mbggenerated
     */
    public void setLineno(Long lineno) {
        this.lineno = lineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTIMATEMONEYBILLDETAIL.BILLTYPEID
     *
     * @return the value of ESTIMATEMONEYBILLDETAIL.BILLTYPEID
     *
     * @mbggenerated
     */
    public Short getBilltypeid() {
        return billtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTIMATEMONEYBILLDETAIL.BILLTYPEID
     *
     * @param billtypeid the value for ESTIMATEMONEYBILLDETAIL.BILLTYPEID
     *
     * @mbggenerated
     */
    public void setBilltypeid(Short billtypeid) {
        this.billtypeid = billtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTIMATEMONEYBILLDETAIL.BILLNO
     *
     * @return the value of ESTIMATEMONEYBILLDETAIL.BILLNO
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTIMATEMONEYBILLDETAIL.BILLNO
     *
     * @param billno the value for ESTIMATEMONEYBILLDETAIL.BILLNO
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTIMATEMONEYBILLDETAIL.ESTIMATEMONEY
     *
     * @return the value of ESTIMATEMONEYBILLDETAIL.ESTIMATEMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getEstimatemoney() {
        return estimatemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTIMATEMONEYBILLDETAIL.ESTIMATEMONEY
     *
     * @param estimatemoney the value for ESTIMATEMONEYBILLDETAIL.ESTIMATEMONEY
     *
     * @mbggenerated
     */
    public void setEstimatemoney(BigDecimal estimatemoney) {
        this.estimatemoney = estimatemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESTIMATEMONEYBILLDETAIL.REMARK
     *
     * @return the value of ESTIMATEMONEYBILLDETAIL.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESTIMATEMONEYBILLDETAIL.REMARK
     *
     * @param remark the value for ESTIMATEMONEYBILLDETAIL.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}