package com.j5erp.entity;

public class Nationality {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NATIONALITY.NATIONALITYID
     *
     * @mbggenerated
     */
    private String nationalityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NATIONALITY.NATIONALITYCN_NAME
     *
     * @mbggenerated
     */
    private String nationalitycnName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated
     */
    public Nationality(String nationalityid, String nationalitycnName) {
        this.nationalityid = nationalityid;
        this.nationalitycnName = nationalitycnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated
     */
    public Nationality() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.NATIONALITYID
     *
     * @return the value of NATIONALITY.NATIONALITYID
     *
     * @mbggenerated
     */
    public String getNationalityid() {
        return nationalityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.NATIONALITYID
     *
     * @param nationalityid the value for NATIONALITY.NATIONALITYID
     *
     * @mbggenerated
     */
    public void setNationalityid(String nationalityid) {
        this.nationalityid = nationalityid == null ? null : nationalityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NATIONALITY.NATIONALITYCN_NAME
     *
     * @return the value of NATIONALITY.NATIONALITYCN_NAME
     *
     * @mbggenerated
     */
    public String getNationalitycnName() {
        return nationalitycnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NATIONALITY.NATIONALITYCN_NAME
     *
     * @param nationalitycnName the value for NATIONALITY.NATIONALITYCN_NAME
     *
     * @mbggenerated
     */
    public void setNationalitycnName(String nationalitycnName) {
        this.nationalitycnName = nationalitycnName == null ? null : nationalitycnName.trim();
    }
}