package com.j5erp.entity;

import java.util.Date;

public class Purchaserequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGBILLNUMBER
     *
     * @mbggenerated
     */
    private String qgbillnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGTYPE
     *
     * @mbggenerated
     */
    private String qgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGDATE
     *
     * @mbggenerated
     */
    private Date qgdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGBILLSTATE
     *
     * @mbggenerated
     */
    private Short qgbillstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGPERSONNEL
     *
     * @mbggenerated
     */
    private String qgpersonnel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGZDPERSONNEL
     *
     * @mbggenerated
     */
    private String qgzdpersonnel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGDEPARTMENT
     *
     * @mbggenerated
     */
    private String qgdepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGFHDEPARTMENT
     *
     * @mbggenerated
     */
    private String qgfhdepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGHEAD
     *
     * @mbggenerated
     */
    private String qghead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGCOLUMN1
     *
     * @mbggenerated
     */
    private String qgcolumn1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGEND
     *
     * @mbggenerated
     */
    private String qgend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGCOLUMN2
     *
     * @mbggenerated
     */
    private String qgcolumn2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGREMARK
     *
     * @mbggenerated
     */
    private String qgremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUEST.QGEXAMINESTATUS
     *
     * @mbggenerated
     */
    private Short qgexaminestatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUEST
     *
     * @mbggenerated
     */
    public Purchaserequest(String qgbillnumber, String qgtype, Date qgdate, Short qgbillstate, String qgpersonnel, String qgzdpersonnel, String qgdepartment, String qgfhdepartment, String qghead, String qgcolumn1, String qgend, String qgcolumn2, String qgremark, Short qgexaminestatus) {
        this.qgbillnumber = qgbillnumber;
        this.qgtype = qgtype;
        this.qgdate = qgdate;
        this.qgbillstate = qgbillstate;
        this.qgpersonnel = qgpersonnel;
        this.qgzdpersonnel = qgzdpersonnel;
        this.qgdepartment = qgdepartment;
        this.qgfhdepartment = qgfhdepartment;
        this.qghead = qghead;
        this.qgcolumn1 = qgcolumn1;
        this.qgend = qgend;
        this.qgcolumn2 = qgcolumn2;
        this.qgremark = qgremark;
        this.qgexaminestatus = qgexaminestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUEST
     *
     * @mbggenerated
     */
    public Purchaserequest() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGBILLNUMBER
     *
     * @return the value of PURCHASEREQUEST.QGBILLNUMBER
     *
     * @mbggenerated
     */
    public String getQgbillnumber() {
        return qgbillnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGBILLNUMBER
     *
     * @param qgbillnumber the value for PURCHASEREQUEST.QGBILLNUMBER
     *
     * @mbggenerated
     */
    public void setQgbillnumber(String qgbillnumber) {
        this.qgbillnumber = qgbillnumber == null ? null : qgbillnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGTYPE
     *
     * @return the value of PURCHASEREQUEST.QGTYPE
     *
     * @mbggenerated
     */
    public String getQgtype() {
        return qgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGTYPE
     *
     * @param qgtype the value for PURCHASEREQUEST.QGTYPE
     *
     * @mbggenerated
     */
    public void setQgtype(String qgtype) {
        this.qgtype = qgtype == null ? null : qgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGDATE
     *
     * @return the value of PURCHASEREQUEST.QGDATE
     *
     * @mbggenerated
     */
    public Date getQgdate() {
        return qgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGDATE
     *
     * @param qgdate the value for PURCHASEREQUEST.QGDATE
     *
     * @mbggenerated
     */
    public void setQgdate(Date qgdate) {
        this.qgdate = qgdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGBILLSTATE
     *
     * @return the value of PURCHASEREQUEST.QGBILLSTATE
     *
     * @mbggenerated
     */
    public Short getQgbillstate() {
        return qgbillstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGBILLSTATE
     *
     * @param qgbillstate the value for PURCHASEREQUEST.QGBILLSTATE
     *
     * @mbggenerated
     */
    public void setQgbillstate(Short qgbillstate) {
        this.qgbillstate = qgbillstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGPERSONNEL
     *
     * @return the value of PURCHASEREQUEST.QGPERSONNEL
     *
     * @mbggenerated
     */
    public String getQgpersonnel() {
        return qgpersonnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGPERSONNEL
     *
     * @param qgpersonnel the value for PURCHASEREQUEST.QGPERSONNEL
     *
     * @mbggenerated
     */
    public void setQgpersonnel(String qgpersonnel) {
        this.qgpersonnel = qgpersonnel == null ? null : qgpersonnel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGZDPERSONNEL
     *
     * @return the value of PURCHASEREQUEST.QGZDPERSONNEL
     *
     * @mbggenerated
     */
    public String getQgzdpersonnel() {
        return qgzdpersonnel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGZDPERSONNEL
     *
     * @param qgzdpersonnel the value for PURCHASEREQUEST.QGZDPERSONNEL
     *
     * @mbggenerated
     */
    public void setQgzdpersonnel(String qgzdpersonnel) {
        this.qgzdpersonnel = qgzdpersonnel == null ? null : qgzdpersonnel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGDEPARTMENT
     *
     * @return the value of PURCHASEREQUEST.QGDEPARTMENT
     *
     * @mbggenerated
     */
    public String getQgdepartment() {
        return qgdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGDEPARTMENT
     *
     * @param qgdepartment the value for PURCHASEREQUEST.QGDEPARTMENT
     *
     * @mbggenerated
     */
    public void setQgdepartment(String qgdepartment) {
        this.qgdepartment = qgdepartment == null ? null : qgdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGFHDEPARTMENT
     *
     * @return the value of PURCHASEREQUEST.QGFHDEPARTMENT
     *
     * @mbggenerated
     */
    public String getQgfhdepartment() {
        return qgfhdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGFHDEPARTMENT
     *
     * @param qgfhdepartment the value for PURCHASEREQUEST.QGFHDEPARTMENT
     *
     * @mbggenerated
     */
    public void setQgfhdepartment(String qgfhdepartment) {
        this.qgfhdepartment = qgfhdepartment == null ? null : qgfhdepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGHEAD
     *
     * @return the value of PURCHASEREQUEST.QGHEAD
     *
     * @mbggenerated
     */
    public String getQghead() {
        return qghead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGHEAD
     *
     * @param qghead the value for PURCHASEREQUEST.QGHEAD
     *
     * @mbggenerated
     */
    public void setQghead(String qghead) {
        this.qghead = qghead == null ? null : qghead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGCOLUMN1
     *
     * @return the value of PURCHASEREQUEST.QGCOLUMN1
     *
     * @mbggenerated
     */
    public String getQgcolumn1() {
        return qgcolumn1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGCOLUMN1
     *
     * @param qgcolumn1 the value for PURCHASEREQUEST.QGCOLUMN1
     *
     * @mbggenerated
     */
    public void setQgcolumn1(String qgcolumn1) {
        this.qgcolumn1 = qgcolumn1 == null ? null : qgcolumn1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGEND
     *
     * @return the value of PURCHASEREQUEST.QGEND
     *
     * @mbggenerated
     */
    public String getQgend() {
        return qgend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGEND
     *
     * @param qgend the value for PURCHASEREQUEST.QGEND
     *
     * @mbggenerated
     */
    public void setQgend(String qgend) {
        this.qgend = qgend == null ? null : qgend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGCOLUMN2
     *
     * @return the value of PURCHASEREQUEST.QGCOLUMN2
     *
     * @mbggenerated
     */
    public String getQgcolumn2() {
        return qgcolumn2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGCOLUMN2
     *
     * @param qgcolumn2 the value for PURCHASEREQUEST.QGCOLUMN2
     *
     * @mbggenerated
     */
    public void setQgcolumn2(String qgcolumn2) {
        this.qgcolumn2 = qgcolumn2 == null ? null : qgcolumn2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGREMARK
     *
     * @return the value of PURCHASEREQUEST.QGREMARK
     *
     * @mbggenerated
     */
    public String getQgremark() {
        return qgremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGREMARK
     *
     * @param qgremark the value for PURCHASEREQUEST.QGREMARK
     *
     * @mbggenerated
     */
    public void setQgremark(String qgremark) {
        this.qgremark = qgremark == null ? null : qgremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUEST.QGEXAMINESTATUS
     *
     * @return the value of PURCHASEREQUEST.QGEXAMINESTATUS
     *
     * @mbggenerated
     */
    public Short getQgexaminestatus() {
        return qgexaminestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUEST.QGEXAMINESTATUS
     *
     * @param qgexaminestatus the value for PURCHASEREQUEST.QGEXAMINESTATUS
     *
     * @mbggenerated
     */
    public void setQgexaminestatus(Short qgexaminestatus) {
        this.qgexaminestatus = qgexaminestatus;
    }
}