package com.j5erp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Purchaserequests {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGBILLNUMBERS
     *
     * @mbggenerated
     */
    private String qgbillnumbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGLINE
     *
     * @mbggenerated
     */
    private String qgline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGMATERIALID
     *
     * @mbggenerated
     */
    private String qgmaterialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGMATERIALNAME
     *
     * @mbggenerated
     */
    private String qgmaterialname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGMATERIALTYPE
     *
     * @mbggenerated
     */
    private String qgmaterialtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGUNIT
     *
     * @mbggenerated
     */
    private String qgunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGNUMBER
     *
     * @mbggenerated
     */
    private Short qgnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGSTANDARDJJ
     *
     * @mbggenerated
     */
    private BigDecimal qgstandardjj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGSTANDARDJJJE
     *
     * @mbggenerated
     */
    private BigDecimal qgstandardjjje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGCURRENCY
     *
     * @mbggenerated
     */
    private String qgcurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGPRICE
     *
     * @mbggenerated
     */
    private BigDecimal qgprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGJJMONEY
     *
     * @mbggenerated
     */
    private BigDecimal qgjjmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGNEEDDATE
     *
     * @mbggenerated
     */
    private Date qgneeddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGSUGGESTDATE
     *
     * @mbggenerated
     */
    private Date qgsuggestdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGTYPEREMARK
     *
     * @mbggenerated
     */
    private String qgtyperemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGSOURCEBILL
     *
     * @mbggenerated
     */
    private String qgsourcebill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PURCHASEREQUESTS.QGSOURCENUMBERS
     *
     * @mbggenerated
     */
    private String qgsourcenumbers;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUESTS
     *
     * @mbggenerated
     */
    public Purchaserequests(String qgbillnumbers, String qgline, String qgmaterialid, String qgmaterialname, String qgmaterialtype, String qgunit, Short qgnumber, BigDecimal qgstandardjj, BigDecimal qgstandardjjje, String qgcurrency, BigDecimal qgprice, BigDecimal qgjjmoney, Date qgneeddate, Date qgsuggestdate, String qgtyperemark, String qgsourcebill, String qgsourcenumbers) {
        this.qgbillnumbers = qgbillnumbers;
        this.qgline = qgline;
        this.qgmaterialid = qgmaterialid;
        this.qgmaterialname = qgmaterialname;
        this.qgmaterialtype = qgmaterialtype;
        this.qgunit = qgunit;
        this.qgnumber = qgnumber;
        this.qgstandardjj = qgstandardjj;
        this.qgstandardjjje = qgstandardjjje;
        this.qgcurrency = qgcurrency;
        this.qgprice = qgprice;
        this.qgjjmoney = qgjjmoney;
        this.qgneeddate = qgneeddate;
        this.qgsuggestdate = qgsuggestdate;
        this.qgtyperemark = qgtyperemark;
        this.qgsourcebill = qgsourcebill;
        this.qgsourcenumbers = qgsourcenumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUESTS
     *
     * @mbggenerated
     */
    public Purchaserequests() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGBILLNUMBERS
     *
     * @return the value of PURCHASEREQUESTS.QGBILLNUMBERS
     *
     * @mbggenerated
     */
    public String getQgbillnumbers() {
        return qgbillnumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGBILLNUMBERS
     *
     * @param qgbillnumbers the value for PURCHASEREQUESTS.QGBILLNUMBERS
     *
     * @mbggenerated
     */
    public void setQgbillnumbers(String qgbillnumbers) {
        this.qgbillnumbers = qgbillnumbers == null ? null : qgbillnumbers.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGLINE
     *
     * @return the value of PURCHASEREQUESTS.QGLINE
     *
     * @mbggenerated
     */
    public String getQgline() {
        return qgline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGLINE
     *
     * @param qgline the value for PURCHASEREQUESTS.QGLINE
     *
     * @mbggenerated
     */
    public void setQgline(String qgline) {
        this.qgline = qgline == null ? null : qgline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGMATERIALID
     *
     * @return the value of PURCHASEREQUESTS.QGMATERIALID
     *
     * @mbggenerated
     */
    public String getQgmaterialid() {
        return qgmaterialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGMATERIALID
     *
     * @param qgmaterialid the value for PURCHASEREQUESTS.QGMATERIALID
     *
     * @mbggenerated
     */
    public void setQgmaterialid(String qgmaterialid) {
        this.qgmaterialid = qgmaterialid == null ? null : qgmaterialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGMATERIALNAME
     *
     * @return the value of PURCHASEREQUESTS.QGMATERIALNAME
     *
     * @mbggenerated
     */
    public String getQgmaterialname() {
        return qgmaterialname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGMATERIALNAME
     *
     * @param qgmaterialname the value for PURCHASEREQUESTS.QGMATERIALNAME
     *
     * @mbggenerated
     */
    public void setQgmaterialname(String qgmaterialname) {
        this.qgmaterialname = qgmaterialname == null ? null : qgmaterialname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGMATERIALTYPE
     *
     * @return the value of PURCHASEREQUESTS.QGMATERIALTYPE
     *
     * @mbggenerated
     */
    public String getQgmaterialtype() {
        return qgmaterialtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGMATERIALTYPE
     *
     * @param qgmaterialtype the value for PURCHASEREQUESTS.QGMATERIALTYPE
     *
     * @mbggenerated
     */
    public void setQgmaterialtype(String qgmaterialtype) {
        this.qgmaterialtype = qgmaterialtype == null ? null : qgmaterialtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGUNIT
     *
     * @return the value of PURCHASEREQUESTS.QGUNIT
     *
     * @mbggenerated
     */
    public String getQgunit() {
        return qgunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGUNIT
     *
     * @param qgunit the value for PURCHASEREQUESTS.QGUNIT
     *
     * @mbggenerated
     */
    public void setQgunit(String qgunit) {
        this.qgunit = qgunit == null ? null : qgunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGNUMBER
     *
     * @return the value of PURCHASEREQUESTS.QGNUMBER
     *
     * @mbggenerated
     */
    public Short getQgnumber() {
        return qgnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGNUMBER
     *
     * @param qgnumber the value for PURCHASEREQUESTS.QGNUMBER
     *
     * @mbggenerated
     */
    public void setQgnumber(Short qgnumber) {
        this.qgnumber = qgnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGSTANDARDJJ
     *
     * @return the value of PURCHASEREQUESTS.QGSTANDARDJJ
     *
     * @mbggenerated
     */
    public BigDecimal getQgstandardjj() {
        return qgstandardjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGSTANDARDJJ
     *
     * @param qgstandardjj the value for PURCHASEREQUESTS.QGSTANDARDJJ
     *
     * @mbggenerated
     */
    public void setQgstandardjj(BigDecimal qgstandardjj) {
        this.qgstandardjj = qgstandardjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGSTANDARDJJJE
     *
     * @return the value of PURCHASEREQUESTS.QGSTANDARDJJJE
     *
     * @mbggenerated
     */
    public BigDecimal getQgstandardjjje() {
        return qgstandardjjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGSTANDARDJJJE
     *
     * @param qgstandardjjje the value for PURCHASEREQUESTS.QGSTANDARDJJJE
     *
     * @mbggenerated
     */
    public void setQgstandardjjje(BigDecimal qgstandardjjje) {
        this.qgstandardjjje = qgstandardjjje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGCURRENCY
     *
     * @return the value of PURCHASEREQUESTS.QGCURRENCY
     *
     * @mbggenerated
     */
    public String getQgcurrency() {
        return qgcurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGCURRENCY
     *
     * @param qgcurrency the value for PURCHASEREQUESTS.QGCURRENCY
     *
     * @mbggenerated
     */
    public void setQgcurrency(String qgcurrency) {
        this.qgcurrency = qgcurrency == null ? null : qgcurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGPRICE
     *
     * @return the value of PURCHASEREQUESTS.QGPRICE
     *
     * @mbggenerated
     */
    public BigDecimal getQgprice() {
        return qgprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGPRICE
     *
     * @param qgprice the value for PURCHASEREQUESTS.QGPRICE
     *
     * @mbggenerated
     */
    public void setQgprice(BigDecimal qgprice) {
        this.qgprice = qgprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGJJMONEY
     *
     * @return the value of PURCHASEREQUESTS.QGJJMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getQgjjmoney() {
        return qgjjmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGJJMONEY
     *
     * @param qgjjmoney the value for PURCHASEREQUESTS.QGJJMONEY
     *
     * @mbggenerated
     */
    public void setQgjjmoney(BigDecimal qgjjmoney) {
        this.qgjjmoney = qgjjmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGNEEDDATE
     *
     * @return the value of PURCHASEREQUESTS.QGNEEDDATE
     *
     * @mbggenerated
     */
    public Date getQgneeddate() {
        return qgneeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGNEEDDATE
     *
     * @param qgneeddate the value for PURCHASEREQUESTS.QGNEEDDATE
     *
     * @mbggenerated
     */
    public void setQgneeddate(Date qgneeddate) {
        this.qgneeddate = qgneeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGSUGGESTDATE
     *
     * @return the value of PURCHASEREQUESTS.QGSUGGESTDATE
     *
     * @mbggenerated
     */
    public Date getQgsuggestdate() {
        return qgsuggestdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGSUGGESTDATE
     *
     * @param qgsuggestdate the value for PURCHASEREQUESTS.QGSUGGESTDATE
     *
     * @mbggenerated
     */
    public void setQgsuggestdate(Date qgsuggestdate) {
        this.qgsuggestdate = qgsuggestdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGTYPEREMARK
     *
     * @return the value of PURCHASEREQUESTS.QGTYPEREMARK
     *
     * @mbggenerated
     */
    public String getQgtyperemark() {
        return qgtyperemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGTYPEREMARK
     *
     * @param qgtyperemark the value for PURCHASEREQUESTS.QGTYPEREMARK
     *
     * @mbggenerated
     */
    public void setQgtyperemark(String qgtyperemark) {
        this.qgtyperemark = qgtyperemark == null ? null : qgtyperemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGSOURCEBILL
     *
     * @return the value of PURCHASEREQUESTS.QGSOURCEBILL
     *
     * @mbggenerated
     */
    public String getQgsourcebill() {
        return qgsourcebill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGSOURCEBILL
     *
     * @param qgsourcebill the value for PURCHASEREQUESTS.QGSOURCEBILL
     *
     * @mbggenerated
     */
    public void setQgsourcebill(String qgsourcebill) {
        this.qgsourcebill = qgsourcebill == null ? null : qgsourcebill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PURCHASEREQUESTS.QGSOURCENUMBERS
     *
     * @return the value of PURCHASEREQUESTS.QGSOURCENUMBERS
     *
     * @mbggenerated
     */
    public String getQgsourcenumbers() {
        return qgsourcenumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PURCHASEREQUESTS.QGSOURCENUMBERS
     *
     * @param qgsourcenumbers the value for PURCHASEREQUESTS.QGSOURCENUMBERS
     *
     * @mbggenerated
     */
    public void setQgsourcenumbers(String qgsourcenumbers) {
        this.qgsourcenumbers = qgsourcenumbers == null ? null : qgsourcenumbers.trim();
    }
}