package com.j5erp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Putstorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.STORAGEID
     *
     * @mbggenerated
     */
    private String storageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.SUPPLIERNAME
     *
     * @mbggenerated
     */
    private String suppliername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.TIME
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.SUPPLIERADDRESS
     *
     * @mbggenerated
     */
    private String supplieraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.STATE
     *
     * @mbggenerated
     */
    private Short state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.TYPE
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.MONEYTYPE
     *
     * @mbggenerated
     */
    private Short moneytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.TAXSTATE
     *
     * @mbggenerated
     */
    private Short taxstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.RATE
     *
     * @mbggenerated
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.DELIVER
     *
     * @mbggenerated
     */
    private String deliver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.TOUCHING
     *
     * @mbggenerated
     */
    private String touching;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.SECTION
     *
     * @mbggenerated
     */
    private Short section;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.CHECKPEOPLE
     *
     * @mbggenerated
     */
    private Short checkpeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.CHECKSTATE
     *
     * @mbggenerated
     */
    private Short checkstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.COLUMN1
     *
     * @mbggenerated
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.COLUMN2
     *
     * @mbggenerated
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUTSTORAGE.COLUMN3
     *
     * @mbggenerated
     */
    private String column3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTSTORAGE
     *
     * @mbggenerated
     */
    public Putstorage(String id, String storageid, String suppliername, Date time, String supplieraddress, Short state, Short type, Short moneytype, Short taxstate, BigDecimal rate, String deliver, String touching, Short section, Short checkpeople, String remark, Short checkstate, String column1, String column2, String column3) {
        this.id = id;
        this.storageid = storageid;
        this.suppliername = suppliername;
        this.time = time;
        this.supplieraddress = supplieraddress;
        this.state = state;
        this.type = type;
        this.moneytype = moneytype;
        this.taxstate = taxstate;
        this.rate = rate;
        this.deliver = deliver;
        this.touching = touching;
        this.section = section;
        this.checkpeople = checkpeople;
        this.remark = remark;
        this.checkstate = checkstate;
        this.column1 = column1;
        this.column2 = column2;
        this.column3 = column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTSTORAGE
     *
     * @mbggenerated
     */
    public Putstorage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.ID
     *
     * @return the value of PUTSTORAGE.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.ID
     *
     * @param id the value for PUTSTORAGE.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.STORAGEID
     *
     * @return the value of PUTSTORAGE.STORAGEID
     *
     * @mbggenerated
     */
    public String getStorageid() {
        return storageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.STORAGEID
     *
     * @param storageid the value for PUTSTORAGE.STORAGEID
     *
     * @mbggenerated
     */
    public void setStorageid(String storageid) {
        this.storageid = storageid == null ? null : storageid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.SUPPLIERNAME
     *
     * @return the value of PUTSTORAGE.SUPPLIERNAME
     *
     * @mbggenerated
     */
    public String getSuppliername() {
        return suppliername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.SUPPLIERNAME
     *
     * @param suppliername the value for PUTSTORAGE.SUPPLIERNAME
     *
     * @mbggenerated
     */
    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername == null ? null : suppliername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.TIME
     *
     * @return the value of PUTSTORAGE.TIME
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.TIME
     *
     * @param time the value for PUTSTORAGE.TIME
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.SUPPLIERADDRESS
     *
     * @return the value of PUTSTORAGE.SUPPLIERADDRESS
     *
     * @mbggenerated
     */
    public String getSupplieraddress() {
        return supplieraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.SUPPLIERADDRESS
     *
     * @param supplieraddress the value for PUTSTORAGE.SUPPLIERADDRESS
     *
     * @mbggenerated
     */
    public void setSupplieraddress(String supplieraddress) {
        this.supplieraddress = supplieraddress == null ? null : supplieraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.STATE
     *
     * @return the value of PUTSTORAGE.STATE
     *
     * @mbggenerated
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.STATE
     *
     * @param state the value for PUTSTORAGE.STATE
     *
     * @mbggenerated
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.TYPE
     *
     * @return the value of PUTSTORAGE.TYPE
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.TYPE
     *
     * @param type the value for PUTSTORAGE.TYPE
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.MONEYTYPE
     *
     * @return the value of PUTSTORAGE.MONEYTYPE
     *
     * @mbggenerated
     */
    public Short getMoneytype() {
        return moneytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.MONEYTYPE
     *
     * @param moneytype the value for PUTSTORAGE.MONEYTYPE
     *
     * @mbggenerated
     */
    public void setMoneytype(Short moneytype) {
        this.moneytype = moneytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.TAXSTATE
     *
     * @return the value of PUTSTORAGE.TAXSTATE
     *
     * @mbggenerated
     */
    public Short getTaxstate() {
        return taxstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.TAXSTATE
     *
     * @param taxstate the value for PUTSTORAGE.TAXSTATE
     *
     * @mbggenerated
     */
    public void setTaxstate(Short taxstate) {
        this.taxstate = taxstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.RATE
     *
     * @return the value of PUTSTORAGE.RATE
     *
     * @mbggenerated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.RATE
     *
     * @param rate the value for PUTSTORAGE.RATE
     *
     * @mbggenerated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.DELIVER
     *
     * @return the value of PUTSTORAGE.DELIVER
     *
     * @mbggenerated
     */
    public String getDeliver() {
        return deliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.DELIVER
     *
     * @param deliver the value for PUTSTORAGE.DELIVER
     *
     * @mbggenerated
     */
    public void setDeliver(String deliver) {
        this.deliver = deliver == null ? null : deliver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.TOUCHING
     *
     * @return the value of PUTSTORAGE.TOUCHING
     *
     * @mbggenerated
     */
    public String getTouching() {
        return touching;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.TOUCHING
     *
     * @param touching the value for PUTSTORAGE.TOUCHING
     *
     * @mbggenerated
     */
    public void setTouching(String touching) {
        this.touching = touching == null ? null : touching.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.SECTION
     *
     * @return the value of PUTSTORAGE.SECTION
     *
     * @mbggenerated
     */
    public Short getSection() {
        return section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.SECTION
     *
     * @param section the value for PUTSTORAGE.SECTION
     *
     * @mbggenerated
     */
    public void setSection(Short section) {
        this.section = section;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.CHECKPEOPLE
     *
     * @return the value of PUTSTORAGE.CHECKPEOPLE
     *
     * @mbggenerated
     */
    public Short getCheckpeople() {
        return checkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.CHECKPEOPLE
     *
     * @param checkpeople the value for PUTSTORAGE.CHECKPEOPLE
     *
     * @mbggenerated
     */
    public void setCheckpeople(Short checkpeople) {
        this.checkpeople = checkpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.REMARK
     *
     * @return the value of PUTSTORAGE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.REMARK
     *
     * @param remark the value for PUTSTORAGE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.CHECKSTATE
     *
     * @return the value of PUTSTORAGE.CHECKSTATE
     *
     * @mbggenerated
     */
    public Short getCheckstate() {
        return checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.CHECKSTATE
     *
     * @param checkstate the value for PUTSTORAGE.CHECKSTATE
     *
     * @mbggenerated
     */
    public void setCheckstate(Short checkstate) {
        this.checkstate = checkstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.COLUMN1
     *
     * @return the value of PUTSTORAGE.COLUMN1
     *
     * @mbggenerated
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.COLUMN1
     *
     * @param column1 the value for PUTSTORAGE.COLUMN1
     *
     * @mbggenerated
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.COLUMN2
     *
     * @return the value of PUTSTORAGE.COLUMN2
     *
     * @mbggenerated
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.COLUMN2
     *
     * @param column2 the value for PUTSTORAGE.COLUMN2
     *
     * @mbggenerated
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUTSTORAGE.COLUMN3
     *
     * @return the value of PUTSTORAGE.COLUMN3
     *
     * @mbggenerated
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUTSTORAGE.COLUMN3
     *
     * @param column3 the value for PUTSTORAGE.COLUMN3
     *
     * @mbggenerated
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }
}