package com.j5erp.entity;

public class Repertoryassert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.REPERTORYID
     *
     * @mbggenerated
     */
    private String repertoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.REPERTORYNAME
     *
     * @mbggenerated
     */
    private String repertoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.REPERTORYCN_SHORT
     *
     * @mbggenerated
     */
    private String repertorycnShort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.LINKMAN
     *
     * @mbggenerated
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.LINKADDRESS
     *
     * @mbggenerated
     */
    private String linkaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.REPERTORYADDRESS
     *
     * @mbggenerated
     */
    private String repertoryaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPERTORYASSERT.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPERTORYASSERT
     *
     * @mbggenerated
     */
    public Repertoryassert(String repertoryid, String repertoryname, String repertorycnShort, String linkman, String phone, String linkaddress, String repertoryaddress, String remark) {
        this.repertoryid = repertoryid;
        this.repertoryname = repertoryname;
        this.repertorycnShort = repertorycnShort;
        this.linkman = linkman;
        this.phone = phone;
        this.linkaddress = linkaddress;
        this.repertoryaddress = repertoryaddress;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REPERTORYASSERT
     *
     * @mbggenerated
     */
    public Repertoryassert() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.REPERTORYID
     *
     * @return the value of REPERTORYASSERT.REPERTORYID
     *
     * @mbggenerated
     */
    public String getRepertoryid() {
        return repertoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.REPERTORYID
     *
     * @param repertoryid the value for REPERTORYASSERT.REPERTORYID
     *
     * @mbggenerated
     */
    public void setRepertoryid(String repertoryid) {
        this.repertoryid = repertoryid == null ? null : repertoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.REPERTORYNAME
     *
     * @return the value of REPERTORYASSERT.REPERTORYNAME
     *
     * @mbggenerated
     */
    public String getRepertoryname() {
        return repertoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.REPERTORYNAME
     *
     * @param repertoryname the value for REPERTORYASSERT.REPERTORYNAME
     *
     * @mbggenerated
     */
    public void setRepertoryname(String repertoryname) {
        this.repertoryname = repertoryname == null ? null : repertoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.REPERTORYCN_SHORT
     *
     * @return the value of REPERTORYASSERT.REPERTORYCN_SHORT
     *
     * @mbggenerated
     */
    public String getRepertorycnShort() {
        return repertorycnShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.REPERTORYCN_SHORT
     *
     * @param repertorycnShort the value for REPERTORYASSERT.REPERTORYCN_SHORT
     *
     * @mbggenerated
     */
    public void setRepertorycnShort(String repertorycnShort) {
        this.repertorycnShort = repertorycnShort == null ? null : repertorycnShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.LINKMAN
     *
     * @return the value of REPERTORYASSERT.LINKMAN
     *
     * @mbggenerated
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.LINKMAN
     *
     * @param linkman the value for REPERTORYASSERT.LINKMAN
     *
     * @mbggenerated
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.PHONE
     *
     * @return the value of REPERTORYASSERT.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.PHONE
     *
     * @param phone the value for REPERTORYASSERT.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.LINKADDRESS
     *
     * @return the value of REPERTORYASSERT.LINKADDRESS
     *
     * @mbggenerated
     */
    public String getLinkaddress() {
        return linkaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.LINKADDRESS
     *
     * @param linkaddress the value for REPERTORYASSERT.LINKADDRESS
     *
     * @mbggenerated
     */
    public void setLinkaddress(String linkaddress) {
        this.linkaddress = linkaddress == null ? null : linkaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.REPERTORYADDRESS
     *
     * @return the value of REPERTORYASSERT.REPERTORYADDRESS
     *
     * @mbggenerated
     */
    public String getRepertoryaddress() {
        return repertoryaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.REPERTORYADDRESS
     *
     * @param repertoryaddress the value for REPERTORYASSERT.REPERTORYADDRESS
     *
     * @mbggenerated
     */
    public void setRepertoryaddress(String repertoryaddress) {
        this.repertoryaddress = repertoryaddress == null ? null : repertoryaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPERTORYASSERT.REMARK
     *
     * @return the value of REPERTORYASSERT.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPERTORYASSERT.REMARK
     *
     * @param remark the value for REPERTORYASSERT.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}