package com.j5erp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Sellquote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.BILLID
     *
     * @mbggenerated
     */
    private String billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.BILLDATE
     *
     * @mbggenerated
     */
    private Date billdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.CLIID
     *
     * @mbggenerated
     */
    private String cliid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.CLINAME
     *
     * @mbggenerated
     */
    private String cliname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.CLIPLACEID
     *
     * @mbggenerated
     */
    private String cliplaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.CLIPLACE
     *
     * @mbggenerated
     */
    private String cliplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.PRICEWHETHERTAX
     *
     * @mbggenerated
     */
    private Short pricewhethertax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.EFFECTDATE
     *
     * @mbggenerated
     */
    private Date effectdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.BBID
     *
     * @mbggenerated
     */
    private String bbid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.BBEXCHANGE_RATE
     *
     * @mbggenerated
     */
    private BigDecimal bbexchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.MAKEEMPNAME
     *
     * @mbggenerated
     */
    private String makeempname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.AUDITINGEMPNAME
     *
     * @mbggenerated
     */
    private String auditingempname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.EMPNAME
     *
     * @mbggenerated
     */
    private String empname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.DEPID
     *
     * @mbggenerated
     */
    private String depid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.DEPNAME
     *
     * @mbggenerated
     */
    private String depname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SELLQUOTE.CHECKSTATUS
     *
     * @mbggenerated
     */
    private Short checkstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SELLQUOTE
     *
     * @mbggenerated
     */
    public Sellquote(String billid, Date billdate, String cliid, String cliname, String cliplaceid, String cliplace, Short pricewhethertax, Date effectdate, String bbid, BigDecimal bbexchangeRate, String remark, String makeempname, String auditingempname, String empname, String depid, String depname, Short checkstatus) {
        this.billid = billid;
        this.billdate = billdate;
        this.cliid = cliid;
        this.cliname = cliname;
        this.cliplaceid = cliplaceid;
        this.cliplace = cliplace;
        this.pricewhethertax = pricewhethertax;
        this.effectdate = effectdate;
        this.bbid = bbid;
        this.bbexchangeRate = bbexchangeRate;
        this.remark = remark;
        this.makeempname = makeempname;
        this.auditingempname = auditingempname;
        this.empname = empname;
        this.depid = depid;
        this.depname = depname;
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SELLQUOTE
     *
     * @mbggenerated
     */
    public Sellquote() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.BILLID
     *
     * @return the value of SELLQUOTE.BILLID
     *
     * @mbggenerated
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.BILLID
     *
     * @param billid the value for SELLQUOTE.BILLID
     *
     * @mbggenerated
     */
    public void setBillid(String billid) {
        this.billid = billid == null ? null : billid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.BILLDATE
     *
     * @return the value of SELLQUOTE.BILLDATE
     *
     * @mbggenerated
     */
    public Date getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.BILLDATE
     *
     * @param billdate the value for SELLQUOTE.BILLDATE
     *
     * @mbggenerated
     */
    public void setBilldate(Date billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.CLIID
     *
     * @return the value of SELLQUOTE.CLIID
     *
     * @mbggenerated
     */
    public String getCliid() {
        return cliid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.CLIID
     *
     * @param cliid the value for SELLQUOTE.CLIID
     *
     * @mbggenerated
     */
    public void setCliid(String cliid) {
        this.cliid = cliid == null ? null : cliid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.CLINAME
     *
     * @return the value of SELLQUOTE.CLINAME
     *
     * @mbggenerated
     */
    public String getCliname() {
        return cliname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.CLINAME
     *
     * @param cliname the value for SELLQUOTE.CLINAME
     *
     * @mbggenerated
     */
    public void setCliname(String cliname) {
        this.cliname = cliname == null ? null : cliname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.CLIPLACEID
     *
     * @return the value of SELLQUOTE.CLIPLACEID
     *
     * @mbggenerated
     */
    public String getCliplaceid() {
        return cliplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.CLIPLACEID
     *
     * @param cliplaceid the value for SELLQUOTE.CLIPLACEID
     *
     * @mbggenerated
     */
    public void setCliplaceid(String cliplaceid) {
        this.cliplaceid = cliplaceid == null ? null : cliplaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.CLIPLACE
     *
     * @return the value of SELLQUOTE.CLIPLACE
     *
     * @mbggenerated
     */
    public String getCliplace() {
        return cliplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.CLIPLACE
     *
     * @param cliplace the value for SELLQUOTE.CLIPLACE
     *
     * @mbggenerated
     */
    public void setCliplace(String cliplace) {
        this.cliplace = cliplace == null ? null : cliplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.PRICEWHETHERTAX
     *
     * @return the value of SELLQUOTE.PRICEWHETHERTAX
     *
     * @mbggenerated
     */
    public Short getPricewhethertax() {
        return pricewhethertax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.PRICEWHETHERTAX
     *
     * @param pricewhethertax the value for SELLQUOTE.PRICEWHETHERTAX
     *
     * @mbggenerated
     */
    public void setPricewhethertax(Short pricewhethertax) {
        this.pricewhethertax = pricewhethertax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.EFFECTDATE
     *
     * @return the value of SELLQUOTE.EFFECTDATE
     *
     * @mbggenerated
     */
    public Date getEffectdate() {
        return effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.EFFECTDATE
     *
     * @param effectdate the value for SELLQUOTE.EFFECTDATE
     *
     * @mbggenerated
     */
    public void setEffectdate(Date effectdate) {
        this.effectdate = effectdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.BBID
     *
     * @return the value of SELLQUOTE.BBID
     *
     * @mbggenerated
     */
    public String getBbid() {
        return bbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.BBID
     *
     * @param bbid the value for SELLQUOTE.BBID
     *
     * @mbggenerated
     */
    public void setBbid(String bbid) {
        this.bbid = bbid == null ? null : bbid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.BBEXCHANGE_RATE
     *
     * @return the value of SELLQUOTE.BBEXCHANGE_RATE
     *
     * @mbggenerated
     */
    public BigDecimal getBbexchangeRate() {
        return bbexchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.BBEXCHANGE_RATE
     *
     * @param bbexchangeRate the value for SELLQUOTE.BBEXCHANGE_RATE
     *
     * @mbggenerated
     */
    public void setBbexchangeRate(BigDecimal bbexchangeRate) {
        this.bbexchangeRate = bbexchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.REMARK
     *
     * @return the value of SELLQUOTE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.REMARK
     *
     * @param remark the value for SELLQUOTE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.MAKEEMPNAME
     *
     * @return the value of SELLQUOTE.MAKEEMPNAME
     *
     * @mbggenerated
     */
    public String getMakeempname() {
        return makeempname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.MAKEEMPNAME
     *
     * @param makeempname the value for SELLQUOTE.MAKEEMPNAME
     *
     * @mbggenerated
     */
    public void setMakeempname(String makeempname) {
        this.makeempname = makeempname == null ? null : makeempname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.AUDITINGEMPNAME
     *
     * @return the value of SELLQUOTE.AUDITINGEMPNAME
     *
     * @mbggenerated
     */
    public String getAuditingempname() {
        return auditingempname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.AUDITINGEMPNAME
     *
     * @param auditingempname the value for SELLQUOTE.AUDITINGEMPNAME
     *
     * @mbggenerated
     */
    public void setAuditingempname(String auditingempname) {
        this.auditingempname = auditingempname == null ? null : auditingempname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.EMPNAME
     *
     * @return the value of SELLQUOTE.EMPNAME
     *
     * @mbggenerated
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.EMPNAME
     *
     * @param empname the value for SELLQUOTE.EMPNAME
     *
     * @mbggenerated
     */
    public void setEmpname(String empname) {
        this.empname = empname == null ? null : empname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.DEPID
     *
     * @return the value of SELLQUOTE.DEPID
     *
     * @mbggenerated
     */
    public String getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.DEPID
     *
     * @param depid the value for SELLQUOTE.DEPID
     *
     * @mbggenerated
     */
    public void setDepid(String depid) {
        this.depid = depid == null ? null : depid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.DEPNAME
     *
     * @return the value of SELLQUOTE.DEPNAME
     *
     * @mbggenerated
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.DEPNAME
     *
     * @param depname the value for SELLQUOTE.DEPNAME
     *
     * @mbggenerated
     */
    public void setDepname(String depname) {
        this.depname = depname == null ? null : depname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SELLQUOTE.CHECKSTATUS
     *
     * @return the value of SELLQUOTE.CHECKSTATUS
     *
     * @mbggenerated
     */
    public Short getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SELLQUOTE.CHECKSTATUS
     *
     * @param checkstatus the value for SELLQUOTE.CHECKSTATUS
     *
     * @mbggenerated
     */
    public void setCheckstatus(Short checkstatus) {
        this.checkstatus = checkstatus;
    }
}