package com.j5erp.entity;

import java.math.BigDecimal;

public class Sharedetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.SID
     *
     * @mbggenerated
     */
    private BigDecimal sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.PID
     *
     * @mbggenerated
     */
    private BigDecimal pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.CLOUD
     *
     * @mbggenerated
     */
    private BigDecimal cloud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.MATERIAL
     *
     * @mbggenerated
     */
    private BigDecimal material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.SNAME
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.MODEL
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.SMONEY
     *
     * @mbggenerated
     */
    private BigDecimal smoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.NUMBERS
     *
     * @mbggenerated
     */
    private BigDecimal numbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.SPRICE
     *
     * @mbggenerated
     */
    private BigDecimal sprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.SWEIGHT
     *
     * @mbggenerated
     */
    private BigDecimal sweight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.SVOLUME
     *
     * @mbggenerated
     */
    private BigDecimal svolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.SHARES
     *
     * @mbggenerated
     */
    private BigDecimal shares;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.CHECKSTATUS
     *
     * @mbggenerated
     */
    private BigDecimal checkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.DEMO1
     *
     * @mbggenerated
     */
    private BigDecimal demo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.DEMO2
     *
     * @mbggenerated
     */
    private String demo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHAREDETAIL.DEMO3
     *
     * @mbggenerated
     */
    private BigDecimal demo3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHAREDETAIL
     *
     * @mbggenerated
     */
    public Sharedetail(BigDecimal sid, BigDecimal pid, BigDecimal cloud, BigDecimal material, String sname, String model, BigDecimal smoney, BigDecimal numbers, BigDecimal sprice, BigDecimal sweight, BigDecimal svolume, BigDecimal shares, BigDecimal checkstatus, BigDecimal demo1, String demo2, BigDecimal demo3) {
        this.sid = sid;
        this.pid = pid;
        this.cloud = cloud;
        this.material = material;
        this.sname = sname;
        this.model = model;
        this.smoney = smoney;
        this.numbers = numbers;
        this.sprice = sprice;
        this.sweight = sweight;
        this.svolume = svolume;
        this.shares = shares;
        this.checkstatus = checkstatus;
        this.demo1 = demo1;
        this.demo2 = demo2;
        this.demo3 = demo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHAREDETAIL
     *
     * @mbggenerated
     */
    public Sharedetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.SID
     *
     * @return the value of SHAREDETAIL.SID
     *
     * @mbggenerated
     */
    public BigDecimal getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.SID
     *
     * @param sid the value for SHAREDETAIL.SID
     *
     * @mbggenerated
     */
    public void setSid(BigDecimal sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.PID
     *
     * @return the value of SHAREDETAIL.PID
     *
     * @mbggenerated
     */
    public BigDecimal getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.PID
     *
     * @param pid the value for SHAREDETAIL.PID
     *
     * @mbggenerated
     */
    public void setPid(BigDecimal pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.CLOUD
     *
     * @return the value of SHAREDETAIL.CLOUD
     *
     * @mbggenerated
     */
    public BigDecimal getCloud() {
        return cloud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.CLOUD
     *
     * @param cloud the value for SHAREDETAIL.CLOUD
     *
     * @mbggenerated
     */
    public void setCloud(BigDecimal cloud) {
        this.cloud = cloud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.MATERIAL
     *
     * @return the value of SHAREDETAIL.MATERIAL
     *
     * @mbggenerated
     */
    public BigDecimal getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.MATERIAL
     *
     * @param material the value for SHAREDETAIL.MATERIAL
     *
     * @mbggenerated
     */
    public void setMaterial(BigDecimal material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.SNAME
     *
     * @return the value of SHAREDETAIL.SNAME
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.SNAME
     *
     * @param sname the value for SHAREDETAIL.SNAME
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.MODEL
     *
     * @return the value of SHAREDETAIL.MODEL
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.MODEL
     *
     * @param model the value for SHAREDETAIL.MODEL
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.SMONEY
     *
     * @return the value of SHAREDETAIL.SMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getSmoney() {
        return smoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.SMONEY
     *
     * @param smoney the value for SHAREDETAIL.SMONEY
     *
     * @mbggenerated
     */
    public void setSmoney(BigDecimal smoney) {
        this.smoney = smoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.NUMBERS
     *
     * @return the value of SHAREDETAIL.NUMBERS
     *
     * @mbggenerated
     */
    public BigDecimal getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.NUMBERS
     *
     * @param numbers the value for SHAREDETAIL.NUMBERS
     *
     * @mbggenerated
     */
    public void setNumbers(BigDecimal numbers) {
        this.numbers = numbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.SPRICE
     *
     * @return the value of SHAREDETAIL.SPRICE
     *
     * @mbggenerated
     */
    public BigDecimal getSprice() {
        return sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.SPRICE
     *
     * @param sprice the value for SHAREDETAIL.SPRICE
     *
     * @mbggenerated
     */
    public void setSprice(BigDecimal sprice) {
        this.sprice = sprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.SWEIGHT
     *
     * @return the value of SHAREDETAIL.SWEIGHT
     *
     * @mbggenerated
     */
    public BigDecimal getSweight() {
        return sweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.SWEIGHT
     *
     * @param sweight the value for SHAREDETAIL.SWEIGHT
     *
     * @mbggenerated
     */
    public void setSweight(BigDecimal sweight) {
        this.sweight = sweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.SVOLUME
     *
     * @return the value of SHAREDETAIL.SVOLUME
     *
     * @mbggenerated
     */
    public BigDecimal getSvolume() {
        return svolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.SVOLUME
     *
     * @param svolume the value for SHAREDETAIL.SVOLUME
     *
     * @mbggenerated
     */
    public void setSvolume(BigDecimal svolume) {
        this.svolume = svolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.SHARES
     *
     * @return the value of SHAREDETAIL.SHARES
     *
     * @mbggenerated
     */
    public BigDecimal getShares() {
        return shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.SHARES
     *
     * @param shares the value for SHAREDETAIL.SHARES
     *
     * @mbggenerated
     */
    public void setShares(BigDecimal shares) {
        this.shares = shares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.CHECKSTATUS
     *
     * @return the value of SHAREDETAIL.CHECKSTATUS
     *
     * @mbggenerated
     */
    public BigDecimal getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.CHECKSTATUS
     *
     * @param checkstatus the value for SHAREDETAIL.CHECKSTATUS
     *
     * @mbggenerated
     */
    public void setCheckstatus(BigDecimal checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.DEMO1
     *
     * @return the value of SHAREDETAIL.DEMO1
     *
     * @mbggenerated
     */
    public BigDecimal getDemo1() {
        return demo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.DEMO1
     *
     * @param demo1 the value for SHAREDETAIL.DEMO1
     *
     * @mbggenerated
     */
    public void setDemo1(BigDecimal demo1) {
        this.demo1 = demo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.DEMO2
     *
     * @return the value of SHAREDETAIL.DEMO2
     *
     * @mbggenerated
     */
    public String getDemo2() {
        return demo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.DEMO2
     *
     * @param demo2 the value for SHAREDETAIL.DEMO2
     *
     * @mbggenerated
     */
    public void setDemo2(String demo2) {
        this.demo2 = demo2 == null ? null : demo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHAREDETAIL.DEMO3
     *
     * @return the value of SHAREDETAIL.DEMO3
     *
     * @mbggenerated
     */
    public BigDecimal getDemo3() {
        return demo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHAREDETAIL.DEMO3
     *
     * @param demo3 the value for SHAREDETAIL.DEMO3
     *
     * @mbggenerated
     */
    public void setDemo3(BigDecimal demo3) {
        this.demo3 = demo3;
    }
}