package com.j5erp.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TCgthmaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.T_CGGTHID
     *
     * @mbggenerated
     */
    private String tCggthid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.T_CGTHDATE
     *
     * @mbggenerated
     */
    private Date tCgthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.T_GYSID
     *
     * @mbggenerated
     */
    private String tGysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.WAREHOUSEID
     *
     * @mbggenerated
     */
    private String warehouseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.SALESMAN
     *
     * @mbggenerated
     */
    private String salesman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.DEPARTMENTID
     *
     * @mbggenerated
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.CURRENCYID
     *
     * @mbggenerated
     */
    private String currencyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.TOUCHPERSON
     *
     * @mbggenerated
     */
    private String touchperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.CHECKPERSON
     *
     * @mbggenerated
     */
    private String checkperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.BOOLPUT
     *
     * @mbggenerated
     */
    private String boolput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.BOOLTAX
     *
     * @mbggenerated
     */
    private String booltax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.COLUMNONE
     *
     * @mbggenerated
     */
    private String columnone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.COLUMNTWO
     *
     * @mbggenerated
     */
    private String columntwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.PERMITTER
     *
     * @mbggenerated
     */
    private String permitter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CGTHMASTER.EXCHRATE
     *
     * @mbggenerated
     */
    private BigDecimal exchrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHMASTER
     *
     * @mbggenerated
     */
    public TCgthmaster(String tCggthid, Date tCgthdate, String tGysid, String warehouseid, String salesman, String departmentid, String currencyid, String touchperson, String checkperson, String boolput, String booltax, String columnone, String columntwo, String permitter, BigDecimal exchrate) {
        this.tCggthid = tCggthid;
        this.tCgthdate = tCgthdate;
        this.tGysid = tGysid;
        this.warehouseid = warehouseid;
        this.salesman = salesman;
        this.departmentid = departmentid;
        this.currencyid = currencyid;
        this.touchperson = touchperson;
        this.checkperson = checkperson;
        this.boolput = boolput;
        this.booltax = booltax;
        this.columnone = columnone;
        this.columntwo = columntwo;
        this.permitter = permitter;
        this.exchrate = exchrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHMASTER
     *
     * @mbggenerated
     */
    public TCgthmaster() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.T_CGGTHID
     *
     * @return the value of T_CGTHMASTER.T_CGGTHID
     *
     * @mbggenerated
     */
    public String gettCggthid() {
        return tCggthid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.T_CGGTHID
     *
     * @param tCggthid the value for T_CGTHMASTER.T_CGGTHID
     *
     * @mbggenerated
     */
    public void settCggthid(String tCggthid) {
        this.tCggthid = tCggthid == null ? null : tCggthid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.T_CGTHDATE
     *
     * @return the value of T_CGTHMASTER.T_CGTHDATE
     *
     * @mbggenerated
     */
    public Date gettCgthdate() {
        return tCgthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.T_CGTHDATE
     *
     * @param tCgthdate the value for T_CGTHMASTER.T_CGTHDATE
     *
     * @mbggenerated
     */
    public void settCgthdate(Date tCgthdate) {
        this.tCgthdate = tCgthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.T_GYSID
     *
     * @return the value of T_CGTHMASTER.T_GYSID
     *
     * @mbggenerated
     */
    public String gettGysid() {
        return tGysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.T_GYSID
     *
     * @param tGysid the value for T_CGTHMASTER.T_GYSID
     *
     * @mbggenerated
     */
    public void settGysid(String tGysid) {
        this.tGysid = tGysid == null ? null : tGysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.WAREHOUSEID
     *
     * @return the value of T_CGTHMASTER.WAREHOUSEID
     *
     * @mbggenerated
     */
    public String getWarehouseid() {
        return warehouseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.WAREHOUSEID
     *
     * @param warehouseid the value for T_CGTHMASTER.WAREHOUSEID
     *
     * @mbggenerated
     */
    public void setWarehouseid(String warehouseid) {
        this.warehouseid = warehouseid == null ? null : warehouseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.SALESMAN
     *
     * @return the value of T_CGTHMASTER.SALESMAN
     *
     * @mbggenerated
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.SALESMAN
     *
     * @param salesman the value for T_CGTHMASTER.SALESMAN
     *
     * @mbggenerated
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.DEPARTMENTID
     *
     * @return the value of T_CGTHMASTER.DEPARTMENTID
     *
     * @mbggenerated
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.DEPARTMENTID
     *
     * @param departmentid the value for T_CGTHMASTER.DEPARTMENTID
     *
     * @mbggenerated
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.CURRENCYID
     *
     * @return the value of T_CGTHMASTER.CURRENCYID
     *
     * @mbggenerated
     */
    public String getCurrencyid() {
        return currencyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.CURRENCYID
     *
     * @param currencyid the value for T_CGTHMASTER.CURRENCYID
     *
     * @mbggenerated
     */
    public void setCurrencyid(String currencyid) {
        this.currencyid = currencyid == null ? null : currencyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.TOUCHPERSON
     *
     * @return the value of T_CGTHMASTER.TOUCHPERSON
     *
     * @mbggenerated
     */
    public String getTouchperson() {
        return touchperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.TOUCHPERSON
     *
     * @param touchperson the value for T_CGTHMASTER.TOUCHPERSON
     *
     * @mbggenerated
     */
    public void setTouchperson(String touchperson) {
        this.touchperson = touchperson == null ? null : touchperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.CHECKPERSON
     *
     * @return the value of T_CGTHMASTER.CHECKPERSON
     *
     * @mbggenerated
     */
    public String getCheckperson() {
        return checkperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.CHECKPERSON
     *
     * @param checkperson the value for T_CGTHMASTER.CHECKPERSON
     *
     * @mbggenerated
     */
    public void setCheckperson(String checkperson) {
        this.checkperson = checkperson == null ? null : checkperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.BOOLPUT
     *
     * @return the value of T_CGTHMASTER.BOOLPUT
     *
     * @mbggenerated
     */
    public String getBoolput() {
        return boolput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.BOOLPUT
     *
     * @param boolput the value for T_CGTHMASTER.BOOLPUT
     *
     * @mbggenerated
     */
    public void setBoolput(String boolput) {
        this.boolput = boolput == null ? null : boolput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.BOOLTAX
     *
     * @return the value of T_CGTHMASTER.BOOLTAX
     *
     * @mbggenerated
     */
    public String getBooltax() {
        return booltax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.BOOLTAX
     *
     * @param booltax the value for T_CGTHMASTER.BOOLTAX
     *
     * @mbggenerated
     */
    public void setBooltax(String booltax) {
        this.booltax = booltax == null ? null : booltax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.COLUMNONE
     *
     * @return the value of T_CGTHMASTER.COLUMNONE
     *
     * @mbggenerated
     */
    public String getColumnone() {
        return columnone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.COLUMNONE
     *
     * @param columnone the value for T_CGTHMASTER.COLUMNONE
     *
     * @mbggenerated
     */
    public void setColumnone(String columnone) {
        this.columnone = columnone == null ? null : columnone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.COLUMNTWO
     *
     * @return the value of T_CGTHMASTER.COLUMNTWO
     *
     * @mbggenerated
     */
    public String getColumntwo() {
        return columntwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.COLUMNTWO
     *
     * @param columntwo the value for T_CGTHMASTER.COLUMNTWO
     *
     * @mbggenerated
     */
    public void setColumntwo(String columntwo) {
        this.columntwo = columntwo == null ? null : columntwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.PERMITTER
     *
     * @return the value of T_CGTHMASTER.PERMITTER
     *
     * @mbggenerated
     */
    public String getPermitter() {
        return permitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.PERMITTER
     *
     * @param permitter the value for T_CGTHMASTER.PERMITTER
     *
     * @mbggenerated
     */
    public void setPermitter(String permitter) {
        this.permitter = permitter == null ? null : permitter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CGTHMASTER.EXCHRATE
     *
     * @return the value of T_CGTHMASTER.EXCHRATE
     *
     * @mbggenerated
     */
    public BigDecimal getExchrate() {
        return exchrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CGTHMASTER.EXCHRATE
     *
     * @param exchrate the value for T_CGTHMASTER.EXCHRATE
     *
     * @mbggenerated
     */
    public void setExchrate(BigDecimal exchrate) {
        this.exchrate = exchrate;
    }
}