package com.j5erp.entity;

import java.math.BigDecimal;

public class Tiaojiadanxiangbiao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.SERNO
     *
     * @mbggenerated
     */
    private Short serno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.BILLNO
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.PRODID
     *
     * @mbggenerated
     */
    private String prodid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.PRODNAME
     *
     * @mbggenerated
     */
    private String prodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.PRODSIZE
     *
     * @mbggenerated
     */
    private String prodsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.UNIT
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.CURQTY
     *
     * @mbggenerated
     */
    private Long curqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.LCOSTAVG
     *
     * @mbggenerated
     */
    private BigDecimal lcostavg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.PRICE
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANXIANGBIAO.ITEMREMARK
     *
     * @mbggenerated
     */
    private String itemremark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANXIANGBIAO
     *
     * @mbggenerated
     */
    public Tiaojiadanxiangbiao(Short serno, String billno, String prodid, String prodname, String prodsize, String unit, Long curqty, BigDecimal lcostavg, BigDecimal price, BigDecimal amount, String itemremark) {
        this.serno = serno;
        this.billno = billno;
        this.prodid = prodid;
        this.prodname = prodname;
        this.prodsize = prodsize;
        this.unit = unit;
        this.curqty = curqty;
        this.lcostavg = lcostavg;
        this.price = price;
        this.amount = amount;
        this.itemremark = itemremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANXIANGBIAO
     *
     * @mbggenerated
     */
    public Tiaojiadanxiangbiao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.SERNO
     *
     * @return the value of TIAOJIADANXIANGBIAO.SERNO
     *
     * @mbggenerated
     */
    public Short getSerno() {
        return serno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.SERNO
     *
     * @param serno the value for TIAOJIADANXIANGBIAO.SERNO
     *
     * @mbggenerated
     */
    public void setSerno(Short serno) {
        this.serno = serno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.BILLNO
     *
     * @return the value of TIAOJIADANXIANGBIAO.BILLNO
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.BILLNO
     *
     * @param billno the value for TIAOJIADANXIANGBIAO.BILLNO
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.PRODID
     *
     * @return the value of TIAOJIADANXIANGBIAO.PRODID
     *
     * @mbggenerated
     */
    public String getProdid() {
        return prodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.PRODID
     *
     * @param prodid the value for TIAOJIADANXIANGBIAO.PRODID
     *
     * @mbggenerated
     */
    public void setProdid(String prodid) {
        this.prodid = prodid == null ? null : prodid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.PRODNAME
     *
     * @return the value of TIAOJIADANXIANGBIAO.PRODNAME
     *
     * @mbggenerated
     */
    public String getProdname() {
        return prodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.PRODNAME
     *
     * @param prodname the value for TIAOJIADANXIANGBIAO.PRODNAME
     *
     * @mbggenerated
     */
    public void setProdname(String prodname) {
        this.prodname = prodname == null ? null : prodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.PRODSIZE
     *
     * @return the value of TIAOJIADANXIANGBIAO.PRODSIZE
     *
     * @mbggenerated
     */
    public String getProdsize() {
        return prodsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.PRODSIZE
     *
     * @param prodsize the value for TIAOJIADANXIANGBIAO.PRODSIZE
     *
     * @mbggenerated
     */
    public void setProdsize(String prodsize) {
        this.prodsize = prodsize == null ? null : prodsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.UNIT
     *
     * @return the value of TIAOJIADANXIANGBIAO.UNIT
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.UNIT
     *
     * @param unit the value for TIAOJIADANXIANGBIAO.UNIT
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.CURQTY
     *
     * @return the value of TIAOJIADANXIANGBIAO.CURQTY
     *
     * @mbggenerated
     */
    public Long getCurqty() {
        return curqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.CURQTY
     *
     * @param curqty the value for TIAOJIADANXIANGBIAO.CURQTY
     *
     * @mbggenerated
     */
    public void setCurqty(Long curqty) {
        this.curqty = curqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.LCOSTAVG
     *
     * @return the value of TIAOJIADANXIANGBIAO.LCOSTAVG
     *
     * @mbggenerated
     */
    public BigDecimal getLcostavg() {
        return lcostavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.LCOSTAVG
     *
     * @param lcostavg the value for TIAOJIADANXIANGBIAO.LCOSTAVG
     *
     * @mbggenerated
     */
    public void setLcostavg(BigDecimal lcostavg) {
        this.lcostavg = lcostavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.PRICE
     *
     * @return the value of TIAOJIADANXIANGBIAO.PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.PRICE
     *
     * @param price the value for TIAOJIADANXIANGBIAO.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.AMOUNT
     *
     * @return the value of TIAOJIADANXIANGBIAO.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.AMOUNT
     *
     * @param amount the value for TIAOJIADANXIANGBIAO.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANXIANGBIAO.ITEMREMARK
     *
     * @return the value of TIAOJIADANXIANGBIAO.ITEMREMARK
     *
     * @mbggenerated
     */
    public String getItemremark() {
        return itemremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANXIANGBIAO.ITEMREMARK
     *
     * @param itemremark the value for TIAOJIADANXIANGBIAO.ITEMREMARK
     *
     * @mbggenerated
     */
    public void setItemremark(String itemremark) {
        this.itemremark = itemremark == null ? null : itemremark.trim();
    }
}