package com.j5erp.entity;

import java.util.Date;

public class Tiaojiadanzhubiao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANZHUBIAO.BILLNO
     *
     * @mbggenerated
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANZHUBIAO.ADJUSTDATE
     *
     * @mbggenerated
     */
    private Date adjustdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANZHUBIAO.MAKER
     *
     * @mbggenerated
     */
    private String maker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANZHUBIAO.PERMITTER
     *
     * @mbggenerated
     */
    private String permitter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANZHUBIAO.AUDITSTATUS
     *
     * @mbggenerated
     */
    private Short auditstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOJIADANZHUBIAO.WHMEMO
     *
     * @mbggenerated
     */
    private String whmemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANZHUBIAO
     *
     * @mbggenerated
     */
    public Tiaojiadanzhubiao(String billno, Date adjustdate, String maker, String permitter, Short auditstatus, String whmemo) {
        this.billno = billno;
        this.adjustdate = adjustdate;
        this.maker = maker;
        this.permitter = permitter;
        this.auditstatus = auditstatus;
        this.whmemo = whmemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANZHUBIAO
     *
     * @mbggenerated
     */
    public Tiaojiadanzhubiao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANZHUBIAO.BILLNO
     *
     * @return the value of TIAOJIADANZHUBIAO.BILLNO
     *
     * @mbggenerated
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANZHUBIAO.BILLNO
     *
     * @param billno the value for TIAOJIADANZHUBIAO.BILLNO
     *
     * @mbggenerated
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANZHUBIAO.ADJUSTDATE
     *
     * @return the value of TIAOJIADANZHUBIAO.ADJUSTDATE
     *
     * @mbggenerated
     */
    public Date getAdjustdate() {
        return adjustdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANZHUBIAO.ADJUSTDATE
     *
     * @param adjustdate the value for TIAOJIADANZHUBIAO.ADJUSTDATE
     *
     * @mbggenerated
     */
    public void setAdjustdate(Date adjustdate) {
        this.adjustdate = adjustdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANZHUBIAO.MAKER
     *
     * @return the value of TIAOJIADANZHUBIAO.MAKER
     *
     * @mbggenerated
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANZHUBIAO.MAKER
     *
     * @param maker the value for TIAOJIADANZHUBIAO.MAKER
     *
     * @mbggenerated
     */
    public void setMaker(String maker) {
        this.maker = maker == null ? null : maker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANZHUBIAO.PERMITTER
     *
     * @return the value of TIAOJIADANZHUBIAO.PERMITTER
     *
     * @mbggenerated
     */
    public String getPermitter() {
        return permitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANZHUBIAO.PERMITTER
     *
     * @param permitter the value for TIAOJIADANZHUBIAO.PERMITTER
     *
     * @mbggenerated
     */
    public void setPermitter(String permitter) {
        this.permitter = permitter == null ? null : permitter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANZHUBIAO.AUDITSTATUS
     *
     * @return the value of TIAOJIADANZHUBIAO.AUDITSTATUS
     *
     * @mbggenerated
     */
    public Short getAuditstatus() {
        return auditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANZHUBIAO.AUDITSTATUS
     *
     * @param auditstatus the value for TIAOJIADANZHUBIAO.AUDITSTATUS
     *
     * @mbggenerated
     */
    public void setAuditstatus(Short auditstatus) {
        this.auditstatus = auditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOJIADANZHUBIAO.WHMEMO
     *
     * @return the value of TIAOJIADANZHUBIAO.WHMEMO
     *
     * @mbggenerated
     */
    public String getWhmemo() {
        return whmemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOJIADANZHUBIAO.WHMEMO
     *
     * @param whmemo the value for TIAOJIADANZHUBIAO.WHMEMO
     *
     * @mbggenerated
     */
    public void setWhmemo(String whmemo) {
        this.whmemo = whmemo == null ? null : whmemo.trim();
    }
}