package com.j5erp.entity;

public class Tiaozhengfangshileixingbiao {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOZHENGFANGSHILEIXINGBIAO.LID
     *
     * @mbggenerated
     */
    private Short lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIAOZHENGFANGSHILEIXINGBIAO.BADIUSTSTYLE
     *
     * @mbggenerated
     */
    private String badiuststyle;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOZHENGFANGSHILEIXINGBIAO
     *
     * @mbggenerated
     */
    public Tiaozhengfangshileixingbiao(Short lid, String badiuststyle) {
        this.lid = lid;
        this.badiuststyle = badiuststyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOZHENGFANGSHILEIXINGBIAO
     *
     * @mbggenerated
     */
    public Tiaozhengfangshileixingbiao() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOZHENGFANGSHILEIXINGBIAO.LID
     *
     * @return the value of TIAOZHENGFANGSHILEIXINGBIAO.LID
     *
     * @mbggenerated
     */
    public Short getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOZHENGFANGSHILEIXINGBIAO.LID
     *
     * @param lid the value for TIAOZHENGFANGSHILEIXINGBIAO.LID
     *
     * @mbggenerated
     */
    public void setLid(Short lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIAOZHENGFANGSHILEIXINGBIAO.BADIUSTSTYLE
     *
     * @return the value of TIAOZHENGFANGSHILEIXINGBIAO.BADIUSTSTYLE
     *
     * @mbggenerated
     */
    public String getBadiuststyle() {
        return badiuststyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIAOZHENGFANGSHILEIXINGBIAO.BADIUSTSTYLE
     *
     * @param badiuststyle the value for TIAOZHENGFANGSHILEIXINGBIAO.BADIUSTSTYLE
     *
     * @mbggenerated
     */
    public void setBadiuststyle(String badiuststyle) {
        this.badiuststyle = badiuststyle == null ? null : badiuststyle.trim();
    }
}