package com.j5erp.entity;

import java.math.BigDecimal;

public class TSuppliermaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.SUPPLIERID
     *
     * @mbggenerated
     */
    private String supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.SUPTYPEID
     *
     * @mbggenerated
     */
    private String suptypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.ADDRESSNAME
     *
     * @mbggenerated
     */
    private String addressname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.CURRENCYID
     *
     * @mbggenerated
     */
    private String currencyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.PURCHASEMAN
     *
     * @mbggenerated
     */
    private String purchaseman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.SURPLUSMONEY
     *
     * @mbggenerated
     */
    private BigDecimal surplusmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.PAYTERM
     *
     * @mbggenerated
     */
    private String payterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.CREDITRAT
     *
     * @mbggenerated
     */
    private String creditrat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.STARTADVRECV
     *
     * @mbggenerated
     */
    private BigDecimal startadvrecv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.STARTRECEIVABLE
     *
     * @mbggenerated
     */
    private BigDecimal startreceivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.CURADVRECV
     *
     * @mbggenerated
     */
    private BigDecimal curadvrecv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.CURRECEIVABLE
     *
     * @mbggenerated
     */
    private BigDecimal curreceivable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.PRICEOFTAX
     *
     * @mbggenerated
     */
    private String priceoftax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.AMOUNTQUOTA
     *
     * @mbggenerated
     */
    private BigDecimal amountquota;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.COLUMNONE
     *
     * @mbggenerated
     */
    private String columnone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SUPPLIERMASTER.COLUMNTWO
     *
     * @mbggenerated
     */
    private String columntwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUPPLIERMASTER
     *
     * @mbggenerated
     */
    public TSuppliermaster(String supplierid, String suptypeid, String addressname, String currencyid, String purchaseman, BigDecimal surplusmoney, String payterm, String creditrat, BigDecimal startadvrecv, BigDecimal startreceivable, BigDecimal curadvrecv, BigDecimal curreceivable, String priceoftax, BigDecimal amountquota, String columnone, String columntwo) {
        this.supplierid = supplierid;
        this.suptypeid = suptypeid;
        this.addressname = addressname;
        this.currencyid = currencyid;
        this.purchaseman = purchaseman;
        this.surplusmoney = surplusmoney;
        this.payterm = payterm;
        this.creditrat = creditrat;
        this.startadvrecv = startadvrecv;
        this.startreceivable = startreceivable;
        this.curadvrecv = curadvrecv;
        this.curreceivable = curreceivable;
        this.priceoftax = priceoftax;
        this.amountquota = amountquota;
        this.columnone = columnone;
        this.columntwo = columntwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUPPLIERMASTER
     *
     * @mbggenerated
     */
    public TSuppliermaster() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.SUPPLIERID
     *
     * @return the value of T_SUPPLIERMASTER.SUPPLIERID
     *
     * @mbggenerated
     */
    public String getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.SUPPLIERID
     *
     * @param supplierid the value for T_SUPPLIERMASTER.SUPPLIERID
     *
     * @mbggenerated
     */
    public void setSupplierid(String supplierid) {
        this.supplierid = supplierid == null ? null : supplierid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.SUPTYPEID
     *
     * @return the value of T_SUPPLIERMASTER.SUPTYPEID
     *
     * @mbggenerated
     */
    public String getSuptypeid() {
        return suptypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.SUPTYPEID
     *
     * @param suptypeid the value for T_SUPPLIERMASTER.SUPTYPEID
     *
     * @mbggenerated
     */
    public void setSuptypeid(String suptypeid) {
        this.suptypeid = suptypeid == null ? null : suptypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.ADDRESSNAME
     *
     * @return the value of T_SUPPLIERMASTER.ADDRESSNAME
     *
     * @mbggenerated
     */
    public String getAddressname() {
        return addressname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.ADDRESSNAME
     *
     * @param addressname the value for T_SUPPLIERMASTER.ADDRESSNAME
     *
     * @mbggenerated
     */
    public void setAddressname(String addressname) {
        this.addressname = addressname == null ? null : addressname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.CURRENCYID
     *
     * @return the value of T_SUPPLIERMASTER.CURRENCYID
     *
     * @mbggenerated
     */
    public String getCurrencyid() {
        return currencyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.CURRENCYID
     *
     * @param currencyid the value for T_SUPPLIERMASTER.CURRENCYID
     *
     * @mbggenerated
     */
    public void setCurrencyid(String currencyid) {
        this.currencyid = currencyid == null ? null : currencyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.PURCHASEMAN
     *
     * @return the value of T_SUPPLIERMASTER.PURCHASEMAN
     *
     * @mbggenerated
     */
    public String getPurchaseman() {
        return purchaseman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.PURCHASEMAN
     *
     * @param purchaseman the value for T_SUPPLIERMASTER.PURCHASEMAN
     *
     * @mbggenerated
     */
    public void setPurchaseman(String purchaseman) {
        this.purchaseman = purchaseman == null ? null : purchaseman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.SURPLUSMONEY
     *
     * @return the value of T_SUPPLIERMASTER.SURPLUSMONEY
     *
     * @mbggenerated
     */
    public BigDecimal getSurplusmoney() {
        return surplusmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.SURPLUSMONEY
     *
     * @param surplusmoney the value for T_SUPPLIERMASTER.SURPLUSMONEY
     *
     * @mbggenerated
     */
    public void setSurplusmoney(BigDecimal surplusmoney) {
        this.surplusmoney = surplusmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.PAYTERM
     *
     * @return the value of T_SUPPLIERMASTER.PAYTERM
     *
     * @mbggenerated
     */
    public String getPayterm() {
        return payterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.PAYTERM
     *
     * @param payterm the value for T_SUPPLIERMASTER.PAYTERM
     *
     * @mbggenerated
     */
    public void setPayterm(String payterm) {
        this.payterm = payterm == null ? null : payterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.CREDITRAT
     *
     * @return the value of T_SUPPLIERMASTER.CREDITRAT
     *
     * @mbggenerated
     */
    public String getCreditrat() {
        return creditrat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.CREDITRAT
     *
     * @param creditrat the value for T_SUPPLIERMASTER.CREDITRAT
     *
     * @mbggenerated
     */
    public void setCreditrat(String creditrat) {
        this.creditrat = creditrat == null ? null : creditrat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.STARTADVRECV
     *
     * @return the value of T_SUPPLIERMASTER.STARTADVRECV
     *
     * @mbggenerated
     */
    public BigDecimal getStartadvrecv() {
        return startadvrecv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.STARTADVRECV
     *
     * @param startadvrecv the value for T_SUPPLIERMASTER.STARTADVRECV
     *
     * @mbggenerated
     */
    public void setStartadvrecv(BigDecimal startadvrecv) {
        this.startadvrecv = startadvrecv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.STARTRECEIVABLE
     *
     * @return the value of T_SUPPLIERMASTER.STARTRECEIVABLE
     *
     * @mbggenerated
     */
    public BigDecimal getStartreceivable() {
        return startreceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.STARTRECEIVABLE
     *
     * @param startreceivable the value for T_SUPPLIERMASTER.STARTRECEIVABLE
     *
     * @mbggenerated
     */
    public void setStartreceivable(BigDecimal startreceivable) {
        this.startreceivable = startreceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.CURADVRECV
     *
     * @return the value of T_SUPPLIERMASTER.CURADVRECV
     *
     * @mbggenerated
     */
    public BigDecimal getCuradvrecv() {
        return curadvrecv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.CURADVRECV
     *
     * @param curadvrecv the value for T_SUPPLIERMASTER.CURADVRECV
     *
     * @mbggenerated
     */
    public void setCuradvrecv(BigDecimal curadvrecv) {
        this.curadvrecv = curadvrecv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.CURRECEIVABLE
     *
     * @return the value of T_SUPPLIERMASTER.CURRECEIVABLE
     *
     * @mbggenerated
     */
    public BigDecimal getCurreceivable() {
        return curreceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.CURRECEIVABLE
     *
     * @param curreceivable the value for T_SUPPLIERMASTER.CURRECEIVABLE
     *
     * @mbggenerated
     */
    public void setCurreceivable(BigDecimal curreceivable) {
        this.curreceivable = curreceivable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.PRICEOFTAX
     *
     * @return the value of T_SUPPLIERMASTER.PRICEOFTAX
     *
     * @mbggenerated
     */
    public String getPriceoftax() {
        return priceoftax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.PRICEOFTAX
     *
     * @param priceoftax the value for T_SUPPLIERMASTER.PRICEOFTAX
     *
     * @mbggenerated
     */
    public void setPriceoftax(String priceoftax) {
        this.priceoftax = priceoftax == null ? null : priceoftax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.AMOUNTQUOTA
     *
     * @return the value of T_SUPPLIERMASTER.AMOUNTQUOTA
     *
     * @mbggenerated
     */
    public BigDecimal getAmountquota() {
        return amountquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.AMOUNTQUOTA
     *
     * @param amountquota the value for T_SUPPLIERMASTER.AMOUNTQUOTA
     *
     * @mbggenerated
     */
    public void setAmountquota(BigDecimal amountquota) {
        this.amountquota = amountquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.COLUMNONE
     *
     * @return the value of T_SUPPLIERMASTER.COLUMNONE
     *
     * @mbggenerated
     */
    public String getColumnone() {
        return columnone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.COLUMNONE
     *
     * @param columnone the value for T_SUPPLIERMASTER.COLUMNONE
     *
     * @mbggenerated
     */
    public void setColumnone(String columnone) {
        this.columnone = columnone == null ? null : columnone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SUPPLIERMASTER.COLUMNTWO
     *
     * @return the value of T_SUPPLIERMASTER.COLUMNTWO
     *
     * @mbggenerated
     */
    public String getColumntwo() {
        return columntwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SUPPLIERMASTER.COLUMNTWO
     *
     * @param columntwo the value for T_SUPPLIERMASTER.COLUMNTWO
     *
     * @mbggenerated
     */
    public void setColumntwo(String columntwo) {
        this.columntwo = columntwo == null ? null : columntwo.trim();
    }
}