package com.j5erp.mapper;

import com.j5erp.entity.BalanceDetail;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface BalanceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_DETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from BALANCE_DETAIL",
        "where BDID = #{bdid,jdbcType=VARCHAR}",
          "and BDLINE = #{bdline,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("bdid") String bdid, @Param("bdline") Long bdline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_DETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into BALANCE_DETAIL (BDID, BDLINE, ",
        "BDSINGLE, BDSOURCE, ",
        "BDPRIMARYMONEY, BDDISCOUNTSMONEY, ",
        "BDCHARGEMONEY, TESTA, ",
        "TESTB)",
        "values (#{bdid,jdbcType=VARCHAR}, #{bdline,jdbcType=DECIMAL}, ",
        "#{bdsingle,jdbcType=VARCHAR}, #{bdsource,jdbcType=VARCHAR}, ",
        "#{bdprimarymoney,jdbcType=DECIMAL}, #{bddiscountsmoney,jdbcType=DECIMAL}, ",
        "#{bdchargemoney,jdbcType=DECIMAL}, #{testa,jdbcType=VARCHAR}, ",
        "#{testb,jdbcType=VARCHAR})"
    })
    int insert(BalanceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_DETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BDID, BDLINE, BDSINGLE, BDSOURCE, BDPRIMARYMONEY, BDDISCOUNTSMONEY, BDCHARGEMONEY, ",
        "TESTA, TESTB",
        "from BALANCE_DETAIL",
        "where BDID = #{bdid,jdbcType=VARCHAR}",
          "and BDLINE = #{bdline,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="BDID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BDLINE", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BDSINGLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BDSOURCE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BDPRIMARYMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BDDISCOUNTSMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BDCHARGEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TESTA", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TESTB", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    BalanceDetail selectByPrimaryKey(@Param("bdid") String bdid, @Param("bdline") Long bdline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_DETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BDID, BDLINE, BDSINGLE, BDSOURCE, BDPRIMARYMONEY, BDDISCOUNTSMONEY, BDCHARGEMONEY, ",
        "TESTA, TESTB",
        "from BALANCE_DETAIL"
    })
    @ConstructorArgs({
        @Arg(column="BDID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BDLINE", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BDSINGLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BDSOURCE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BDPRIMARYMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BDDISCOUNTSMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BDCHARGEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TESTA", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TESTB", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<BalanceDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_DETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update BALANCE_DETAIL",
        "set BDSINGLE = #{bdsingle,jdbcType=VARCHAR},",
          "BDSOURCE = #{bdsource,jdbcType=VARCHAR},",
          "BDPRIMARYMONEY = #{bdprimarymoney,jdbcType=DECIMAL},",
          "BDDISCOUNTSMONEY = #{bddiscountsmoney,jdbcType=DECIMAL},",
          "BDCHARGEMONEY = #{bdchargemoney,jdbcType=DECIMAL},",
          "TESTA = #{testa,jdbcType=VARCHAR},",
          "TESTB = #{testb,jdbcType=VARCHAR}",
        "where BDID = #{bdid,jdbcType=VARCHAR}",
          "and BDLINE = #{bdline,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(BalanceDetail record);
}