package com.j5erp.mapper;

import com.j5erp.entity.BalanceHost;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface BalanceHostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_HOST
     *
     * @mbggenerated
     */
    @Delete({
        "delete from BALANCE_HOST",
        "where BHID = #{bhid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String bhid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_HOST
     *
     * @mbggenerated
     */
    @Insert({
        "insert into BALANCE_HOST (BHID, BHDATE, ",
        "SUPPLIERSID, CURRENCYID, ",
        "BHCLEARINGONE, BHCLEARINGTOW, ",
        "BHCLEARINGTHREE, BHEXCHANGERATE, ",
        "BHDISCOUNTRATE, BHDEPT, ",
        "BHREMARK, BHMAKINGNAME, ",
        "BHVERIFIER, BHREVIEWDATA, ",
        "BHREVIEWDATE, TESTA, ",
        "TESTB)",
        "values (#{bhid,jdbcType=VARCHAR}, #{bhdate,jdbcType=TIMESTAMP}, ",
        "#{suppliersid,jdbcType=VARCHAR}, #{currencyid,jdbcType=VARCHAR}, ",
        "#{bhclearingone,jdbcType=DECIMAL}, #{bhclearingtow,jdbcType=DECIMAL}, ",
        "#{bhclearingthree,jdbcType=DECIMAL}, #{bhexchangerate,jdbcType=DECIMAL}, ",
        "#{bhdiscountrate,jdbcType=DECIMAL}, #{bhdept,jdbcType=VARCHAR}, ",
        "#{bhremark,jdbcType=VARCHAR}, #{bhmakingname,jdbcType=VARCHAR}, ",
        "#{bhverifier,jdbcType=VARCHAR}, #{bhreviewdata,jdbcType=CHAR}, ",
        "#{bhreviewdate,jdbcType=TIMESTAMP}, #{testa,jdbcType=VARCHAR}, ",
        "#{testb,jdbcType=VARCHAR})"
    })
    int insert(BalanceHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_HOST
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BHID, BHDATE, SUPPLIERSID, CURRENCYID, BHCLEARINGONE, BHCLEARINGTOW, BHCLEARINGTHREE, ",
        "BHEXCHANGERATE, BHDISCOUNTRATE, BHDEPT, BHREMARK, BHMAKINGNAME, BHVERIFIER, ",
        "BHREVIEWDATA, BHREVIEWDATE, TESTA, TESTB",
        "from BALANCE_HOST",
        "where BHID = #{bhid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="BHID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BHDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="SUPPLIERSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCYID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHCLEARINGONE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHCLEARINGTOW", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHCLEARINGTHREE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHEXCHANGERATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHDISCOUNTRATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHDEPT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHMAKINGNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHVERIFIER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHREVIEWDATA", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="BHREVIEWDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="TESTA", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TESTB", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    BalanceHost selectByPrimaryKey(String bhid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_HOST
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BHID, BHDATE, SUPPLIERSID, CURRENCYID, BHCLEARINGONE, BHCLEARINGTOW, BHCLEARINGTHREE, ",
        "BHEXCHANGERATE, BHDISCOUNTRATE, BHDEPT, BHREMARK, BHMAKINGNAME, BHVERIFIER, ",
        "BHREVIEWDATA, BHREVIEWDATE, TESTA, TESTB",
        "from BALANCE_HOST"
    })
    @ConstructorArgs({
        @Arg(column="BHID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BHDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="SUPPLIERSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCYID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHCLEARINGONE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHCLEARINGTOW", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHCLEARINGTHREE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHEXCHANGERATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHDISCOUNTRATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BHDEPT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHMAKINGNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHVERIFIER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BHREVIEWDATA", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="BHREVIEWDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="TESTA", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TESTB", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<BalanceHost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BALANCE_HOST
     *
     * @mbggenerated
     */
    @Update({
        "update BALANCE_HOST",
        "set BHDATE = #{bhdate,jdbcType=TIMESTAMP},",
          "SUPPLIERSID = #{suppliersid,jdbcType=VARCHAR},",
          "CURRENCYID = #{currencyid,jdbcType=VARCHAR},",
          "BHCLEARINGONE = #{bhclearingone,jdbcType=DECIMAL},",
          "BHCLEARINGTOW = #{bhclearingtow,jdbcType=DECIMAL},",
          "BHCLEARINGTHREE = #{bhclearingthree,jdbcType=DECIMAL},",
          "BHEXCHANGERATE = #{bhexchangerate,jdbcType=DECIMAL},",
          "BHDISCOUNTRATE = #{bhdiscountrate,jdbcType=DECIMAL},",
          "BHDEPT = #{bhdept,jdbcType=VARCHAR},",
          "BHREMARK = #{bhremark,jdbcType=VARCHAR},",
          "BHMAKINGNAME = #{bhmakingname,jdbcType=VARCHAR},",
          "BHVERIFIER = #{bhverifier,jdbcType=VARCHAR},",
          "BHREVIEWDATA = #{bhreviewdata,jdbcType=CHAR},",
          "BHREVIEWDATE = #{bhreviewdate,jdbcType=TIMESTAMP},",
          "TESTA = #{testa,jdbcType=VARCHAR},",
          "TESTB = #{testb,jdbcType=VARCHAR}",
        "where BHID = #{bhid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BalanceHost record);
}