package com.j5erp.mapper;

import com.j5erp.entity.Billtype;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface BilltypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTYPE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from BILLTYPE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTYPE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into BILLTYPE (ID, SOTYPE, ",
        "ENNAME, DETAILTABLE)",
        "values (#{id,jdbcType=DECIMAL}, #{sotype,jdbcType=VARCHAR}, ",
        "#{enname,jdbcType=VARCHAR}, #{detailtable,jdbcType=VARCHAR})"
    })
    int insert(Billtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTYPE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, SOTYPE, ENNAME, DETAILTABLE",
        "from BILLTYPE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="SOTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ENNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DETAILTABLE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Billtype selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTYPE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, SOTYPE, ENNAME, DETAILTABLE",
        "from BILLTYPE"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="SOTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ENNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DETAILTABLE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Billtype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BILLTYPE
     *
     * @mbggenerated
     */
    @Update({
        "update BILLTYPE",
        "set SOTYPE = #{sotype,jdbcType=VARCHAR},",
          "ENNAME = #{enname,jdbcType=VARCHAR},",
          "DETAILTABLE = #{detailtable,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Billtype record);
}