package com.j5erp.mapper;

import com.j5erp.entity.Buyer;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface BuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUYER
     *
     * @mbggenerated
     */
    @Delete({
        "delete from BUYER",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUYER
     *
     * @mbggenerated
     */
    @Insert({
        "insert into BUYER (ID, TIME, ",
        "SUPPLIERNAME, STATE, ",
        "MONEYTYPE, TAXSTATE, ",
        "RATE, DELIVER, TOUCHING, ",
        "SECTION, CHECKPEOPLE, ",
        "REMARK, COLUMNSTATE, ",
        "CHECKSTATE, COLUMN1, ",
        "COLUMN2, COLUMN3)",
        "values (#{id,jdbcType=VARCHAR}, #{time,jdbcType=TIMESTAMP}, ",
        "#{suppliername,jdbcType=VARCHAR}, #{state,jdbcType=DECIMAL}, ",
        "#{moneytype,jdbcType=DECIMAL}, #{taxstate,jdbcType=DECIMAL}, ",
        "#{rate,jdbcType=DECIMAL}, #{deliver,jdbcType=VARCHAR}, #{touching,jdbcType=VARCHAR}, ",
        "#{section,jdbcType=VARCHAR}, #{checkpeople,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{columnstate,jdbcType=DECIMAL}, ",
        "#{checkstate,jdbcType=DECIMAL}, #{column1,jdbcType=VARCHAR}, ",
        "#{column2,jdbcType=VARCHAR}, #{column3,jdbcType=VARCHAR})"
    })
    int insert(Buyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUYER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TIME, SUPPLIERNAME, STATE, MONEYTYPE, TAXSTATE, RATE, DELIVER, TOUCHING, ",
        "SECTION, CHECKPEOPLE, REMARK, COLUMNSTATE, CHECKSTATE, COLUMN1, COLUMN2, COLUMN3",
        "from BUYER",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="SUPPLIERNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTYPE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXSTATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="RATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DELIVER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCHING", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SECTION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKPEOPLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNSTATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKSTATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COLUMN1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN3", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Buyer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUYER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, TIME, SUPPLIERNAME, STATE, MONEYTYPE, TAXSTATE, RATE, DELIVER, TOUCHING, ",
        "SECTION, CHECKPEOPLE, REMARK, COLUMNSTATE, CHECKSTATE, COLUMN1, COLUMN2, COLUMN3",
        "from BUYER"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="SUPPLIERNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTYPE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXSTATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="RATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DELIVER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCHING", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SECTION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKPEOPLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNSTATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKSTATE", javaType=Integer.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COLUMN1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN3", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Buyer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BUYER
     *
     * @mbggenerated
     */
    @Update({
        "update BUYER",
        "set TIME = #{time,jdbcType=TIMESTAMP},",
          "SUPPLIERNAME = #{suppliername,jdbcType=VARCHAR},",
          "STATE = #{state,jdbcType=DECIMAL},",
          "MONEYTYPE = #{moneytype,jdbcType=DECIMAL},",
          "TAXSTATE = #{taxstate,jdbcType=DECIMAL},",
          "RATE = #{rate,jdbcType=DECIMAL},",
          "DELIVER = #{deliver,jdbcType=VARCHAR},",
          "TOUCHING = #{touching,jdbcType=VARCHAR},",
          "SECTION = #{section,jdbcType=VARCHAR},",
          "CHECKPEOPLE = #{checkpeople,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "COLUMNSTATE = #{columnstate,jdbcType=DECIMAL},",
          "CHECKSTATE = #{checkstate,jdbcType=DECIMAL},",
          "COLUMN1 = #{column1,jdbcType=VARCHAR},",
          "COLUMN2 = #{column2,jdbcType=VARCHAR},",
          "COLUMN3 = #{column3,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Buyer record);
}