package com.j5erp.mapper;

import com.j5erp.entity.Checks;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ChecksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from CHECKS",
        "where PDNUMBERS = #{pdnumbers,jdbcType=VARCHAR}",
          "and PDLINE = #{pdline,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("pdnumbers") String pdnumbers, @Param("pdline") String pdline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into CHECKS (PDNUMBERS, PDLINE, ",
        "PDMATERIALID, PDMATERIALNAME, ",
        "PDMATERIALTYPE, PDPAPERNUMBER, ",
        "PDNUMBER, PDLOSSPROFITNUMBERS, ",
        "PDPRICE, PDLOSSPROFITMONEY, ",
        "PDCAUSE)",
        "values (#{pdnumbers,jdbcType=VARCHAR}, #{pdline,jdbcType=VARCHAR}, ",
        "#{pdmaterialid,jdbcType=VARCHAR}, #{pdmaterialname,jdbcType=VARCHAR}, ",
        "#{pdmaterialtype,jdbcType=VARCHAR}, #{pdpapernumber,jdbcType=DECIMAL}, ",
        "#{pdnumber,jdbcType=DECIMAL}, #{pdlossprofitnumbers,jdbcType=DECIMAL}, ",
        "#{pdprice,jdbcType=DECIMAL}, #{pdlossprofitmoney,jdbcType=DECIMAL}, ",
        "#{pdcause,jdbcType=VARCHAR})"
    })
    int insert(Checks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "PDNUMBERS, PDLINE, PDMATERIALID, PDMATERIALNAME, PDMATERIALTYPE, PDPAPERNUMBER, ",
        "PDNUMBER, PDLOSSPROFITNUMBERS, PDPRICE, PDLOSSPROFITMONEY, PDCAUSE",
        "from CHECKS",
        "where PDNUMBERS = #{pdnumbers,jdbcType=VARCHAR}",
          "and PDLINE = #{pdline,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="PDNUMBERS", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PDLINE", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PDMATERIALID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PDMATERIALNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PDMATERIALTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PDPAPERNUMBER", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDNUMBER", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDLOSSPROFITNUMBERS", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDLOSSPROFITMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDCAUSE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Checks selectByPrimaryKey(@Param("pdnumbers") String pdnumbers, @Param("pdline") String pdline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "PDNUMBERS, PDLINE, PDMATERIALID, PDMATERIALNAME, PDMATERIALTYPE, PDPAPERNUMBER, ",
        "PDNUMBER, PDLOSSPROFITNUMBERS, PDPRICE, PDLOSSPROFITMONEY, PDCAUSE",
        "from CHECKS"
    })
    @ConstructorArgs({
        @Arg(column="PDNUMBERS", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PDLINE", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PDMATERIALID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PDMATERIALNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PDMATERIALTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PDPAPERNUMBER", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDNUMBER", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDLOSSPROFITNUMBERS", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDLOSSPROFITMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PDCAUSE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Checks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHECKS
     *
     * @mbggenerated
     */
    @Update({
        "update CHECKS",
        "set PDMATERIALID = #{pdmaterialid,jdbcType=VARCHAR},",
          "PDMATERIALNAME = #{pdmaterialname,jdbcType=VARCHAR},",
          "PDMATERIALTYPE = #{pdmaterialtype,jdbcType=VARCHAR},",
          "PDPAPERNUMBER = #{pdpapernumber,jdbcType=DECIMAL},",
          "PDNUMBER = #{pdnumber,jdbcType=DECIMAL},",
          "PDLOSSPROFITNUMBERS = #{pdlossprofitnumbers,jdbcType=DECIMAL},",
          "PDPRICE = #{pdprice,jdbcType=DECIMAL},",
          "PDLOSSPROFITMONEY = #{pdlossprofitmoney,jdbcType=DECIMAL},",
          "PDCAUSE = #{pdcause,jdbcType=VARCHAR}",
        "where PDNUMBERS = #{pdnumbers,jdbcType=VARCHAR}",
          "and PDLINE = #{pdline,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Checks record);
}