package com.j5erp.mapper;

import com.j5erp.entity.Cointype;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CointypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COINTYPE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from COINTYPE",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COINTYPE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into COINTYPE (ID, CNAME, ",
        "PAITIES)",
        "values (#{id,jdbcType=VARCHAR}, #{cname,jdbcType=VARCHAR}, ",
        "#{paities,jdbcType=DECIMAL})"
    })
    int insert(Cointype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COINTYPE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, CNAME, PAITIES",
        "from COINTYPE",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PAITIES", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    Cointype selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COINTYPE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, CNAME, PAITIES",
        "from COINTYPE"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PAITIES", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    List<Cointype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COINTYPE
     *
     * @mbggenerated
     */
    @Update({
        "update COINTYPE",
        "set CNAME = #{cname,jdbcType=VARCHAR},",
          "PAITIES = #{paities,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Cointype record);
}