package com.j5erp.mapper;

import com.j5erp.entity.Costdetail;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface CostdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COSTDETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from COSTDETAIL",
        "where CID = #{cid,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(BigDecimal cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COSTDETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into COSTDETAIL (CID, PID, ",
        "CLOUD, COSTNAME, ",
        "CURRENCY, EXCHANGERARATE, ",
        "MONEY, STANDARDCOIN, ",
        "CHECKSTATUS, DEMO1, ",
        "DEMO2, DEMO3)",
        "values (#{cid,jdbcType=DECIMAL}, #{pid,jdbcType=DECIMAL}, ",
        "#{cloud,jdbcType=DECIMAL}, #{costname,jdbcType=VARCHAR}, ",
        "#{currency,jdbcType=VARCHAR}, #{exchangerarate,jdbcType=DECIMAL}, ",
        "#{money,jdbcType=DECIMAL}, #{standardcoin,jdbcType=DECIMAL}, ",
        "#{checkstatus,jdbcType=DECIMAL}, #{demo1,jdbcType=DECIMAL}, ",
        "#{demo2,jdbcType=VARCHAR}, #{demo3,jdbcType=DECIMAL})"
    })
    int insert(Costdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COSTDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "CID, PID, CLOUD, COSTNAME, CURRENCY, EXCHANGERARATE, MONEY, STANDARDCOIN, CHECKSTATUS, ",
        "DEMO1, DEMO2, DEMO3",
        "from COSTDETAIL",
        "where CID = #{cid,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="CID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="PID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CLOUD", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COSTNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EXCHANGERARATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STANDARDCOIN", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKSTATUS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO1", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEMO3", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    Costdetail selectByPrimaryKey(BigDecimal cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COSTDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "CID, PID, CLOUD, COSTNAME, CURRENCY, EXCHANGERARATE, MONEY, STANDARDCOIN, CHECKSTATUS, ",
        "DEMO1, DEMO2, DEMO3",
        "from COSTDETAIL"
    })
    @ConstructorArgs({
        @Arg(column="CID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="PID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CLOUD", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COSTNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EXCHANGERARATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STANDARDCOIN", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKSTATUS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO1", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEMO3", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    List<Costdetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COSTDETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update COSTDETAIL",
        "set PID = #{pid,jdbcType=DECIMAL},",
          "CLOUD = #{cloud,jdbcType=DECIMAL},",
          "COSTNAME = #{costname,jdbcType=VARCHAR},",
          "CURRENCY = #{currency,jdbcType=VARCHAR},",
          "EXCHANGERARATE = #{exchangerarate,jdbcType=DECIMAL},",
          "MONEY = #{money,jdbcType=DECIMAL},",
          "STANDARDCOIN = #{standardcoin,jdbcType=DECIMAL},",
          "CHECKSTATUS = #{checkstatus,jdbcType=DECIMAL},",
          "DEMO1 = #{demo1,jdbcType=DECIMAL},",
          "DEMO2 = #{demo2,jdbcType=VARCHAR},",
          "DEMO3 = #{demo3,jdbcType=DECIMAL}",
        "where CID = #{cid,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Costdetail record);
}