package com.j5erp.mapper;

import com.j5erp.entity.Department;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated
     */
    @Delete({
        "delete from DEPARTMENT",
        "where DEPARTMENTID = #{departmentid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String departmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated
     */
    @Insert({
        "insert into DEPARTMENT (DEPARTMENTID, DEPARTMENTCN_NAME, ",
        "STANDBY_1, STANDBY_2)",
        "values (#{departmentid,jdbcType=VARCHAR}, #{departmentcnName,jdbcType=VARCHAR}, ",
        "#{standby1,jdbcType=VARCHAR}, #{standby2,jdbcType=VARCHAR})"
    })
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "DEPARTMENTID, DEPARTMENTCN_NAME, STANDBY_1, STANDBY_2",
        "from DEPARTMENT",
        "where DEPARTMENTID = #{departmentid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="DEPARTMENTCN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Department selectByPrimaryKey(String departmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "DEPARTMENTID, DEPARTMENTCN_NAME, STANDBY_1, STANDBY_2",
        "from DEPARTMENT"
    })
    @ConstructorArgs({
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="DEPARTMENTCN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbggenerated
     */
    @Update({
        "update DEPARTMENT",
        "set DEPARTMENTCN_NAME = #{departmentcnName,jdbcType=VARCHAR},",
          "STANDBY_1 = #{standby1,jdbcType=VARCHAR},",
          "STANDBY_2 = #{standby2,jdbcType=VARCHAR}",
        "where DEPARTMENTID = #{departmentid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Department record);
}