package com.j5erp.mapper;

import com.j5erp.entity.Enquirysons;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface EnquirysonsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRYSONS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ENQUIRYSONS",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRYSONS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ENQUIRYSONS (ID, LINE, ",
        "FID, WID, FROMID, ",
        "FROMTYPE, PRICE, ",
        "NUM, MONEY, TARIFF, ",
        "TARIFFMONEY, MONEYTARIFF, ",
        "GIFT, REMARK, COLUMN1, ",
        "COLUMN2, COLUMN3)",
        "values (#{id,jdbcType=VARCHAR}, #{line,jdbcType=VARCHAR}, ",
        "#{fid,jdbcType=VARCHAR}, #{wid,jdbcType=VARCHAR}, #{fromid,jdbcType=VARCHAR}, ",
        "#{fromtype,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, ",
        "#{num,jdbcType=DECIMAL}, #{money,jdbcType=DECIMAL}, #{tariff,jdbcType=DECIMAL}, ",
        "#{tariffmoney,jdbcType=DECIMAL}, #{moneytariff,jdbcType=DECIMAL}, ",
        "#{gift,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR}, #{column1,jdbcType=VARCHAR}, ",
        "#{column2,jdbcType=VARCHAR}, #{column3,jdbcType=VARCHAR})"
    })
    int insert(Enquirysons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRYSONS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, LINE, FID, WID, FROMID, FROMTYPE, PRICE, NUM, MONEY, TARIFF, TARIFFMONEY, ",
        "MONEYTARIFF, GIFT, REMARK, COLUMN1, COLUMN2, COLUMN3",
        "from ENQUIRYSONS",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="WID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="NUM", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TARIFF", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TARIFFMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTARIFF", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="GIFT", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN3", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Enquirysons selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRYSONS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, LINE, FID, WID, FROMID, FROMTYPE, PRICE, NUM, MONEY, TARIFF, TARIFFMONEY, ",
        "MONEYTARIFF, GIFT, REMARK, COLUMN1, COLUMN2, COLUMN3",
        "from ENQUIRYSONS"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="WID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="NUM", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TARIFF", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TARIFFMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTARIFF", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="GIFT", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN3", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Enquirysons> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ENQUIRYSONS
     *
     * @mbggenerated
     */
    @Update({
        "update ENQUIRYSONS",
        "set LINE = #{line,jdbcType=VARCHAR},",
          "FID = #{fid,jdbcType=VARCHAR},",
          "WID = #{wid,jdbcType=VARCHAR},",
          "FROMID = #{fromid,jdbcType=VARCHAR},",
          "FROMTYPE = #{fromtype,jdbcType=VARCHAR},",
          "PRICE = #{price,jdbcType=DECIMAL},",
          "NUM = #{num,jdbcType=DECIMAL},",
          "MONEY = #{money,jdbcType=DECIMAL},",
          "TARIFF = #{tariff,jdbcType=DECIMAL},",
          "TARIFFMONEY = #{tariffmoney,jdbcType=DECIMAL},",
          "MONEYTARIFF = #{moneytariff,jdbcType=DECIMAL},",
          "GIFT = #{gift,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "COLUMN1 = #{column1,jdbcType=VARCHAR},",
          "COLUMN2 = #{column2,jdbcType=VARCHAR},",
          "COLUMN3 = #{column3,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Enquirysons record);
}