package com.j5erp.mapper;

import com.j5erp.entity.Estimatemoneybilldetail;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface EstimatemoneybilldetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESTIMATEMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ESTIMATEMONEYBILLDETAIL",
        "where ID = #{id,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("id") String id, @Param("lineno") Long lineno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESTIMATEMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ESTIMATEMONEYBILLDETAIL (ID, LINENO, ",
        "BILLTYPEID, BILLNO, ",
        "ESTIMATEMONEY, REMARK)",
        "values (#{id,jdbcType=VARCHAR}, #{lineno,jdbcType=DECIMAL}, ",
        "#{billtypeid,jdbcType=DECIMAL}, #{billno,jdbcType=VARCHAR}, ",
        "#{estimatemoney,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(Estimatemoneybilldetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESTIMATEMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, LINENO, BILLTYPEID, BILLNO, ESTIMATEMONEY, REMARK",
        "from ESTIMATEMONEYBILLDETAIL",
        "where ID = #{id,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINENO", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLTYPEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ESTIMATEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Estimatemoneybilldetail selectByPrimaryKey(@Param("id") String id, @Param("lineno") Long lineno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESTIMATEMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, LINENO, BILLTYPEID, BILLNO, ESTIMATEMONEY, REMARK",
        "from ESTIMATEMONEYBILLDETAIL"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINENO", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLTYPEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ESTIMATEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Estimatemoneybilldetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESTIMATEMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update ESTIMATEMONEYBILLDETAIL",
        "set BILLTYPEID = #{billtypeid,jdbcType=DECIMAL},",
          "BILLNO = #{billno,jdbcType=VARCHAR},",
          "ESTIMATEMONEY = #{estimatemoney,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Estimatemoneybilldetail record);
}