package com.j5erp.mapper;

import com.j5erp.entity.Matterwithdepot;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface MatterwithdepotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERWITHDEPOT
     *
     * @mbggenerated
     */
    @Delete({
        "delete from MATTERWITHDEPOT",
        "where MATTERWITHDEPOTID = #{matterwithdepotid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String matterwithdepotid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERWITHDEPOT
     *
     * @mbggenerated
     */
    @Insert({
        "insert into MATTERWITHDEPOT (MATTERWITHDEPOTID, DEPOTID, ",
        "MATTERID, MATTERNUMBER, ",
        "MATTERMONEY, MATTERPRICE, ",
        "STATUS, PREPARE1, ",
        "PREPARE2)",
        "values (#{matterwithdepotid,jdbcType=VARCHAR}, #{depotid,jdbcType=VARCHAR}, ",
        "#{matterid,jdbcType=VARCHAR}, #{matternumber,jdbcType=DECIMAL}, ",
        "#{mattermoney,jdbcType=DECIMAL}, #{matterprice,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=DECIMAL}, #{prepare1,jdbcType=VARCHAR}, ",
        "#{prepare2,jdbcType=VARCHAR})"
    })
    int insert(Matterwithdepot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERWITHDEPOT
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MATTERWITHDEPOTID, DEPOTID, MATTERID, MATTERNUMBER, MATTERMONEY, MATTERPRICE, ",
        "STATUS, PREPARE1, PREPARE2",
        "from MATTERWITHDEPOT",
        "where MATTERWITHDEPOTID = #{matterwithdepotid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="MATTERWITHDEPOTID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="DEPOTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATTERNUMBER", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATTERMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATTERPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Matterwithdepot selectByPrimaryKey(String matterwithdepotid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERWITHDEPOT
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MATTERWITHDEPOTID, DEPOTID, MATTERID, MATTERNUMBER, MATTERMONEY, MATTERPRICE, ",
        "STATUS, PREPARE1, PREPARE2",
        "from MATTERWITHDEPOT"
    })
    @ConstructorArgs({
        @Arg(column="MATTERWITHDEPOTID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="DEPOTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATTERNUMBER", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATTERMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATTERPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Matterwithdepot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERWITHDEPOT
     *
     * @mbggenerated
     */
    @Update({
        "update MATTERWITHDEPOT",
        "set DEPOTID = #{depotid,jdbcType=VARCHAR},",
          "MATTERID = #{matterid,jdbcType=VARCHAR},",
          "MATTERNUMBER = #{matternumber,jdbcType=DECIMAL},",
          "MATTERMONEY = #{mattermoney,jdbcType=DECIMAL},",
          "MATTERPRICE = #{matterprice,jdbcType=DECIMAL},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "PREPARE1 = #{prepare1,jdbcType=VARCHAR},",
          "PREPARE2 = #{prepare2,jdbcType=VARCHAR}",
        "where MATTERWITHDEPOTID = #{matterwithdepotid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Matterwithdepot record);
}