package com.j5erp.mapper;

import com.j5erp.entity.Matterinfo;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface MatterinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERINFO
     *
     * @mbggenerated
     */
    @Delete({
        "delete from MATTERINFO",
        "where MATTERID = #{matterid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String matterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERINFO
     *
     * @mbggenerated
     */
    @Insert({
        "insert into MATTERINFO (MATTERID, MATTERNAME, ",
        "MATTERTYPEID, SAVE, ",
        "MODELS, SUGGESTPRICE, ",
        "ASELL, BSELL, CSELL, ",
        "DSELL, ESELL, STANDARDBID, ",
        "MONEYTYPE, BIAOCB, ",
        "TAXSTATE, MATTERREMARK, ",
        "SHUILV, ALOCAIGOU, ",
        "SALESERID, ANQUSAVE, ",
        "BSUMCOST, AVGCOST, ",
        "COST, STARTSCOST, ",
        "STATUS, PREPARE1, ",
        "PREPARE2)",
        "values (#{matterid,jdbcType=VARCHAR}, #{mattername,jdbcType=VARCHAR}, ",
        "#{mattertypeid,jdbcType=VARCHAR}, #{save,jdbcType=VARCHAR}, ",
        "#{models,jdbcType=VARCHAR}, #{suggestprice,jdbcType=VARCHAR}, ",
        "#{asell,jdbcType=DECIMAL}, #{bsell,jdbcType=DECIMAL}, #{csell,jdbcType=DECIMAL}, ",
        "#{dsell,jdbcType=DECIMAL}, #{esell,jdbcType=DECIMAL}, #{standardbid,jdbcType=DECIMAL}, ",
        "#{moneytype,jdbcType=VARCHAR}, #{biaocb,jdbcType=DECIMAL}, ",
        "#{taxstate,jdbcType=DECIMAL}, #{matterremark,jdbcType=VARCHAR}, ",
        "#{shuilv,jdbcType=DECIMAL}, #{alocaigou,jdbcType=DECIMAL}, ",
        "#{saleserid,jdbcType=VARCHAR}, #{anqusave,jdbcType=DECIMAL}, ",
        "#{bsumcost,jdbcType=DECIMAL}, #{avgcost,jdbcType=DECIMAL}, ",
        "#{cost,jdbcType=DECIMAL}, #{startscost,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=DECIMAL}, #{prepare1,jdbcType=VARCHAR}, ",
        "#{prepare2,jdbcType=VARCHAR})"
    })
    int insert(Matterinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERINFO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MATTERID, MATTERNAME, MATTERTYPEID, SAVE, MODELS, SUGGESTPRICE, ASELL, BSELL, ",
        "CSELL, DSELL, ESELL, STANDARDBID, MONEYTYPE, BIAOCB, TAXSTATE, MATTERREMARK, ",
        "SHUILV, ALOCAIGOU, SALESERID, ANQUSAVE, BSUMCOST, AVGCOST, COST, STARTSCOST, ",
        "STATUS, PREPARE1, PREPARE2",
        "from MATTERINFO",
        "where MATTERID = #{matterid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="MATTERNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATTERTYPEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SAVE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MODELS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUGGESTPRICE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ASELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BSELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CSELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DSELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ESELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STANDARDBID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BIAOCB", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXSTATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATTERREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SHUILV", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ALOCAIGOU", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SALESERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ANQUSAVE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BSUMCOST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AVGCOST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STARTSCOST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Matterinfo selectByPrimaryKey(String matterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERINFO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MATTERID, MATTERNAME, MATTERTYPEID, SAVE, MODELS, SUGGESTPRICE, ASELL, BSELL, ",
        "CSELL, DSELL, ESELL, STANDARDBID, MONEYTYPE, BIAOCB, TAXSTATE, MATTERREMARK, ",
        "SHUILV, ALOCAIGOU, SALESERID, ANQUSAVE, BSUMCOST, AVGCOST, COST, STARTSCOST, ",
        "STATUS, PREPARE1, PREPARE2",
        "from MATTERINFO"
    })
    @ConstructorArgs({
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="MATTERNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATTERTYPEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SAVE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MODELS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUGGESTPRICE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ASELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BSELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CSELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DSELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ESELL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STANDARDBID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BIAOCB", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXSTATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATTERREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SHUILV", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ALOCAIGOU", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SALESERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ANQUSAVE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BSUMCOST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AVGCOST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STARTSCOST", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Matterinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERINFO
     *
     * @mbggenerated
     */
    @Update({
        "update MATTERINFO",
        "set MATTERNAME = #{mattername,jdbcType=VARCHAR},",
          "MATTERTYPEID = #{mattertypeid,jdbcType=VARCHAR},",
          "SAVE = #{save,jdbcType=VARCHAR},",
          "MODELS = #{models,jdbcType=VARCHAR},",
          "SUGGESTPRICE = #{suggestprice,jdbcType=VARCHAR},",
          "ASELL = #{asell,jdbcType=DECIMAL},",
          "BSELL = #{bsell,jdbcType=DECIMAL},",
          "CSELL = #{csell,jdbcType=DECIMAL},",
          "DSELL = #{dsell,jdbcType=DECIMAL},",
          "ESELL = #{esell,jdbcType=DECIMAL},",
          "STANDARDBID = #{standardbid,jdbcType=DECIMAL},",
          "MONEYTYPE = #{moneytype,jdbcType=VARCHAR},",
          "BIAOCB = #{biaocb,jdbcType=DECIMAL},",
          "TAXSTATE = #{taxstate,jdbcType=DECIMAL},",
          "MATTERREMARK = #{matterremark,jdbcType=VARCHAR},",
          "SHUILV = #{shuilv,jdbcType=DECIMAL},",
          "ALOCAIGOU = #{alocaigou,jdbcType=DECIMAL},",
          "SALESERID = #{saleserid,jdbcType=VARCHAR},",
          "ANQUSAVE = #{anqusave,jdbcType=DECIMAL},",
          "BSUMCOST = #{bsumcost,jdbcType=DECIMAL},",
          "AVGCOST = #{avgcost,jdbcType=DECIMAL},",
          "COST = #{cost,jdbcType=DECIMAL},",
          "STARTSCOST = #{startscost,jdbcType=DECIMAL},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "PREPARE1 = #{prepare1,jdbcType=VARCHAR},",
          "PREPARE2 = #{prepare2,jdbcType=VARCHAR}",
        "where MATTERID = #{matterid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Matterinfo record);
}