package com.j5erp.mapper;

import com.j5erp.entity.Mattertype;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface MattertypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERTYPE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from MATTERTYPE",
        "where MATTERTYPEID = #{mattertypeid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String mattertypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERTYPE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into MATTERTYPE (MATTERTYPEID, TYPE, ",
        "ENAME, SAVECOURSE, ",
        "SALESPROCEED, SALESCOST, ",
        "REMARK, STATUS, ",
        "PREPARE1, PREPARE2)",
        "values (#{mattertypeid,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
        "#{ename,jdbcType=VARCHAR}, #{savecourse,jdbcType=VARCHAR}, ",
        "#{salesproceed,jdbcType=VARCHAR}, #{salescost,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{status,jdbcType=DECIMAL}, ",
        "#{prepare1,jdbcType=VARCHAR}, #{prepare2,jdbcType=VARCHAR})"
    })
    int insert(Mattertype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERTYPE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MATTERTYPEID, TYPE, ENAME, SAVECOURSE, SALESPROCEED, SALESCOST, REMARK, STATUS, ",
        "PREPARE1, PREPARE2",
        "from MATTERTYPE",
        "where MATTERTYPEID = #{mattertypeid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="MATTERTYPEID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ENAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SAVECOURSE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALESPROCEED", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALESCOST", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Mattertype selectByPrimaryKey(String mattertypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERTYPE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MATTERTYPEID, TYPE, ENAME, SAVECOURSE, SALESPROCEED, SALESCOST, REMARK, STATUS, ",
        "PREPARE1, PREPARE2",
        "from MATTERTYPE"
    })
    @ConstructorArgs({
        @Arg(column="MATTERTYPEID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="TYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ENAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SAVECOURSE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALESPROCEED", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALESCOST", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Mattertype> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MATTERTYPE
     *
     * @mbggenerated
     */
    @Update({
        "update MATTERTYPE",
        "set TYPE = #{type,jdbcType=VARCHAR},",
          "ENAME = #{ename,jdbcType=VARCHAR},",
          "SAVECOURSE = #{savecourse,jdbcType=VARCHAR},",
          "SALESPROCEED = #{salesproceed,jdbcType=VARCHAR},",
          "SALESCOST = #{salescost,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "PREPARE1 = #{prepare1,jdbcType=VARCHAR},",
          "PREPARE2 = #{prepare2,jdbcType=VARCHAR}",
        "where MATTERTYPEID = #{mattertypeid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Mattertype record);
}