package com.j5erp.mapper;

import com.j5erp.entity.Movestorage;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface MovestorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVESTORAGE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from MOVESTORAGE",
        "where MSENO = #{mseno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String mseno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVESTORAGE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into MOVESTORAGE (MSENO, MSEDATE, ",
        "MSEOUTSTORAGE, MSEINSERTSTOR, ",
        "MSEEMPLOYEE, MESAUDITINGEMP, ",
        "MESREMARK, MESSTATUS)",
        "values (#{mseno,jdbcType=VARCHAR}, #{msedate,jdbcType=TIMESTAMP}, ",
        "#{mseoutstorage,jdbcType=VARCHAR}, #{mseinsertstor,jdbcType=VARCHAR}, ",
        "#{mseemployee,jdbcType=VARCHAR}, #{mesauditingemp,jdbcType=VARCHAR}, ",
        "#{mesremark,jdbcType=VARCHAR}, #{messtatus,jdbcType=DECIMAL})"
    })
    int insert(Movestorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVESTORAGE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MSENO, MSEDATE, MSEOUTSTORAGE, MSEINSERTSTOR, MSEEMPLOYEE, MESAUDITINGEMP, MESREMARK, ",
        "MESSTATUS",
        "from MOVESTORAGE",
        "where MSENO = #{mseno,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="MSENO", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="MSEDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="MSEOUTSTORAGE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MSEINSERTSTOR", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MSEEMPLOYEE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MESAUDITINGEMP", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MESREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MESSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL)
    })
    Movestorage selectByPrimaryKey(String mseno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVESTORAGE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MSENO, MSEDATE, MSEOUTSTORAGE, MSEINSERTSTOR, MSEEMPLOYEE, MESAUDITINGEMP, MESREMARK, ",
        "MESSTATUS",
        "from MOVESTORAGE"
    })
    @ConstructorArgs({
        @Arg(column="MSENO", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="MSEDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="MSEOUTSTORAGE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MSEINSERTSTOR", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MSEEMPLOYEE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MESAUDITINGEMP", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MESREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MESSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL)
    })
    List<Movestorage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVESTORAGE
     *
     * @mbggenerated
     */
    @Update({
        "update MOVESTORAGE",
        "set MSEDATE = #{msedate,jdbcType=TIMESTAMP},",
          "MSEOUTSTORAGE = #{mseoutstorage,jdbcType=VARCHAR},",
          "MSEINSERTSTOR = #{mseinsertstor,jdbcType=VARCHAR},",
          "MSEEMPLOYEE = #{mseemployee,jdbcType=VARCHAR},",
          "MESAUDITINGEMP = #{mesauditingemp,jdbcType=VARCHAR},",
          "MESREMARK = #{mesremark,jdbcType=VARCHAR},",
          "MESSTATUS = #{messtatus,jdbcType=DECIMAL}",
        "where MSENO = #{mseno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Movestorage record);
}