package com.j5erp.mapper;

import com.j5erp.entity.Movedetails;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface MovedetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVEDETAILS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from MOVEDETAILS",
        "where MSENO = #{mseno,jdbcType=VARCHAR}",
          "and LINEMARK = #{linemark,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("mseno") String mseno, @Param("linemark") Long linemark);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVEDETAILS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into MOVEDETAILS (MSENO, LINEMARK, ",
        "MDSMATERIELTYPE, MDSMATERIELNAME, ",
        "MDSMATERIELSPECS, MDSMATERIELUNIT, ",
        "MDSMATERIELNUM, MDSREMARK)",
        "values (#{mseno,jdbcType=VARCHAR}, #{linemark,jdbcType=DECIMAL}, ",
        "#{mdsmaterieltype,jdbcType=VARCHAR}, #{mdsmaterielname,jdbcType=VARCHAR}, ",
        "#{mdsmaterielspecs,jdbcType=VARCHAR}, #{mdsmaterielunit,jdbcType=VARCHAR}, ",
        "#{mdsmaterielnum,jdbcType=DECIMAL}, #{mdsremark,jdbcType=VARCHAR})"
    })
    int insert(Movedetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVEDETAILS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MSENO, LINEMARK, MDSMATERIELTYPE, MDSMATERIELNAME, MDSMATERIELSPECS, MDSMATERIELUNIT, ",
        "MDSMATERIELNUM, MDSREMARK",
        "from MOVEDETAILS",
        "where MSENO = #{mseno,jdbcType=VARCHAR}",
          "and LINEMARK = #{linemark,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="MSENO", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINEMARK", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="MDSMATERIELTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELSPECS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELNUM", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MDSREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Movedetails selectByPrimaryKey(@Param("mseno") String mseno, @Param("linemark") Long linemark);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVEDETAILS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "MSENO, LINEMARK, MDSMATERIELTYPE, MDSMATERIELNAME, MDSMATERIELSPECS, MDSMATERIELUNIT, ",
        "MDSMATERIELNUM, MDSREMARK",
        "from MOVEDETAILS"
    })
    @ConstructorArgs({
        @Arg(column="MSENO", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINEMARK", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="MDSMATERIELTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELSPECS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MDSMATERIELNUM", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MDSREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Movedetails> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOVEDETAILS
     *
     * @mbggenerated
     */
    @Update({
        "update MOVEDETAILS",
        "set MDSMATERIELTYPE = #{mdsmaterieltype,jdbcType=VARCHAR},",
          "MDSMATERIELNAME = #{mdsmaterielname,jdbcType=VARCHAR},",
          "MDSMATERIELSPECS = #{mdsmaterielspecs,jdbcType=VARCHAR},",
          "MDSMATERIELUNIT = #{mdsmaterielunit,jdbcType=VARCHAR},",
          "MDSMATERIELNUM = #{mdsmaterielnum,jdbcType=DECIMAL},",
          "MDSREMARK = #{mdsremark,jdbcType=VARCHAR}",
        "where MSENO = #{mseno,jdbcType=VARCHAR}",
          "and LINEMARK = #{linemark,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Movedetails record);
}