package com.j5erp.mapper;

import com.j5erp.entity.Nation;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface NationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATION
     *
     * @mbggenerated
     */
    @Delete({
        "delete from NATION",
        "where NATIONID = #{nationid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String nationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATION
     *
     * @mbggenerated
     */
    @Insert({
        "insert into NATION (NATIONID, NATIONCN_NAME)",
        "values (#{nationid,jdbcType=VARCHAR}, #{nationcnName,jdbcType=VARCHAR})"
    })
    int insert(Nation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATION
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "NATIONID, NATIONCN_NAME",
        "from NATION",
        "where NATIONID = #{nationid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="NATIONID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="NATIONCN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Nation selectByPrimaryKey(String nationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATION
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "NATIONID, NATIONCN_NAME",
        "from NATION"
    })
    @ConstructorArgs({
        @Arg(column="NATIONID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="NATIONCN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Nation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATION
     *
     * @mbggenerated
     */
    @Update({
        "update NATION",
        "set NATIONCN_NAME = #{nationcnName,jdbcType=VARCHAR}",
        "where NATIONID = #{nationid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Nation record);
}