package com.j5erp.mapper;

import com.j5erp.entity.Nationality;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface NationalityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated
     */
    @Delete({
        "delete from NATIONALITY",
        "where NATIONALITYID = #{nationalityid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String nationalityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated
     */
    @Insert({
        "insert into NATIONALITY (NATIONALITYID, NATIONALITYCN_NAME)",
        "values (#{nationalityid,jdbcType=VARCHAR}, #{nationalitycnName,jdbcType=VARCHAR})"
    })
    int insert(Nationality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "NATIONALITYID, NATIONALITYCN_NAME",
        "from NATIONALITY",
        "where NATIONALITYID = #{nationalityid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="NATIONALITYID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="NATIONALITYCN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Nationality selectByPrimaryKey(String nationalityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "NATIONALITYID, NATIONALITYCN_NAME",
        "from NATIONALITY"
    })
    @ConstructorArgs({
        @Arg(column="NATIONALITYID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="NATIONALITYCN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Nationality> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NATIONALITY
     *
     * @mbggenerated
     */
    @Update({
        "update NATIONALITY",
        "set NATIONALITYCN_NAME = #{nationalitycnName,jdbcType=VARCHAR}",
        "where NATIONALITYID = #{nationalityid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Nationality record);
}