package com.j5erp.mapper;

import com.j5erp.entity.Outgoingdetail;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface OutgoingdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTGOINGDETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from OUTGOINGDETAIL",
        "where LINENUMBER = #{linenumber,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String linenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTGOINGDETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into OUTGOINGDETAIL (LINENUMBER, BILLNO, ",
        "DEPOT, BILLDATE, ",
        "REMARKS, TYPE, QUANTITY, ",
        "MONEY, STATUS, PREPARE1, ",
        "PREPARE2)",
        "values (#{linenumber,jdbcType=VARCHAR}, #{billno,jdbcType=VARCHAR}, ",
        "#{depot,jdbcType=VARCHAR}, #{billdate,jdbcType=DECIMAL}, ",
        "#{remarks,jdbcType=DECIMAL}, #{type,jdbcType=DECIMAL}, #{quantity,jdbcType=DECIMAL}, ",
        "#{money,jdbcType=DECIMAL}, #{status,jdbcType=DECIMAL}, #{prepare1,jdbcType=VARCHAR}, ",
        "#{prepare2,jdbcType=VARCHAR})"
    })
    int insert(Outgoingdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTGOINGDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "LINENUMBER, BILLNO, DEPOT, BILLDATE, REMARKS, TYPE, QUANTITY, MONEY, STATUS, ",
        "PREPARE1, PREPARE2",
        "from OUTGOINGDETAIL",
        "where LINENUMBER = #{linenumber,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="LINENUMBER", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPOT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BILLDATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARKS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TYPE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QUANTITY", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Outgoingdetail selectByPrimaryKey(String linenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTGOINGDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "LINENUMBER, BILLNO, DEPOT, BILLDATE, REMARKS, TYPE, QUANTITY, MONEY, STATUS, ",
        "PREPARE1, PREPARE2",
        "from OUTGOINGDETAIL"
    })
    @ConstructorArgs({
        @Arg(column="LINENUMBER", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPOT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BILLDATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARKS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TYPE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QUANTITY", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Outgoingdetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OUTGOINGDETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update OUTGOINGDETAIL",
        "set BILLNO = #{billno,jdbcType=VARCHAR},",
          "DEPOT = #{depot,jdbcType=VARCHAR},",
          "BILLDATE = #{billdate,jdbcType=DECIMAL},",
          "REMARKS = #{remarks,jdbcType=DECIMAL},",
          "TYPE = #{type,jdbcType=DECIMAL},",
          "QUANTITY = #{quantity,jdbcType=DECIMAL},",
          "MONEY = #{money,jdbcType=DECIMAL},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "PREPARE1 = #{prepare1,jdbcType=VARCHAR},",
          "PREPARE2 = #{prepare2,jdbcType=VARCHAR}",
        "where LINENUMBER = #{linenumber,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Outgoingdetail record);
}