package com.j5erp.mapper;

import com.j5erp.entity.Purchase;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface PurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from PURCHASE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into PURCHASE (ID, SDATE, ",
        "STYPE, SMONEY, TOUCHING, ",
        "ACCOUNT, CHECKSTATUS, ",
        "DEMO1, DEMO2, DEMO3)",
        "values (#{id,jdbcType=DECIMAL}, #{sdate,jdbcType=TIMESTAMP}, ",
        "#{stype,jdbcType=VARCHAR}, #{smoney,jdbcType=DECIMAL}, #{touching,jdbcType=VARCHAR}, ",
        "#{account,jdbcType=VARCHAR}, #{checkstatus,jdbcType=DECIMAL}, ",
        "#{demo1,jdbcType=DECIMAL}, #{demo2,jdbcType=VARCHAR}, #{demo3,jdbcType=DECIMAL})"
    })
    int insert(Purchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, SDATE, STYPE, SMONEY, TOUCHING, ACCOUNT, CHECKSTATUS, DEMO1, DEMO2, DEMO3",
        "from PURCHASE",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="SDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="STYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TOUCHING", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ACCOUNT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATUS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO1", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEMO3", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    Purchase selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, SDATE, STYPE, SMONEY, TOUCHING, ACCOUNT, CHECKSTATUS, DEMO1, DEMO2, DEMO3",
        "from PURCHASE"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="SDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="STYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TOUCHING", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ACCOUNT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATUS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO1", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEMO3", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    List<Purchase> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASE
     *
     * @mbggenerated
     */
    @Update({
        "update PURCHASE",
        "set SDATE = #{sdate,jdbcType=TIMESTAMP},",
          "STYPE = #{stype,jdbcType=VARCHAR},",
          "SMONEY = #{smoney,jdbcType=DECIMAL},",
          "TOUCHING = #{touching,jdbcType=VARCHAR},",
          "ACCOUNT = #{account,jdbcType=VARCHAR},",
          "CHECKSTATUS = #{checkstatus,jdbcType=DECIMAL},",
          "DEMO1 = #{demo1,jdbcType=DECIMAL},",
          "DEMO2 = #{demo2,jdbcType=VARCHAR},",
          "DEMO3 = #{demo3,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Purchase record);
}