package com.j5erp.mapper;

import com.j5erp.entity.Purchaserequests;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface PurchaserequestsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUESTS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from PURCHASEREQUESTS",
        "where QGBILLNUMBERS = #{qgbillnumbers,jdbcType=VARCHAR}",
          "and QGLINE = #{qgline,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("qgbillnumbers") String qgbillnumbers, @Param("qgline") String qgline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUESTS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into PURCHASEREQUESTS (QGBILLNUMBERS, QGLINE, ",
        "QGMATERIALID, QGMATERIALNAME, ",
        "QGMATERIALTYPE, QGUNIT, ",
        "QGNUMBER, QGSTANDARDJJ, ",
        "QGSTANDARDJJJE, QGCURRENCY, ",
        "QGPRICE, QGJJMONEY, ",
        "QGNEEDDATE, QGSUGGESTDATE, ",
        "QGTYPEREMARK, QGSOURCEBILL, ",
        "QGSOURCENUMBERS)",
        "values (#{qgbillnumbers,jdbcType=VARCHAR}, #{qgline,jdbcType=VARCHAR}, ",
        "#{qgmaterialid,jdbcType=VARCHAR}, #{qgmaterialname,jdbcType=VARCHAR}, ",
        "#{qgmaterialtype,jdbcType=VARCHAR}, #{qgunit,jdbcType=VARCHAR}, ",
        "#{qgnumber,jdbcType=DECIMAL}, #{qgstandardjj,jdbcType=DECIMAL}, ",
        "#{qgstandardjjje,jdbcType=DECIMAL}, #{qgcurrency,jdbcType=VARCHAR}, ",
        "#{qgprice,jdbcType=DECIMAL}, #{qgjjmoney,jdbcType=DECIMAL}, ",
        "#{qgneeddate,jdbcType=TIMESTAMP}, #{qgsuggestdate,jdbcType=TIMESTAMP}, ",
        "#{qgtyperemark,jdbcType=VARCHAR}, #{qgsourcebill,jdbcType=VARCHAR}, ",
        "#{qgsourcenumbers,jdbcType=VARCHAR})"
    })
    int insert(Purchaserequests record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUESTS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "QGBILLNUMBERS, QGLINE, QGMATERIALID, QGMATERIALNAME, QGMATERIALTYPE, QGUNIT, ",
        "QGNUMBER, QGSTANDARDJJ, QGSTANDARDJJJE, QGCURRENCY, QGPRICE, QGJJMONEY, QGNEEDDATE, ",
        "QGSUGGESTDATE, QGTYPEREMARK, QGSOURCEBILL, QGSOURCENUMBERS",
        "from PURCHASEREQUESTS",
        "where QGBILLNUMBERS = #{qgbillnumbers,jdbcType=VARCHAR}",
          "and QGLINE = #{qgline,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="QGBILLNUMBERS", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="QGLINE", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="QGMATERIALID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGMATERIALNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGMATERIALTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGNUMBER", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGSTANDARDJJ", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGSTANDARDJJJE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGCURRENCY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGJJMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGNEEDDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="QGSUGGESTDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="QGTYPEREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGSOURCEBILL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGSOURCENUMBERS", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Purchaserequests selectByPrimaryKey(@Param("qgbillnumbers") String qgbillnumbers, @Param("qgline") String qgline);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUESTS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "QGBILLNUMBERS, QGLINE, QGMATERIALID, QGMATERIALNAME, QGMATERIALTYPE, QGUNIT, ",
        "QGNUMBER, QGSTANDARDJJ, QGSTANDARDJJJE, QGCURRENCY, QGPRICE, QGJJMONEY, QGNEEDDATE, ",
        "QGSUGGESTDATE, QGTYPEREMARK, QGSOURCEBILL, QGSOURCENUMBERS",
        "from PURCHASEREQUESTS"
    })
    @ConstructorArgs({
        @Arg(column="QGBILLNUMBERS", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="QGLINE", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="QGMATERIALID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGMATERIALNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGMATERIALTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGNUMBER", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGSTANDARDJJ", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGSTANDARDJJJE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGCURRENCY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGJJMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="QGNEEDDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="QGSUGGESTDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="QGTYPEREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGSOURCEBILL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QGSOURCENUMBERS", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Purchaserequests> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PURCHASEREQUESTS
     *
     * @mbggenerated
     */
    @Update({
        "update PURCHASEREQUESTS",
        "set QGMATERIALID = #{qgmaterialid,jdbcType=VARCHAR},",
          "QGMATERIALNAME = #{qgmaterialname,jdbcType=VARCHAR},",
          "QGMATERIALTYPE = #{qgmaterialtype,jdbcType=VARCHAR},",
          "QGUNIT = #{qgunit,jdbcType=VARCHAR},",
          "QGNUMBER = #{qgnumber,jdbcType=DECIMAL},",
          "QGSTANDARDJJ = #{qgstandardjj,jdbcType=DECIMAL},",
          "QGSTANDARDJJJE = #{qgstandardjjje,jdbcType=DECIMAL},",
          "QGCURRENCY = #{qgcurrency,jdbcType=VARCHAR},",
          "QGPRICE = #{qgprice,jdbcType=DECIMAL},",
          "QGJJMONEY = #{qgjjmoney,jdbcType=DECIMAL},",
          "QGNEEDDATE = #{qgneeddate,jdbcType=TIMESTAMP},",
          "QGSUGGESTDATE = #{qgsuggestdate,jdbcType=TIMESTAMP},",
          "QGTYPEREMARK = #{qgtyperemark,jdbcType=VARCHAR},",
          "QGSOURCEBILL = #{qgsourcebill,jdbcType=VARCHAR},",
          "QGSOURCENUMBERS = #{qgsourcenumbers,jdbcType=VARCHAR}",
        "where QGBILLNUMBERS = #{qgbillnumbers,jdbcType=VARCHAR}",
          "and QGLINE = #{qgline,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Purchaserequests record);
}