package com.j5erp.mapper;

import com.j5erp.entity.Putstorage;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface PutstorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTSTORAGE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from PUTSTORAGE",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTSTORAGE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into PUTSTORAGE (ID, STORAGEID, ",
        "SUPPLIERNAME, TIME, ",
        "SUPPLIERADDRESS, STATE, ",
        "TYPE, MONEYTYPE, ",
        "TAXSTATE, RATE, ",
        "DELIVER, TOUCHING, ",
        "SECTION, CHECKPEOPLE, ",
        "REMARK, CHECKSTATE, ",
        "COLUMN1, COLUMN2, ",
        "COLUMN3)",
        "values (#{id,jdbcType=VARCHAR}, #{storageid,jdbcType=VARCHAR}, ",
        "#{suppliername,jdbcType=VARCHAR}, #{time,jdbcType=TIMESTAMP}, ",
        "#{supplieraddress,jdbcType=VARCHAR}, #{state,jdbcType=DECIMAL}, ",
        "#{type,jdbcType=DECIMAL}, #{moneytype,jdbcType=DECIMAL}, ",
        "#{taxstate,jdbcType=DECIMAL}, #{rate,jdbcType=DECIMAL}, ",
        "#{deliver,jdbcType=VARCHAR}, #{touching,jdbcType=VARCHAR}, ",
        "#{section,jdbcType=DECIMAL}, #{checkpeople,jdbcType=DECIMAL}, ",
        "#{remark,jdbcType=VARCHAR}, #{checkstate,jdbcType=DECIMAL}, ",
        "#{column1,jdbcType=VARCHAR}, #{column2,jdbcType=VARCHAR}, ",
        "#{column3,jdbcType=VARCHAR})"
    })
    int insert(Putstorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTSTORAGE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, STORAGEID, SUPPLIERNAME, TIME, SUPPLIERADDRESS, STATE, TYPE, MONEYTYPE, ",
        "TAXSTATE, RATE, DELIVER, TOUCHING, SECTION, CHECKPEOPLE, REMARK, CHECKSTATE, ",
        "COLUMN1, COLUMN2, COLUMN3",
        "from PUTSTORAGE",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="STORAGEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUPPLIERNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="SUPPLIERADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXSTATE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="RATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DELIVER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCHING", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SECTION", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKPEOPLE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COLUMN1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN3", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Putstorage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTSTORAGE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, STORAGEID, SUPPLIERNAME, TIME, SUPPLIERADDRESS, STATE, TYPE, MONEYTYPE, ",
        "TAXSTATE, RATE, DELIVER, TOUCHING, SECTION, CHECKPEOPLE, REMARK, CHECKSTATE, ",
        "COLUMN1, COLUMN2, COLUMN3",
        "from PUTSTORAGE"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="STORAGEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUPPLIERNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="SUPPLIERADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEYTYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXSTATE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="RATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DELIVER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCHING", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SECTION", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKPEOPLE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COLUMN1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMN3", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Putstorage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUTSTORAGE
     *
     * @mbggenerated
     */
    @Update({
        "update PUTSTORAGE",
        "set STORAGEID = #{storageid,jdbcType=VARCHAR},",
          "SUPPLIERNAME = #{suppliername,jdbcType=VARCHAR},",
          "TIME = #{time,jdbcType=TIMESTAMP},",
          "SUPPLIERADDRESS = #{supplieraddress,jdbcType=VARCHAR},",
          "STATE = #{state,jdbcType=DECIMAL},",
          "TYPE = #{type,jdbcType=DECIMAL},",
          "MONEYTYPE = #{moneytype,jdbcType=DECIMAL},",
          "TAXSTATE = #{taxstate,jdbcType=DECIMAL},",
          "RATE = #{rate,jdbcType=DECIMAL},",
          "DELIVER = #{deliver,jdbcType=VARCHAR},",
          "TOUCHING = #{touching,jdbcType=VARCHAR},",
          "SECTION = #{section,jdbcType=DECIMAL},",
          "CHECKPEOPLE = #{checkpeople,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "CHECKSTATE = #{checkstate,jdbcType=DECIMAL},",
          "COLUMN1 = #{column1,jdbcType=VARCHAR},",
          "COLUMN2 = #{column2,jdbcType=VARCHAR},",
          "COLUMN3 = #{column3,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Putstorage record);
}