package com.j5erp.mapper;

import com.j5erp.entity.Quotedetaiols;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface QuotedetaiolsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUOTEDETAIOLS
     *
     * @mbggenerated
     */
    @Delete({
        "delete from QUOTEDETAIOLS",
        "where BILLID = #{billid,jdbcType=VARCHAR}",
          "and LINEMARK = #{linemark,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("billid") String billid, @Param("linemark") Short linemark);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUOTEDETAIOLS
     *
     * @mbggenerated
     */
    @Insert({
        "insert into QUOTEDETAIOLS (BILLID, LINEMARK, ",
        "MATID, MATNAME, ",
        "MATSPEC, MATUNIT, ",
        "NUMS, AGIOAGOPRICE, ",
        "AGIO, PRICE, CESS, ",
        "TAXMONEY, INTAXMONEY, ",
        "MONEY, IFPRESENT, ",
        "FMARK)",
        "values (#{billid,jdbcType=VARCHAR}, #{linemark,jdbcType=DECIMAL}, ",
        "#{matid,jdbcType=VARCHAR}, #{matname,jdbcType=VARCHAR}, ",
        "#{matspec,jdbcType=VARCHAR}, #{matunit,jdbcType=VARCHAR}, ",
        "#{nums,jdbcType=DECIMAL}, #{agioagoprice,jdbcType=DECIMAL}, ",
        "#{agio,jdbcType=DECIMAL}, #{price,jdbcType=DECIMAL}, #{cess,jdbcType=DECIMAL}, ",
        "#{taxmoney,jdbcType=DECIMAL}, #{intaxmoney,jdbcType=DECIMAL}, ",
        "#{money,jdbcType=DECIMAL}, #{ifpresent,jdbcType=DECIMAL}, ",
        "#{fmark,jdbcType=VARCHAR})"
    })
    int insert(Quotedetaiols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUOTEDETAIOLS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BILLID, LINEMARK, MATID, MATNAME, MATSPEC, MATUNIT, NUMS, AGIOAGOPRICE, AGIO, ",
        "PRICE, CESS, TAXMONEY, INTAXMONEY, MONEY, IFPRESENT, FMARK",
        "from QUOTEDETAIOLS",
        "where BILLID = #{billid,jdbcType=VARCHAR}",
          "and LINEMARK = #{linemark,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="BILLID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINEMARK", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="MATID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATSPEC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NUMS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AGIOAGOPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AGIO", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CESS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="INTAXMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="IFPRESENT", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="FMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Quotedetaiols selectByPrimaryKey(@Param("billid") String billid, @Param("linemark") Short linemark);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUOTEDETAIOLS
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BILLID, LINEMARK, MATID, MATNAME, MATSPEC, MATUNIT, NUMS, AGIOAGOPRICE, AGIO, ",
        "PRICE, CESS, TAXMONEY, INTAXMONEY, MONEY, IFPRESENT, FMARK",
        "from QUOTEDETAIOLS"
    })
    @ConstructorArgs({
        @Arg(column="BILLID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINEMARK", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="MATID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATSPEC", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MATUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NUMS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AGIOAGOPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AGIO", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CESS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="INTAXMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="IFPRESENT", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="FMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Quotedetaiols> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUOTEDETAIOLS
     *
     * @mbggenerated
     */
    @Update({
        "update QUOTEDETAIOLS",
        "set MATID = #{matid,jdbcType=VARCHAR},",
          "MATNAME = #{matname,jdbcType=VARCHAR},",
          "MATSPEC = #{matspec,jdbcType=VARCHAR},",
          "MATUNIT = #{matunit,jdbcType=VARCHAR},",
          "NUMS = #{nums,jdbcType=DECIMAL},",
          "AGIOAGOPRICE = #{agioagoprice,jdbcType=DECIMAL},",
          "AGIO = #{agio,jdbcType=DECIMAL},",
          "PRICE = #{price,jdbcType=DECIMAL},",
          "CESS = #{cess,jdbcType=DECIMAL},",
          "TAXMONEY = #{taxmoney,jdbcType=DECIMAL},",
          "INTAXMONEY = #{intaxmoney,jdbcType=DECIMAL},",
          "MONEY = #{money,jdbcType=DECIMAL},",
          "IFPRESENT = #{ifpresent,jdbcType=DECIMAL},",
          "FMARK = #{fmark,jdbcType=VARCHAR}",
        "where BILLID = #{billid,jdbcType=VARCHAR}",
          "and LINEMARK = #{linemark,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Quotedetaiols record);
}