package com.j5erp.mapper;

import com.j5erp.entity.Salescargodetail;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SalescargodetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGODETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SALESCARGODETAIL",
        "where DETAILID = #{detailid,jdbcType=VARCHAR}",
          "and SALEID = #{saleid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("detailid") String detailid, @Param("saleid") String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGODETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SALESCARGODETAIL (DETAILID, SALEID, ",
        "MATTERID, REBATEPRICE, ",
        "BOKENNUMBER, UNITPRICE, ",
        "MONEY, TAXRATE, ",
        "TAXAMOUNT, TAXMONEY, ",
        "GIFT, REMARKS, SOURCEBILL, ",
        "SOURCEID, STATUS, ",
        "PREPARE1, PREPARE2)",
        "values (#{detailid,jdbcType=VARCHAR}, #{saleid,jdbcType=VARCHAR}, ",
        "#{matterid,jdbcType=VARCHAR}, #{rebateprice,jdbcType=VARCHAR}, ",
        "#{bokennumber,jdbcType=VARCHAR}, #{unitprice,jdbcType=VARCHAR}, ",
        "#{money,jdbcType=VARCHAR}, #{taxrate,jdbcType=VARCHAR}, ",
        "#{taxamount,jdbcType=VARCHAR}, #{taxmoney,jdbcType=VARCHAR}, ",
        "#{gift,jdbcType=VARCHAR}, #{remarks,jdbcType=VARCHAR}, #{sourcebill,jdbcType=VARCHAR}, ",
        "#{sourceid,jdbcType=VARCHAR}, #{status,jdbcType=DECIMAL}, ",
        "#{prepare1,jdbcType=VARCHAR}, #{prepare2,jdbcType=VARCHAR})"
    })
    int insert(Salescargodetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGODETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "DETAILID, SALEID, MATTERID, REBATEPRICE, BOKENNUMBER, UNITPRICE, MONEY, TAXRATE, ",
        "TAXAMOUNT, TAXMONEY, GIFT, REMARKS, SOURCEBILL, SOURCEID, STATUS, PREPARE1, ",
        "PREPARE2",
        "from SALESCARGODETAIL",
        "where DETAILID = #{detailid,jdbcType=VARCHAR}",
          "and SALEID = #{saleid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="DETAILID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="SALEID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REBATEPRICE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BOKENNUMBER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UNITPRICE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MONEY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXRATE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXAMOUNT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXMONEY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="GIFT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARKS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SOURCEBILL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SOURCEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Salescargodetail selectByPrimaryKey(@Param("detailid") String detailid, @Param("saleid") String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGODETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "DETAILID, SALEID, MATTERID, REBATEPRICE, BOKENNUMBER, UNITPRICE, MONEY, TAXRATE, ",
        "TAXAMOUNT, TAXMONEY, GIFT, REMARKS, SOURCEBILL, SOURCEID, STATUS, PREPARE1, ",
        "PREPARE2",
        "from SALESCARGODETAIL"
    })
    @ConstructorArgs({
        @Arg(column="DETAILID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="SALEID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REBATEPRICE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BOKENNUMBER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UNITPRICE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MONEY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXRATE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXAMOUNT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXMONEY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="GIFT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARKS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SOURCEBILL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SOURCEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Salescargodetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGODETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update SALESCARGODETAIL",
        "set MATTERID = #{matterid,jdbcType=VARCHAR},",
          "REBATEPRICE = #{rebateprice,jdbcType=VARCHAR},",
          "BOKENNUMBER = #{bokennumber,jdbcType=VARCHAR},",
          "UNITPRICE = #{unitprice,jdbcType=VARCHAR},",
          "MONEY = #{money,jdbcType=VARCHAR},",
          "TAXRATE = #{taxrate,jdbcType=VARCHAR},",
          "TAXAMOUNT = #{taxamount,jdbcType=VARCHAR},",
          "TAXMONEY = #{taxmoney,jdbcType=VARCHAR},",
          "GIFT = #{gift,jdbcType=VARCHAR},",
          "REMARKS = #{remarks,jdbcType=VARCHAR},",
          "SOURCEBILL = #{sourcebill,jdbcType=VARCHAR},",
          "SOURCEID = #{sourceid,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "PREPARE1 = #{prepare1,jdbcType=VARCHAR},",
          "PREPARE2 = #{prepare2,jdbcType=VARCHAR}",
        "where DETAILID = #{detailid,jdbcType=VARCHAR}",
          "and SALEID = #{saleid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Salescargodetail record);
}