package com.j5erp.mapper;

import com.j5erp.entity.SalesReturnDetailed;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SalesReturnDetailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN_DETAILED
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SALES_RETURN_DETAILED",
        "where REJECTEDID = #{rejectedid,jdbcType=VARCHAR}",
          "and LINE = #{line,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("rejectedid") String rejectedid, @Param("line") BigDecimal line);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN_DETAILED
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SALES_RETURN_DETAILED (REJECTEDID, LINE, ",
        "PRODID, PRODNAME, ",
        "PRODSIZE, SUNIT, ",
        "SQUANTITY, OIDPRICE, ",
        "DISCOUNT, PRICE, ",
        "AMOUNT, TAXRATE, ",
        "TAXAMT, AMOUNTWITHTAX, ",
        "ITEMREMARK, TRANTYPE, ",
        "FROMNO)",
        "values (#{rejectedid,jdbcType=VARCHAR}, #{line,jdbcType=DECIMAL}, ",
        "#{prodid,jdbcType=VARCHAR}, #{prodname,jdbcType=VARCHAR}, ",
        "#{prodsize,jdbcType=VARCHAR}, #{sunit,jdbcType=VARCHAR}, ",
        "#{squantity,jdbcType=DECIMAL}, #{oidprice,jdbcType=DECIMAL}, ",
        "#{discount,jdbcType=DECIMAL}, #{price,jdbcType=DECIMAL}, ",
        "#{amount,jdbcType=DECIMAL}, #{taxrate,jdbcType=DECIMAL}, ",
        "#{taxamt,jdbcType=DECIMAL}, #{amountwithtax,jdbcType=DECIMAL}, ",
        "#{itemremark,jdbcType=VARCHAR}, #{trantype,jdbcType=VARCHAR}, ",
        "#{fromno,jdbcType=VARCHAR})"
    })
    int insert(SalesReturnDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN_DETAILED
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "REJECTEDID, LINE, PRODID, PRODNAME, PRODSIZE, SUNIT, SQUANTITY, OIDPRICE, DISCOUNT, ",
        "PRICE, AMOUNT, TAXRATE, TAXAMT, AMOUNTWITHTAX, ITEMREMARK, TRANTYPE, FROMNO",
        "from SALES_RETURN_DETAILED",
        "where REJECTEDID = #{rejectedid,jdbcType=VARCHAR}",
          "and LINE = #{line,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="REJECTEDID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="PRODID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODSIZE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SQUANTITY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="OIDPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DISCOUNT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AMOUNT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXRATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXAMT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AMOUNTWITHTAX", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ITEMREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TRANTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMNO", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    SalesReturnDetailed selectByPrimaryKey(@Param("rejectedid") String rejectedid, @Param("line") BigDecimal line);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN_DETAILED
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "REJECTEDID, LINE, PRODID, PRODNAME, PRODSIZE, SUNIT, SQUANTITY, OIDPRICE, DISCOUNT, ",
        "PRICE, AMOUNT, TAXRATE, TAXAMT, AMOUNTWITHTAX, ITEMREMARK, TRANTYPE, FROMNO",
        "from SALES_RETURN_DETAILED"
    })
    @ConstructorArgs({
        @Arg(column="REJECTEDID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="PRODID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODSIZE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SQUANTITY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="OIDPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DISCOUNT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AMOUNT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXRATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXAMT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AMOUNTWITHTAX", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ITEMREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TRANTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMNO", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<SalesReturnDetailed> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN_DETAILED
     *
     * @mbggenerated
     */
    @Update({
        "update SALES_RETURN_DETAILED",
        "set PRODID = #{prodid,jdbcType=VARCHAR},",
          "PRODNAME = #{prodname,jdbcType=VARCHAR},",
          "PRODSIZE = #{prodsize,jdbcType=VARCHAR},",
          "SUNIT = #{sunit,jdbcType=VARCHAR},",
          "SQUANTITY = #{squantity,jdbcType=DECIMAL},",
          "OIDPRICE = #{oidprice,jdbcType=DECIMAL},",
          "DISCOUNT = #{discount,jdbcType=DECIMAL},",
          "PRICE = #{price,jdbcType=DECIMAL},",
          "AMOUNT = #{amount,jdbcType=DECIMAL},",
          "TAXRATE = #{taxrate,jdbcType=DECIMAL},",
          "TAXAMT = #{taxamt,jdbcType=DECIMAL},",
          "AMOUNTWITHTAX = #{amountwithtax,jdbcType=DECIMAL},",
          "ITEMREMARK = #{itemremark,jdbcType=VARCHAR},",
          "TRANTYPE = #{trantype,jdbcType=VARCHAR},",
          "FROMNO = #{fromno,jdbcType=VARCHAR}",
        "where REJECTEDID = #{rejectedid,jdbcType=VARCHAR}",
          "and LINE = #{line,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(SalesReturnDetailed record);
}