package com.j5erp.mapper;

import com.j5erp.entity.SalesReturn;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SalesReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SALES_RETURN",
        "where REJECTEDID = #{rejectedid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String rejectedid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SALES_RETURN (REJECTEDID, CLIENTID, ",
        "REJECTEDDATE, ADDRESS, ",
        "TAX, REPOSITORY, ",
        "CURRENCY, WAREHOUSEID, ",
        "STAFFID, DEPARTMENTID, ",
        "COMPOSITEID, STATE)",
        "values (#{rejectedid,jdbcType=VARCHAR}, #{clientid,jdbcType=VARCHAR}, ",
        "#{rejecteddate,jdbcType=TIMESTAMP}, #{address,jdbcType=VARCHAR}, ",
        "#{tax,jdbcType=DECIMAL}, #{repository,jdbcType=DECIMAL}, ",
        "#{currency,jdbcType=VARCHAR}, #{warehouseid,jdbcType=VARCHAR}, ",
        "#{staffid,jdbcType=VARCHAR}, #{departmentid,jdbcType=VARCHAR}, ",
        "#{compositeid,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR})"
    })
    int insert(SalesReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "REJECTEDID, CLIENTID, REJECTEDDATE, ADDRESS, TAX, REPOSITORY, CURRENCY, WAREHOUSEID, ",
        "STAFFID, DEPARTMENTID, COMPOSITEID, STATE",
        "from SALES_RETURN",
        "where REJECTEDID = #{rejectedid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="REJECTEDID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CLIENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REJECTEDDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="ADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAX", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REPOSITORY", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CURRENCY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="WAREHOUSEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STAFFID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COMPOSITEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    SalesReturn selectByPrimaryKey(String rejectedid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "REJECTEDID, CLIENTID, REJECTEDDATE, ADDRESS, TAX, REPOSITORY, CURRENCY, WAREHOUSEID, ",
        "STAFFID, DEPARTMENTID, COMPOSITEID, STATE",
        "from SALES_RETURN"
    })
    @ConstructorArgs({
        @Arg(column="REJECTEDID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CLIENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REJECTEDDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="ADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAX", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REPOSITORY", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CURRENCY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="WAREHOUSEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STAFFID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COMPOSITEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<SalesReturn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALES_RETURN
     *
     * @mbggenerated
     */
    @Update({
        "update SALES_RETURN",
        "set CLIENTID = #{clientid,jdbcType=VARCHAR},",
          "REJECTEDDATE = #{rejecteddate,jdbcType=TIMESTAMP},",
          "ADDRESS = #{address,jdbcType=VARCHAR},",
          "TAX = #{tax,jdbcType=DECIMAL},",
          "REPOSITORY = #{repository,jdbcType=DECIMAL},",
          "CURRENCY = #{currency,jdbcType=VARCHAR},",
          "WAREHOUSEID = #{warehouseid,jdbcType=VARCHAR},",
          "STAFFID = #{staffid,jdbcType=VARCHAR},",
          "DEPARTMENTID = #{departmentid,jdbcType=VARCHAR},",
          "COMPOSITEID = #{compositeid,jdbcType=VARCHAR},",
          "STATE = #{state,jdbcType=VARCHAR}",
        "where REJECTEDID = #{rejectedid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SalesReturn record);
}