package com.j5erp.mapper;

import com.j5erp.entity.Salescargo;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SalescargoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGO
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SALESCARGO",
        "where SALEID = #{saleid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGO
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SALESCARGO (SALEID, SALEDATE, ",
        "CID, DEPOTID, ADDRESSID, ",
        "GOLDID, TAX, REMARKS, ",
        "YWID, ZDID, SSID, ",
        "FHID, STATUS, PREPARE1, ",
        "PREPARE2)",
        "values (#{saleid,jdbcType=VARCHAR}, #{saledate,jdbcType=TIMESTAMP}, ",
        "#{cid,jdbcType=VARCHAR}, #{depotid,jdbcType=VARCHAR}, #{addressid,jdbcType=VARCHAR}, ",
        "#{goldid,jdbcType=VARCHAR}, #{tax,jdbcType=VARCHAR}, #{remarks,jdbcType=VARCHAR}, ",
        "#{ywid,jdbcType=VARCHAR}, #{zdid,jdbcType=VARCHAR}, #{ssid,jdbcType=VARCHAR}, ",
        "#{fhid,jdbcType=VARCHAR}, #{status,jdbcType=DECIMAL}, #{prepare1,jdbcType=VARCHAR}, ",
        "#{prepare2,jdbcType=VARCHAR})"
    })
    int insert(Salescargo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SALEID, SALEDATE, CID, DEPOTID, ADDRESSID, GOLDID, TAX, REMARKS, YWID, ZDID, ",
        "SSID, FHID, STATUS, PREPARE1, PREPARE2",
        "from SALESCARGO",
        "where SALEID = #{saleid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="SALEID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="SALEDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="CID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPOTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ADDRESSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="GOLDID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAX", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARKS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="YWID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ZDID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FHID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Salescargo selectByPrimaryKey(String saleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SALEID, SALEDATE, CID, DEPOTID, ADDRESSID, GOLDID, TAX, REMARKS, YWID, ZDID, ",
        "SSID, FHID, STATUS, PREPARE1, PREPARE2",
        "from SALESCARGO"
    })
    @ConstructorArgs({
        @Arg(column="SALEID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="SALEDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="CID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPOTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ADDRESSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="GOLDID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAX", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARKS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="YWID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ZDID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FHID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PREPARE1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PREPARE2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Salescargo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALESCARGO
     *
     * @mbggenerated
     */
    @Update({
        "update SALESCARGO",
        "set SALEDATE = #{saledate,jdbcType=TIMESTAMP},",
          "CID = #{cid,jdbcType=VARCHAR},",
          "DEPOTID = #{depotid,jdbcType=VARCHAR},",
          "ADDRESSID = #{addressid,jdbcType=VARCHAR},",
          "GOLDID = #{goldid,jdbcType=VARCHAR},",
          "TAX = #{tax,jdbcType=VARCHAR},",
          "REMARKS = #{remarks,jdbcType=VARCHAR},",
          "YWID = #{ywid,jdbcType=VARCHAR},",
          "ZDID = #{zdid,jdbcType=VARCHAR},",
          "SSID = #{ssid,jdbcType=VARCHAR},",
          "FHID = #{fhid,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "PREPARE1 = #{prepare1,jdbcType=VARCHAR},",
          "PREPARE2 = #{prepare2,jdbcType=VARCHAR}",
        "where SALEID = #{saleid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Salescargo record);
}