package com.j5erp.mapper;

import com.j5erp.entity.Saleorder;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SaleorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALEORDER
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SALEORDER",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALEORDER
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SALEORDER (ID, CUSID, ",
        "TOADDRESS, SALETYPE, ",
        "ISTAX, ORDERSTATUS, ",
        "ORDERTIME, COINTYPE, ",
        "PAITIES, WANDNAME, ",
        "DANDNAME, CANDNAME, ",
        "MANDNAME, CHECKSTATUS, ",
        "REMARK)",
        "values (#{id,jdbcType=VARCHAR}, #{cusid,jdbcType=VARCHAR}, ",
        "#{toaddress,jdbcType=VARCHAR}, #{saletype,jdbcType=DECIMAL}, ",
        "#{istax,jdbcType=DECIMAL}, #{orderstatus,jdbcType=DECIMAL}, ",
        "#{ordertime,jdbcType=TIMESTAMP}, #{cointype,jdbcType=DECIMAL}, ",
        "#{paities,jdbcType=DECIMAL}, #{wandname,jdbcType=VARCHAR}, ",
        "#{dandname,jdbcType=VARCHAR}, #{candname,jdbcType=VARCHAR}, ",
        "#{mandname,jdbcType=VARCHAR}, #{checkstatus,jdbcType=DECIMAL}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(Saleorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALEORDER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, CUSID, TOADDRESS, SALETYPE, ISTAX, ORDERSTATUS, ORDERTIME, COINTYPE, PAITIES, ",
        "WANDNAME, DANDNAME, CANDNAME, MANDNAME, CHECKSTATUS, REMARK",
        "from SALEORDER",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CUSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALETYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ISTAX", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ORDERSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ORDERTIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="COINTYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PAITIES", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="WANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Saleorder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALEORDER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, CUSID, TOADDRESS, SALETYPE, ISTAX, ORDERSTATUS, ORDERTIME, COINTYPE, PAITIES, ",
        "WANDNAME, DANDNAME, CANDNAME, MANDNAME, CHECKSTATUS, REMARK",
        "from SALEORDER"
    })
    @ConstructorArgs({
        @Arg(column="ID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="CUSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALETYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ISTAX", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ORDERSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ORDERTIME", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="COINTYPE", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PAITIES", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="WANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Saleorder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SALEORDER
     *
     * @mbggenerated
     */
    @Update({
        "update SALEORDER",
        "set CUSID = #{cusid,jdbcType=VARCHAR},",
          "TOADDRESS = #{toaddress,jdbcType=VARCHAR},",
          "SALETYPE = #{saletype,jdbcType=DECIMAL},",
          "ISTAX = #{istax,jdbcType=DECIMAL},",
          "ORDERSTATUS = #{orderstatus,jdbcType=DECIMAL},",
          "ORDERTIME = #{ordertime,jdbcType=TIMESTAMP},",
          "COINTYPE = #{cointype,jdbcType=DECIMAL},",
          "PAITIES = #{paities,jdbcType=DECIMAL},",
          "WANDNAME = #{wandname,jdbcType=VARCHAR},",
          "DANDNAME = #{dandname,jdbcType=VARCHAR},",
          "CANDNAME = #{candname,jdbcType=VARCHAR},",
          "MANDNAME = #{mandname,jdbcType=VARCHAR},",
          "CHECKSTATUS = #{checkstatus,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Saleorder record);
}