package com.j5erp.mapper;

import com.j5erp.entity.Sellquote;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SellquoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SELLQUOTE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SELLQUOTE",
        "where BILLID = #{billid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SELLQUOTE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SELLQUOTE (BILLID, BILLDATE, ",
        "CLIID, CLINAME, ",
        "CLIPLACEID, CLIPLACE, ",
        "PRICEWHETHERTAX, EFFECTDATE, ",
        "BBID, BBEXCHANGE_RATE, ",
        "REMARK, MAKEEMPNAME, ",
        "AUDITINGEMPNAME, EMPNAME, ",
        "DEPID, DEPNAME, ",
        "CHECKSTATUS)",
        "values (#{billid,jdbcType=VARCHAR}, #{billdate,jdbcType=TIMESTAMP}, ",
        "#{cliid,jdbcType=VARCHAR}, #{cliname,jdbcType=VARCHAR}, ",
        "#{cliplaceid,jdbcType=VARCHAR}, #{cliplace,jdbcType=VARCHAR}, ",
        "#{pricewhethertax,jdbcType=DECIMAL}, #{effectdate,jdbcType=TIMESTAMP}, ",
        "#{bbid,jdbcType=VARCHAR}, #{bbexchangeRate,jdbcType=DECIMAL}, ",
        "#{remark,jdbcType=VARCHAR}, #{makeempname,jdbcType=VARCHAR}, ",
        "#{auditingempname,jdbcType=VARCHAR}, #{empname,jdbcType=VARCHAR}, ",
        "#{depid,jdbcType=VARCHAR}, #{depname,jdbcType=VARCHAR}, ",
        "#{checkstatus,jdbcType=DECIMAL})"
    })
    int insert(Sellquote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SELLQUOTE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BILLID, BILLDATE, CLIID, CLINAME, CLIPLACEID, CLIPLACE, PRICEWHETHERTAX, EFFECTDATE, ",
        "BBID, BBEXCHANGE_RATE, REMARK, MAKEEMPNAME, AUDITINGEMPNAME, EMPNAME, DEPID, ",
        "DEPNAME, CHECKSTATUS",
        "from SELLQUOTE",
        "where BILLID = #{billid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="BILLID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BILLDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="CLIID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CLINAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CLIPLACEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CLIPLACE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRICEWHETHERTAX", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="EFFECTDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="BBID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BBEXCHANGE_RATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MAKEEMPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="AUDITINGEMPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EMPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL)
    })
    Sellquote selectByPrimaryKey(String billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SELLQUOTE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "BILLID, BILLDATE, CLIID, CLINAME, CLIPLACEID, CLIPLACE, PRICEWHETHERTAX, EFFECTDATE, ",
        "BBID, BBEXCHANGE_RATE, REMARK, MAKEEMPNAME, AUDITINGEMPNAME, EMPNAME, DEPID, ",
        "DEPNAME, CHECKSTATUS",
        "from SELLQUOTE"
    })
    @ConstructorArgs({
        @Arg(column="BILLID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="BILLDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="CLIID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CLINAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CLIPLACEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CLIPLACE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRICEWHETHERTAX", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="EFFECTDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="BBID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BBEXCHANGE_RATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MAKEEMPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="AUDITINGEMPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EMPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKSTATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL)
    })
    List<Sellquote> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SELLQUOTE
     *
     * @mbggenerated
     */
    @Update({
        "update SELLQUOTE",
        "set BILLDATE = #{billdate,jdbcType=TIMESTAMP},",
          "CLIID = #{cliid,jdbcType=VARCHAR},",
          "CLINAME = #{cliname,jdbcType=VARCHAR},",
          "CLIPLACEID = #{cliplaceid,jdbcType=VARCHAR},",
          "CLIPLACE = #{cliplace,jdbcType=VARCHAR},",
          "PRICEWHETHERTAX = #{pricewhethertax,jdbcType=DECIMAL},",
          "EFFECTDATE = #{effectdate,jdbcType=TIMESTAMP},",
          "BBID = #{bbid,jdbcType=VARCHAR},",
          "BBEXCHANGE_RATE = #{bbexchangeRate,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "MAKEEMPNAME = #{makeempname,jdbcType=VARCHAR},",
          "AUDITINGEMPNAME = #{auditingempname,jdbcType=VARCHAR},",
          "EMPNAME = #{empname,jdbcType=VARCHAR},",
          "DEPID = #{depid,jdbcType=VARCHAR},",
          "DEPNAME = #{depname,jdbcType=VARCHAR},",
          "CHECKSTATUS = #{checkstatus,jdbcType=DECIMAL}",
        "where BILLID = #{billid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Sellquote record);
}