package com.j5erp.mapper;

import com.j5erp.entity.Sharedetail;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SharedetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHAREDETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SHAREDETAIL",
        "where SID = #{sid,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHAREDETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SHAREDETAIL (SID, PID, ",
        "CLOUD, MATERIAL, ",
        "SNAME, MODEL, SMONEY, ",
        "NUMBERS, SPRICE, ",
        "SWEIGHT, SVOLUME, ",
        "SHARES, CHECKSTATUS, ",
        "DEMO1, DEMO2, DEMO3)",
        "values (#{sid,jdbcType=DECIMAL}, #{pid,jdbcType=DECIMAL}, ",
        "#{cloud,jdbcType=DECIMAL}, #{material,jdbcType=DECIMAL}, ",
        "#{sname,jdbcType=VARCHAR}, #{model,jdbcType=VARCHAR}, #{smoney,jdbcType=DECIMAL}, ",
        "#{numbers,jdbcType=DECIMAL}, #{sprice,jdbcType=DECIMAL}, ",
        "#{sweight,jdbcType=DECIMAL}, #{svolume,jdbcType=DECIMAL}, ",
        "#{shares,jdbcType=DECIMAL}, #{checkstatus,jdbcType=DECIMAL}, ",
        "#{demo1,jdbcType=DECIMAL}, #{demo2,jdbcType=VARCHAR}, #{demo3,jdbcType=DECIMAL})"
    })
    int insert(Sharedetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHAREDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SID, PID, CLOUD, MATERIAL, SNAME, MODEL, SMONEY, NUMBERS, SPRICE, SWEIGHT, SVOLUME, ",
        "SHARES, CHECKSTATUS, DEMO1, DEMO2, DEMO3",
        "from SHAREDETAIL",
        "where SID = #{sid,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="SID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="PID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CLOUD", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATERIAL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MODEL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="NUMBERS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SWEIGHT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SVOLUME", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SHARES", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKSTATUS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO1", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEMO3", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    Sharedetail selectByPrimaryKey(BigDecimal sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHAREDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SID, PID, CLOUD, MATERIAL, SNAME, MODEL, SMONEY, NUMBERS, SPRICE, SWEIGHT, SVOLUME, ",
        "SHARES, CHECKSTATUS, DEMO1, DEMO2, DEMO3",
        "from SHAREDETAIL"
    })
    @ConstructorArgs({
        @Arg(column="SID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="PID", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CLOUD", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="MATERIAL", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MODEL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="NUMBERS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SWEIGHT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SVOLUME", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SHARES", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CHECKSTATUS", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO1", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DEMO2", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEMO3", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    List<Sharedetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHAREDETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update SHAREDETAIL",
        "set PID = #{pid,jdbcType=DECIMAL},",
          "CLOUD = #{cloud,jdbcType=DECIMAL},",
          "MATERIAL = #{material,jdbcType=DECIMAL},",
          "SNAME = #{sname,jdbcType=VARCHAR},",
          "MODEL = #{model,jdbcType=VARCHAR},",
          "SMONEY = #{smoney,jdbcType=DECIMAL},",
          "NUMBERS = #{numbers,jdbcType=DECIMAL},",
          "SPRICE = #{sprice,jdbcType=DECIMAL},",
          "SWEIGHT = #{sweight,jdbcType=DECIMAL},",
          "SVOLUME = #{svolume,jdbcType=DECIMAL},",
          "SHARES = #{shares,jdbcType=DECIMAL},",
          "CHECKSTATUS = #{checkstatus,jdbcType=DECIMAL},",
          "DEMO1 = #{demo1,jdbcType=DECIMAL},",
          "DEMO2 = #{demo2,jdbcType=VARCHAR},",
          "DEMO3 = #{demo3,jdbcType=DECIMAL}",
        "where SID = #{sid,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Sharedetail record);
}