package com.j5erp.mapper;

import com.j5erp.entity.Shouldestimatebilldetail;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ShouldestimatebilldetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDESTIMATEBILLDETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SHOULDESTIMATEBILLDETAIL",
        "where EMID = #{emid,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("emid") String emid, @Param("lineno") Long lineno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDESTIMATEBILLDETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SHOULDESTIMATEBILLDETAIL (EMID, LINENO, ",
        "BILLTYPEID, BILLNO, ",
        "ESTIMATENO, LEFTMONEY, ",
        "USEMONEY, DANDNAME)",
        "values (#{emid,jdbcType=VARCHAR}, #{lineno,jdbcType=DECIMAL}, ",
        "#{billtypeid,jdbcType=DECIMAL}, #{billno,jdbcType=VARCHAR}, ",
        "#{estimateno,jdbcType=VARCHAR}, #{leftmoney,jdbcType=DECIMAL}, ",
        "#{usemoney,jdbcType=DECIMAL}, #{dandname,jdbcType=VARCHAR})"
    })
    int insert(Shouldestimatebilldetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDESTIMATEBILLDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "EMID, LINENO, BILLTYPEID, BILLNO, ESTIMATENO, LEFTMONEY, USEMONEY, DANDNAME",
        "from SHOULDESTIMATEBILLDETAIL",
        "where EMID = #{emid,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="EMID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINENO", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLTYPEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ESTIMATENO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LEFTMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="USEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Shouldestimatebilldetail selectByPrimaryKey(@Param("emid") String emid, @Param("lineno") Long lineno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDESTIMATEBILLDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "EMID, LINENO, BILLTYPEID, BILLNO, ESTIMATENO, LEFTMONEY, USEMONEY, DANDNAME",
        "from SHOULDESTIMATEBILLDETAIL"
    })
    @ConstructorArgs({
        @Arg(column="EMID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINENO", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLTYPEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ESTIMATENO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LEFTMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="USEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Shouldestimatebilldetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDESTIMATEBILLDETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update SHOULDESTIMATEBILLDETAIL",
        "set BILLTYPEID = #{billtypeid,jdbcType=DECIMAL},",
          "BILLNO = #{billno,jdbcType=VARCHAR},",
          "ESTIMATENO = #{estimateno,jdbcType=VARCHAR},",
          "LEFTMONEY = #{leftmoney,jdbcType=DECIMAL},",
          "USEMONEY = #{usemoney,jdbcType=DECIMAL},",
          "DANDNAME = #{dandname,jdbcType=VARCHAR}",
        "where EMID = #{emid,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Shouldestimatebilldetail record);
}