package com.j5erp.mapper;

import com.j5erp.entity.Shouldgetmoneybilldetail;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface ShouldgetmoneybilldetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDGETMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from SHOULDGETMONEYBILLDETAIL",
        "where CONTNETID = #{contnetid,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("contnetid") String contnetid, @Param("lineno") Long lineno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDGETMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into SHOULDGETMONEYBILLDETAIL (CONTNETID, LINENO, ",
        "BILLTYPEID, BILLNO, ",
        "BILLDATE, CANDNAME, ",
        "DANDNAME, HANDNAME, ",
        "CTYPEANDNAME, SOURCEMONEY, ",
        "DISCOUNTMONEY, USEMONEY, ",
        "USESMONEY)",
        "values (#{contnetid,jdbcType=VARCHAR}, #{lineno,jdbcType=DECIMAL}, ",
        "#{billtypeid,jdbcType=DECIMAL}, #{billno,jdbcType=VARCHAR}, ",
        "#{billdate,jdbcType=TIMESTAMP}, #{candname,jdbcType=VARCHAR}, ",
        "#{dandname,jdbcType=VARCHAR}, #{handname,jdbcType=VARCHAR}, ",
        "#{ctypeandname,jdbcType=VARCHAR}, #{sourcemoney,jdbcType=DECIMAL}, ",
        "#{discountmoney,jdbcType=DECIMAL}, #{usemoney,jdbcType=DECIMAL}, ",
        "#{usesmoney,jdbcType=DECIMAL})"
    })
    int insert(Shouldgetmoneybilldetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDGETMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "CONTNETID, LINENO, BILLTYPEID, BILLNO, BILLDATE, CANDNAME, DANDNAME, HANDNAME, ",
        "CTYPEANDNAME, SOURCEMONEY, DISCOUNTMONEY, USEMONEY, USESMONEY",
        "from SHOULDGETMONEYBILLDETAIL",
        "where CONTNETID = #{contnetid,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="CONTNETID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINENO", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLTYPEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BILLDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="CANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CTYPEANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SOURCEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DISCOUNTMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="USEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="USESMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    Shouldgetmoneybilldetail selectByPrimaryKey(@Param("contnetid") String contnetid, @Param("lineno") Long lineno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDGETMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "CONTNETID, LINENO, BILLTYPEID, BILLNO, BILLDATE, CANDNAME, DANDNAME, HANDNAME, ",
        "CTYPEANDNAME, SOURCEMONEY, DISCOUNTMONEY, USEMONEY, USESMONEY",
        "from SHOULDGETMONEYBILLDETAIL"
    })
    @ConstructorArgs({
        @Arg(column="CONTNETID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINENO", javaType=Long.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLTYPEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BILLDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="CANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CTYPEANDNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SOURCEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="DISCOUNTMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="USEMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="USESMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    List<Shouldgetmoneybilldetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHOULDGETMONEYBILLDETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update SHOULDGETMONEYBILLDETAIL",
        "set BILLTYPEID = #{billtypeid,jdbcType=DECIMAL},",
          "BILLNO = #{billno,jdbcType=VARCHAR},",
          "BILLDATE = #{billdate,jdbcType=TIMESTAMP},",
          "CANDNAME = #{candname,jdbcType=VARCHAR},",
          "DANDNAME = #{dandname,jdbcType=VARCHAR},",
          "HANDNAME = #{handname,jdbcType=VARCHAR},",
          "CTYPEANDNAME = #{ctypeandname,jdbcType=VARCHAR},",
          "SOURCEMONEY = #{sourcemoney,jdbcType=DECIMAL},",
          "DISCOUNTMONEY = #{discountmoney,jdbcType=DECIMAL},",
          "USEMONEY = #{usemoney,jdbcType=DECIMAL},",
          "USESMONEY = #{usesmoney,jdbcType=DECIMAL}",
        "where CONTNETID = #{contnetid,jdbcType=VARCHAR}",
          "and LINENO = #{lineno,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Shouldgetmoneybilldetail record);
}