package com.j5erp.mapper;

import com.j5erp.entity.StaffMasterFile;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface StaffMasterFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_MASTER_FILE
     *
     * @mbggenerated
     */
    @Delete({
        "delete from STAFF_MASTER_FILE",
        "where STAFFID = #{staffid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String staffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_MASTER_FILE
     *
     * @mbggenerated
     */
    @Insert({
        "insert into STAFF_MASTER_FILE (STAFFID, PWD, ",
        "DEPARTMENTID, STAFFNAME, ",
        "SEX, STAFFEN_NAME, ",
        "IDCARD, BIRTHDAY, ",
        "POLITICS_STATUS, MARRIAGE_STATUS, ",
        "INDUCTION_DATE, BLOOD_GROUP, ",
        "REGULAR_WORKER_DATE, NATIVE_PLACE, ",
        "QUALIFYING_PERIOD, NATIONALITY, ",
        "LEAVE_OFFICE_DATE, NATION, ",
        "TECHNICAL_TITLE, CN_DUTIES, ",
        "EN_DUTIES, LINKPOSTCODE, ",
        "LINKADDRESS, LINKPHONE, ",
        "PHONE, HIGHEST_EDUCATION, ",
        "EXPIRATION_DATE, BACHELOR_DEGREE, ",
        "ARRIVAL_DATE, GRADUATE, ",
        "PASSPORT_NUMBER, COLLEGE_MAJOR, ",
        "PACT_START_DATE, EXPERIENCES_DATE, ",
        "EMAIL, CONTRACT_PERIOD, ",
        "NOW_PHONE, DOMICILE_PHONE, ",
        "NOW_ADDRESS, HOME_PHONE, ",
        "HOME_ADDRESS, REMARK, ",
        "STANDBY_1, STANDBY_2)",
        "values (#{staffid,jdbcType=VARCHAR}, #{pwd,jdbcType=VARCHAR}, ",
        "#{departmentid,jdbcType=VARCHAR}, #{staffname,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=VARCHAR}, #{staffenName,jdbcType=VARCHAR}, ",
        "#{idcard,jdbcType=VARCHAR}, #{birthday,jdbcType=TIMESTAMP}, ",
        "#{politicsStatus,jdbcType=VARCHAR}, #{marriageStatus,jdbcType=DECIMAL}, ",
        "#{inductionDate,jdbcType=TIMESTAMP}, #{bloodGroup,jdbcType=VARCHAR}, ",
        "#{regularWorkerDate,jdbcType=TIMESTAMP}, #{nativePlace,jdbcType=VARCHAR}, ",
        "#{qualifyingPeriod,jdbcType=VARCHAR}, #{nationality,jdbcType=VARCHAR}, ",
        "#{leaveOfficeDate,jdbcType=TIMESTAMP}, #{nation,jdbcType=VARCHAR}, ",
        "#{technicalTitle,jdbcType=VARCHAR}, #{cnDuties,jdbcType=VARCHAR}, ",
        "#{enDuties,jdbcType=VARCHAR}, #{linkpostcode,jdbcType=VARCHAR}, ",
        "#{linkaddress,jdbcType=VARCHAR}, #{linkphone,jdbcType=VARCHAR}, ",
        "#{phone,jdbcType=VARCHAR}, #{highestEducation,jdbcType=VARCHAR}, ",
        "#{expirationDate,jdbcType=TIMESTAMP}, #{bachelorDegree,jdbcType=VARCHAR}, ",
        "#{arrivalDate,jdbcType=TIMESTAMP}, #{graduate,jdbcType=VARCHAR}, ",
        "#{passportNumber,jdbcType=VARCHAR}, #{collegeMajor,jdbcType=VARCHAR}, ",
        "#{pactStartDate,jdbcType=TIMESTAMP}, #{experiencesDate,jdbcType=TIMESTAMP}, ",
        "#{email,jdbcType=VARCHAR}, #{contractPeriod,jdbcType=TIMESTAMP}, ",
        "#{nowPhone,jdbcType=VARCHAR}, #{domicilePhone,jdbcType=VARCHAR}, ",
        "#{nowAddress,jdbcType=VARCHAR}, #{homePhone,jdbcType=VARCHAR}, ",
        "#{homeAddress,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{standby1,jdbcType=VARCHAR}, #{standby2,jdbcType=VARCHAR})"
    })
    int insert(StaffMasterFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_MASTER_FILE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "STAFFID, PWD, DEPARTMENTID, STAFFNAME, SEX, STAFFEN_NAME, IDCARD, BIRTHDAY, ",
        "POLITICS_STATUS, MARRIAGE_STATUS, INDUCTION_DATE, BLOOD_GROUP, REGULAR_WORKER_DATE, ",
        "NATIVE_PLACE, QUALIFYING_PERIOD, NATIONALITY, LEAVE_OFFICE_DATE, NATION, TECHNICAL_TITLE, ",
        "CN_DUTIES, EN_DUTIES, LINKPOSTCODE, LINKADDRESS, LINKPHONE, PHONE, HIGHEST_EDUCATION, ",
        "EXPIRATION_DATE, BACHELOR_DEGREE, ARRIVAL_DATE, GRADUATE, PASSPORT_NUMBER, COLLEGE_MAJOR, ",
        "PACT_START_DATE, EXPERIENCES_DATE, EMAIL, CONTRACT_PERIOD, NOW_PHONE, DOMICILE_PHONE, ",
        "NOW_ADDRESS, HOME_PHONE, HOME_ADDRESS, REMARK, STANDBY_1, STANDBY_2",
        "from STAFF_MASTER_FILE",
        "where STAFFID = #{staffid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="STAFFID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PWD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STAFFNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SEX", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STAFFEN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="IDCARD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BIRTHDAY", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="POLITICS_STATUS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MARRIAGE_STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="INDUCTION_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="BLOOD_GROUP", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REGULAR_WORKER_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="NATIVE_PLACE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUALIFYING_PERIOD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NATIONALITY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LEAVE_OFFICE_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="NATION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TECHNICAL_TITLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CN_DUTIES", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EN_DUTIES", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LINKPOSTCODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LINKADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LINKPHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HIGHEST_EDUCATION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EXPIRATION_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="BACHELOR_DEGREE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ARRIVAL_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="GRADUATE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PASSPORT_NUMBER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLLEGE_MAJOR", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PACT_START_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="EXPERIENCES_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="EMAIL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CONTRACT_PERIOD", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="NOW_PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DOMICILE_PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NOW_ADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HOME_PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HOME_ADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    StaffMasterFile selectByPrimaryKey(String staffid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_MASTER_FILE
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "STAFFID, PWD, DEPARTMENTID, STAFFNAME, SEX, STAFFEN_NAME, IDCARD, BIRTHDAY, ",
        "POLITICS_STATUS, MARRIAGE_STATUS, INDUCTION_DATE, BLOOD_GROUP, REGULAR_WORKER_DATE, ",
        "NATIVE_PLACE, QUALIFYING_PERIOD, NATIONALITY, LEAVE_OFFICE_DATE, NATION, TECHNICAL_TITLE, ",
        "CN_DUTIES, EN_DUTIES, LINKPOSTCODE, LINKADDRESS, LINKPHONE, PHONE, HIGHEST_EDUCATION, ",
        "EXPIRATION_DATE, BACHELOR_DEGREE, ARRIVAL_DATE, GRADUATE, PASSPORT_NUMBER, COLLEGE_MAJOR, ",
        "PACT_START_DATE, EXPERIENCES_DATE, EMAIL, CONTRACT_PERIOD, NOW_PHONE, DOMICILE_PHONE, ",
        "NOW_ADDRESS, HOME_PHONE, HOME_ADDRESS, REMARK, STANDBY_1, STANDBY_2",
        "from STAFF_MASTER_FILE"
    })
    @ConstructorArgs({
        @Arg(column="STAFFID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PWD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STAFFNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SEX", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STAFFEN_NAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="IDCARD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BIRTHDAY", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="POLITICS_STATUS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="MARRIAGE_STATUS", javaType=Short.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="INDUCTION_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="BLOOD_GROUP", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REGULAR_WORKER_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="NATIVE_PLACE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUALIFYING_PERIOD", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NATIONALITY", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LEAVE_OFFICE_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="NATION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TECHNICAL_TITLE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CN_DUTIES", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EN_DUTIES", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LINKPOSTCODE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LINKADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="LINKPHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HIGHEST_EDUCATION", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="EXPIRATION_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="BACHELOR_DEGREE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ARRIVAL_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="GRADUATE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PASSPORT_NUMBER", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLLEGE_MAJOR", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PACT_START_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="EXPERIENCES_DATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="EMAIL", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CONTRACT_PERIOD", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="NOW_PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DOMICILE_PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="NOW_ADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HOME_PHONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="HOME_ADDRESS", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_1", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STANDBY_2", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<StaffMasterFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAFF_MASTER_FILE
     *
     * @mbggenerated
     */
    @Update({
        "update STAFF_MASTER_FILE",
        "set PWD = #{pwd,jdbcType=VARCHAR},",
          "DEPARTMENTID = #{departmentid,jdbcType=VARCHAR},",
          "STAFFNAME = #{staffname,jdbcType=VARCHAR},",
          "SEX = #{sex,jdbcType=VARCHAR},",
          "STAFFEN_NAME = #{staffenName,jdbcType=VARCHAR},",
          "IDCARD = #{idcard,jdbcType=VARCHAR},",
          "BIRTHDAY = #{birthday,jdbcType=TIMESTAMP},",
          "POLITICS_STATUS = #{politicsStatus,jdbcType=VARCHAR},",
          "MARRIAGE_STATUS = #{marriageStatus,jdbcType=DECIMAL},",
          "INDUCTION_DATE = #{inductionDate,jdbcType=TIMESTAMP},",
          "BLOOD_GROUP = #{bloodGroup,jdbcType=VARCHAR},",
          "REGULAR_WORKER_DATE = #{regularWorkerDate,jdbcType=TIMESTAMP},",
          "NATIVE_PLACE = #{nativePlace,jdbcType=VARCHAR},",
          "QUALIFYING_PERIOD = #{qualifyingPeriod,jdbcType=VARCHAR},",
          "NATIONALITY = #{nationality,jdbcType=VARCHAR},",
          "LEAVE_OFFICE_DATE = #{leaveOfficeDate,jdbcType=TIMESTAMP},",
          "NATION = #{nation,jdbcType=VARCHAR},",
          "TECHNICAL_TITLE = #{technicalTitle,jdbcType=VARCHAR},",
          "CN_DUTIES = #{cnDuties,jdbcType=VARCHAR},",
          "EN_DUTIES = #{enDuties,jdbcType=VARCHAR},",
          "LINKPOSTCODE = #{linkpostcode,jdbcType=VARCHAR},",
          "LINKADDRESS = #{linkaddress,jdbcType=VARCHAR},",
          "LINKPHONE = #{linkphone,jdbcType=VARCHAR},",
          "PHONE = #{phone,jdbcType=VARCHAR},",
          "HIGHEST_EDUCATION = #{highestEducation,jdbcType=VARCHAR},",
          "EXPIRATION_DATE = #{expirationDate,jdbcType=TIMESTAMP},",
          "BACHELOR_DEGREE = #{bachelorDegree,jdbcType=VARCHAR},",
          "ARRIVAL_DATE = #{arrivalDate,jdbcType=TIMESTAMP},",
          "GRADUATE = #{graduate,jdbcType=VARCHAR},",
          "PASSPORT_NUMBER = #{passportNumber,jdbcType=VARCHAR},",
          "COLLEGE_MAJOR = #{collegeMajor,jdbcType=VARCHAR},",
          "PACT_START_DATE = #{pactStartDate,jdbcType=TIMESTAMP},",
          "EXPERIENCES_DATE = #{experiencesDate,jdbcType=TIMESTAMP},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "CONTRACT_PERIOD = #{contractPeriod,jdbcType=TIMESTAMP},",
          "NOW_PHONE = #{nowPhone,jdbcType=VARCHAR},",
          "DOMICILE_PHONE = #{domicilePhone,jdbcType=VARCHAR},",
          "NOW_ADDRESS = #{nowAddress,jdbcType=VARCHAR},",
          "HOME_PHONE = #{homePhone,jdbcType=VARCHAR},",
          "HOME_ADDRESS = #{homeAddress,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "STANDBY_1 = #{standby1,jdbcType=VARCHAR},",
          "STANDBY_2 = #{standby2,jdbcType=VARCHAR}",
        "where STAFFID = #{staffid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(StaffMasterFile record);
}