package com.j5erp.mapper;

import com.j5erp.entity.TCgthdetail;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TCgthdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHDETAIL
     *
     * @mbggenerated
     */
    @Delete({
        "delete from T_CGTHDETAIL",
        "where T_DETAILID = #{tDetailid,jdbcType=VARCHAR}",
          "and LINEID = #{lineid,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(@Param("tDetailid") String tDetailid, @Param("lineid") Short lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHDETAIL
     *
     * @mbggenerated
     */
    @Insert({
        "insert into T_CGTHDETAIL (T_DETAILID, LINEID, ",
        "MATTERID, QUANTUM, ",
        "UNITPRICE, SUMMONEY, ",
        "TAXRATE, TAXMONEY, ",
        "SUMTAX, REMARK, ",
        "SUPPLIERID, PAYMENTDATE, ",
        "PAYMENTTERM, TRANTYPE, ",
        "FROMNO, COLUMNONE, ",
        "COLUMNTWO)",
        "values (#{tDetailid,jdbcType=VARCHAR}, #{lineid,jdbcType=DECIMAL}, ",
        "#{matterid,jdbcType=VARCHAR}, #{quantum,jdbcType=DECIMAL}, ",
        "#{unitprice,jdbcType=DECIMAL}, #{summoney,jdbcType=DECIMAL}, ",
        "#{taxrate,jdbcType=VARCHAR}, #{taxmoney,jdbcType=DECIMAL}, ",
        "#{sumtax,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR}, ",
        "#{supplierid,jdbcType=VARCHAR}, #{paymentdate,jdbcType=TIMESTAMP}, ",
        "#{paymentterm,jdbcType=VARCHAR}, #{trantype,jdbcType=VARCHAR}, ",
        "#{fromno,jdbcType=VARCHAR}, #{columnone,jdbcType=VARCHAR}, ",
        "#{columntwo,jdbcType=VARCHAR})"
    })
    int insert(TCgthdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "T_DETAILID, LINEID, MATTERID, QUANTUM, UNITPRICE, SUMMONEY, TAXRATE, TAXMONEY, ",
        "SUMTAX, REMARK, SUPPLIERID, PAYMENTDATE, PAYMENTTERM, TRANTYPE, FROMNO, COLUMNONE, ",
        "COLUMNTWO",
        "from T_CGTHDETAIL",
        "where T_DETAILID = #{tDetailid,jdbcType=VARCHAR}",
          "and LINEID = #{lineid,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="T_DETAILID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUANTUM", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="UNITPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SUMMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXRATE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SUMTAX", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUPPLIERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PAYMENTDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="PAYMENTTERM", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TRANTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNTWO", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TCgthdetail selectByPrimaryKey(@Param("tDetailid") String tDetailid, @Param("lineid") Short lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHDETAIL
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "T_DETAILID, LINEID, MATTERID, QUANTUM, UNITPRICE, SUMMONEY, TAXRATE, TAXMONEY, ",
        "SUMTAX, REMARK, SUPPLIERID, PAYMENTDATE, PAYMENTTERM, TRANTYPE, FROMNO, COLUMNONE, ",
        "COLUMNTWO",
        "from T_CGTHDETAIL"
    })
    @ConstructorArgs({
        @Arg(column="T_DETAILID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="LINEID", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="MATTERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="QUANTUM", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="UNITPRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SUMMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="TAXRATE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TAXMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="SUMTAX", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="REMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SUPPLIERID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PAYMENTDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="PAYMENTTERM", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TRANTYPE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="FROMNO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNTWO", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TCgthdetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHDETAIL
     *
     * @mbggenerated
     */
    @Update({
        "update T_CGTHDETAIL",
        "set MATTERID = #{matterid,jdbcType=VARCHAR},",
          "QUANTUM = #{quantum,jdbcType=DECIMAL},",
          "UNITPRICE = #{unitprice,jdbcType=DECIMAL},",
          "SUMMONEY = #{summoney,jdbcType=DECIMAL},",
          "TAXRATE = #{taxrate,jdbcType=VARCHAR},",
          "TAXMONEY = #{taxmoney,jdbcType=DECIMAL},",
          "SUMTAX = #{sumtax,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "SUPPLIERID = #{supplierid,jdbcType=VARCHAR},",
          "PAYMENTDATE = #{paymentdate,jdbcType=TIMESTAMP},",
          "PAYMENTTERM = #{paymentterm,jdbcType=VARCHAR},",
          "TRANTYPE = #{trantype,jdbcType=VARCHAR},",
          "FROMNO = #{fromno,jdbcType=VARCHAR},",
          "COLUMNONE = #{columnone,jdbcType=VARCHAR},",
          "COLUMNTWO = #{columntwo,jdbcType=VARCHAR}",
        "where T_DETAILID = #{tDetailid,jdbcType=VARCHAR}",
          "and LINEID = #{lineid,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TCgthdetail record);
}