package com.j5erp.mapper;

import com.j5erp.entity.TCgthmaster;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TCgthmasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHMASTER
     *
     * @mbggenerated
     */
    @Delete({
        "delete from T_CGTHMASTER",
        "where T_CGGTHID = #{tCggthid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String tCggthid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHMASTER
     *
     * @mbggenerated
     */
    @Insert({
        "insert into T_CGTHMASTER (T_CGGTHID, T_CGTHDATE, ",
        "T_GYSID, WAREHOUSEID, ",
        "SALESMAN, DEPARTMENTID, ",
        "CURRENCYID, TOUCHPERSON, ",
        "CHECKPERSON, BOOLPUT, ",
        "BOOLTAX, COLUMNONE, ",
        "COLUMNTWO, PERMITTER, ",
        "EXCHRATE)",
        "values (#{tCggthid,jdbcType=VARCHAR}, #{tCgthdate,jdbcType=TIMESTAMP}, ",
        "#{tGysid,jdbcType=VARCHAR}, #{warehouseid,jdbcType=VARCHAR}, ",
        "#{salesman,jdbcType=VARCHAR}, #{departmentid,jdbcType=VARCHAR}, ",
        "#{currencyid,jdbcType=VARCHAR}, #{touchperson,jdbcType=VARCHAR}, ",
        "#{checkperson,jdbcType=VARCHAR}, #{boolput,jdbcType=CHAR}, ",
        "#{booltax,jdbcType=CHAR}, #{columnone,jdbcType=VARCHAR}, ",
        "#{columntwo,jdbcType=VARCHAR}, #{permitter,jdbcType=CHAR}, ",
        "#{exchrate,jdbcType=DECIMAL})"
    })
    int insert(TCgthmaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHMASTER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "T_CGGTHID, T_CGTHDATE, T_GYSID, WAREHOUSEID, SALESMAN, DEPARTMENTID, CURRENCYID, ",
        "TOUCHPERSON, CHECKPERSON, BOOLPUT, BOOLTAX, COLUMNONE, COLUMNTWO, PERMITTER, ",
        "EXCHRATE",
        "from T_CGTHMASTER",
        "where T_CGGTHID = #{tCggthid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="T_CGGTHID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="T_CGTHDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="T_GYSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="WAREHOUSEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALESMAN", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCYID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCHPERSON", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKPERSON", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BOOLPUT", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="BOOLTAX", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="COLUMNONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNTWO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PERMITTER", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="EXCHRATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    TCgthmaster selectByPrimaryKey(String tCggthid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHMASTER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "T_CGGTHID, T_CGTHDATE, T_GYSID, WAREHOUSEID, SALESMAN, DEPARTMENTID, CURRENCYID, ",
        "TOUCHPERSON, CHECKPERSON, BOOLPUT, BOOLTAX, COLUMNONE, COLUMNTWO, PERMITTER, ",
        "EXCHRATE",
        "from T_CGTHMASTER"
    })
    @ConstructorArgs({
        @Arg(column="T_CGGTHID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="T_CGTHDATE", javaType=Date.class, jdbcType=JdbcType.TIMESTAMP),
        @Arg(column="T_GYSID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="WAREHOUSEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SALESMAN", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="DEPARTMENTID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCYID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="TOUCHPERSON", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CHECKPERSON", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="BOOLPUT", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="BOOLTAX", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="COLUMNONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNTWO", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PERMITTER", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="EXCHRATE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL)
    })
    List<TCgthmaster> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CGTHMASTER
     *
     * @mbggenerated
     */
    @Update({
        "update T_CGTHMASTER",
        "set T_CGTHDATE = #{tCgthdate,jdbcType=TIMESTAMP},",
          "T_GYSID = #{tGysid,jdbcType=VARCHAR},",
          "WAREHOUSEID = #{warehouseid,jdbcType=VARCHAR},",
          "SALESMAN = #{salesman,jdbcType=VARCHAR},",
          "DEPARTMENTID = #{departmentid,jdbcType=VARCHAR},",
          "CURRENCYID = #{currencyid,jdbcType=VARCHAR},",
          "TOUCHPERSON = #{touchperson,jdbcType=VARCHAR},",
          "CHECKPERSON = #{checkperson,jdbcType=VARCHAR},",
          "BOOLPUT = #{boolput,jdbcType=CHAR},",
          "BOOLTAX = #{booltax,jdbcType=CHAR},",
          "COLUMNONE = #{columnone,jdbcType=VARCHAR},",
          "COLUMNTWO = #{columntwo,jdbcType=VARCHAR},",
          "PERMITTER = #{permitter,jdbcType=CHAR},",
          "EXCHRATE = #{exchrate,jdbcType=DECIMAL}",
        "where T_CGGTHID = #{tCggthid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TCgthmaster record);
}