package com.j5erp.mapper;

import com.j5erp.entity.Tiaozhengfangshileixingbiao;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TiaozhengfangshileixingbiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOZHENGFANGSHILEIXINGBIAO
     *
     * @mbggenerated
     */
    @Delete({
        "delete from TIAOZHENGFANGSHILEIXINGBIAO",
        "where LID = #{lid,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Short lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOZHENGFANGSHILEIXINGBIAO
     *
     * @mbggenerated
     */
    @Insert({
        "insert into TIAOZHENGFANGSHILEIXINGBIAO (LID, BADIUSTSTYLE)",
        "values (#{lid,jdbcType=DECIMAL}, #{badiuststyle,jdbcType=VARCHAR})"
    })
    int insert(Tiaozhengfangshileixingbiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOZHENGFANGSHILEIXINGBIAO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "LID, BADIUSTSTYLE",
        "from TIAOZHENGFANGSHILEIXINGBIAO",
        "where LID = #{lid,jdbcType=DECIMAL}"
    })
    @ConstructorArgs({
        @Arg(column="LID", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BADIUSTSTYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Tiaozhengfangshileixingbiao selectByPrimaryKey(Short lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOZHENGFANGSHILEIXINGBIAO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "LID, BADIUSTSTYLE",
        "from TIAOZHENGFANGSHILEIXINGBIAO"
    })
    @ConstructorArgs({
        @Arg(column="LID", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BADIUSTSTYLE", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Tiaozhengfangshileixingbiao> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOZHENGFANGSHILEIXINGBIAO
     *
     * @mbggenerated
     */
    @Update({
        "update TIAOZHENGFANGSHILEIXINGBIAO",
        "set BADIUSTSTYLE = #{badiuststyle,jdbcType=VARCHAR}",
        "where LID = #{lid,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(Tiaozhengfangshileixingbiao record);
}