package com.j5erp.mapper;

import com.j5erp.entity.Tiaojiadanxiangbiao;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TiaojiadanxiangbiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANXIANGBIAO
     *
     * @mbggenerated
     */
    @Delete({
        "delete from TIAOJIADANXIANGBIAO",
        "where SERNO = #{serno,jdbcType=DECIMAL}",
          "and BILLNO = #{billno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("serno") Short serno, @Param("billno") String billno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANXIANGBIAO
     *
     * @mbggenerated
     */
    @Insert({
        "insert into TIAOJIADANXIANGBIAO (SERNO, BILLNO, ",
        "PRODID, PRODNAME, ",
        "PRODSIZE, UNIT, ",
        "CURQTY, LCOSTAVG, ",
        "PRICE, AMOUNT, ITEMREMARK)",
        "values (#{serno,jdbcType=DECIMAL}, #{billno,jdbcType=VARCHAR}, ",
        "#{prodid,jdbcType=VARCHAR}, #{prodname,jdbcType=VARCHAR}, ",
        "#{prodsize,jdbcType=VARCHAR}, #{unit,jdbcType=VARCHAR}, ",
        "#{curqty,jdbcType=DECIMAL}, #{lcostavg,jdbcType=DECIMAL}, ",
        "#{price,jdbcType=DECIMAL}, #{amount,jdbcType=DECIMAL}, #{itemremark,jdbcType=VARCHAR})"
    })
    int insert(Tiaojiadanxiangbiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANXIANGBIAO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SERNO, BILLNO, PRODID, PRODNAME, PRODSIZE, UNIT, CURQTY, LCOSTAVG, PRICE, AMOUNT, ",
        "ITEMREMARK",
        "from TIAOJIADANXIANGBIAO",
        "where SERNO = #{serno,jdbcType=DECIMAL}",
          "and BILLNO = #{billno,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="SERNO", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PRODID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODSIZE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURQTY", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="LCOSTAVG", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AMOUNT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ITEMREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    Tiaojiadanxiangbiao selectByPrimaryKey(@Param("serno") Short serno, @Param("billno") String billno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANXIANGBIAO
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SERNO, BILLNO, PRODID, PRODNAME, PRODSIZE, UNIT, CURQTY, LCOSTAVG, PRICE, AMOUNT, ",
        "ITEMREMARK",
        "from TIAOJIADANXIANGBIAO"
    })
    @ConstructorArgs({
        @Arg(column="SERNO", javaType=Short.class, jdbcType=JdbcType.DECIMAL, id=true),
        @Arg(column="BILLNO", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="PRODID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PRODSIZE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="UNIT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURQTY", javaType=Long.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="LCOSTAVG", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="AMOUNT", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="ITEMREMARK", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<Tiaojiadanxiangbiao> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TIAOJIADANXIANGBIAO
     *
     * @mbggenerated
     */
    @Update({
        "update TIAOJIADANXIANGBIAO",
        "set PRODID = #{prodid,jdbcType=VARCHAR},",
          "PRODNAME = #{prodname,jdbcType=VARCHAR},",
          "PRODSIZE = #{prodsize,jdbcType=VARCHAR},",
          "UNIT = #{unit,jdbcType=VARCHAR},",
          "CURQTY = #{curqty,jdbcType=DECIMAL},",
          "LCOSTAVG = #{lcostavg,jdbcType=DECIMAL},",
          "PRICE = #{price,jdbcType=DECIMAL},",
          "AMOUNT = #{amount,jdbcType=DECIMAL},",
          "ITEMREMARK = #{itemremark,jdbcType=VARCHAR}",
        "where SERNO = #{serno,jdbcType=DECIMAL}",
          "and BILLNO = #{billno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Tiaojiadanxiangbiao record);
}