package com.j5erp.mapper;

import com.j5erp.entity.TSuppliermaster;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Arg;
import org.apache.ibatis.annotations.ConstructorArgs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TSuppliermasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUPPLIERMASTER
     *
     * @mbggenerated
     */
    @Delete({
        "delete from T_SUPPLIERMASTER",
        "where SUPPLIERID = #{supplierid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String supplierid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUPPLIERMASTER
     *
     * @mbggenerated
     */
    @Insert({
        "insert into T_SUPPLIERMASTER (SUPPLIERID, SUPTYPEID, ",
        "ADDRESSNAME, CURRENCYID, ",
        "PURCHASEMAN, SURPLUSMONEY, ",
        "PAYTERM, CREDITRAT, ",
        "STARTADVRECV, STARTRECEIVABLE, ",
        "CURADVRECV, CURRECEIVABLE, ",
        "PRICEOFTAX, AMOUNTQUOTA, ",
        "COLUMNONE, COLUMNTWO)",
        "values (#{supplierid,jdbcType=VARCHAR}, #{suptypeid,jdbcType=VARCHAR}, ",
        "#{addressname,jdbcType=VARCHAR}, #{currencyid,jdbcType=VARCHAR}, ",
        "#{purchaseman,jdbcType=VARCHAR}, #{surplusmoney,jdbcType=DECIMAL}, ",
        "#{payterm,jdbcType=VARCHAR}, #{creditrat,jdbcType=VARCHAR}, ",
        "#{startadvrecv,jdbcType=DECIMAL}, #{startreceivable,jdbcType=DECIMAL}, ",
        "#{curadvrecv,jdbcType=DECIMAL}, #{curreceivable,jdbcType=DECIMAL}, ",
        "#{priceoftax,jdbcType=CHAR}, #{amountquota,jdbcType=DECIMAL}, ",
        "#{columnone,jdbcType=VARCHAR}, #{columntwo,jdbcType=VARCHAR})"
    })
    int insert(TSuppliermaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUPPLIERMASTER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SUPPLIERID, SUPTYPEID, ADDRESSNAME, CURRENCYID, PURCHASEMAN, SURPLUSMONEY, PAYTERM, ",
        "CREDITRAT, STARTADVRECV, STARTRECEIVABLE, CURADVRECV, CURRECEIVABLE, PRICEOFTAX, ",
        "AMOUNTQUOTA, COLUMNONE, COLUMNTWO",
        "from T_SUPPLIERMASTER",
        "where SUPPLIERID = #{supplierid,jdbcType=VARCHAR}"
    })
    @ConstructorArgs({
        @Arg(column="SUPPLIERID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="SUPTYPEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ADDRESSNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCYID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PURCHASEMAN", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SURPLUSMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PAYTERM", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREDITRAT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STARTADVRECV", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STARTRECEIVABLE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CURADVRECV", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CURRECEIVABLE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICEOFTAX", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="AMOUNTQUOTA", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COLUMNONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNTWO", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    TSuppliermaster selectByPrimaryKey(String supplierid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUPPLIERMASTER
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "SUPPLIERID, SUPTYPEID, ADDRESSNAME, CURRENCYID, PURCHASEMAN, SURPLUSMONEY, PAYTERM, ",
        "CREDITRAT, STARTADVRECV, STARTRECEIVABLE, CURADVRECV, CURRECEIVABLE, PRICEOFTAX, ",
        "AMOUNTQUOTA, COLUMNONE, COLUMNTWO",
        "from T_SUPPLIERMASTER"
    })
    @ConstructorArgs({
        @Arg(column="SUPPLIERID", javaType=String.class, jdbcType=JdbcType.VARCHAR, id=true),
        @Arg(column="SUPTYPEID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="ADDRESSNAME", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CURRENCYID", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="PURCHASEMAN", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="SURPLUSMONEY", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PAYTERM", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="CREDITRAT", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="STARTADVRECV", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="STARTRECEIVABLE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CURADVRECV", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="CURRECEIVABLE", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="PRICEOFTAX", javaType=String.class, jdbcType=JdbcType.CHAR),
        @Arg(column="AMOUNTQUOTA", javaType=BigDecimal.class, jdbcType=JdbcType.DECIMAL),
        @Arg(column="COLUMNONE", javaType=String.class, jdbcType=JdbcType.VARCHAR),
        @Arg(column="COLUMNTWO", javaType=String.class, jdbcType=JdbcType.VARCHAR)
    })
    List<TSuppliermaster> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SUPPLIERMASTER
     *
     * @mbggenerated
     */
    @Update({
        "update T_SUPPLIERMASTER",
        "set SUPTYPEID = #{suptypeid,jdbcType=VARCHAR},",
          "ADDRESSNAME = #{addressname,jdbcType=VARCHAR},",
          "CURRENCYID = #{currencyid,jdbcType=VARCHAR},",
          "PURCHASEMAN = #{purchaseman,jdbcType=VARCHAR},",
          "SURPLUSMONEY = #{surplusmoney,jdbcType=DECIMAL},",
          "PAYTERM = #{payterm,jdbcType=VARCHAR},",
          "CREDITRAT = #{creditrat,jdbcType=VARCHAR},",
          "STARTADVRECV = #{startadvrecv,jdbcType=DECIMAL},",
          "STARTRECEIVABLE = #{startreceivable,jdbcType=DECIMAL},",
          "CURADVRECV = #{curadvrecv,jdbcType=DECIMAL},",
          "CURRECEIVABLE = #{curreceivable,jdbcType=DECIMAL},",
          "PRICEOFTAX = #{priceoftax,jdbcType=CHAR},",
          "AMOUNTQUOTA = #{amountquota,jdbcType=DECIMAL},",
          "COLUMNONE = #{columnone,jdbcType=VARCHAR},",
          "COLUMNTWO = #{columntwo,jdbcType=VARCHAR}",
        "where SUPPLIERID = #{supplierid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TSuppliermaster record);
}